/*
 * This file is generated by jOOQ.
 */
package com.db_access.jooq.tables;


import com.db_access.jooq.Indexes;
import com.db_access.jooq.Keys;
import com.db_access.jooq._1137VetCarRpDatabase;
import com.db_access.jooq.tables.records.CustomersRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Customers extends TableImpl<CustomersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>1137_VET_Car_RP_Database.customers</code>
     */
    public static final Customers CUSTOMERS = new Customers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CustomersRecord> getRecordType() {
        return CustomersRecord.class;
    }

    /**
     * The column <code>1137_VET_Car_RP_Database.customers.id</code>.
     */
    public final TableField<CustomersRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>1137_VET_Car_RP_Database.customers.full_name</code>.
     */
    public final TableField<CustomersRecord, String> FULL_NAME = createField(DSL.name("full_name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>1137_VET_Car_RP_Database.customers.phone_number</code>.
     */
    public final TableField<CustomersRecord, String> PHONE_NUMBER = createField(DSL.name("phone_number"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>1137_VET_Car_RP_Database.customers.email</code>.
     */
    public final TableField<CustomersRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>1137_VET_Car_RP_Database.customers.password</code>.
     */
    public final TableField<CustomersRecord, String> PASSWORD = createField(DSL.name("password"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>1137_VET_Car_RP_Database.customers.file_name</code>.
     */
    public final TableField<CustomersRecord, String> FILE_NAME = createField(DSL.name("file_name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>1137_VET_Car_RP_Database.customers.file_url</code>.
     */
    public final TableField<CustomersRecord, String> FILE_URL = createField(DSL.name("file_url"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>1137_VET_Car_RP_Database.customers.is_verified</code>.
     * 0: Unverified, 1: Verified (OTP)
     */
    public final TableField<CustomersRecord, Byte> IS_VERIFIED = createField(DSL.name("is_verified"), SQLDataType.TINYINT.defaultValue(DSL.inline("0", SQLDataType.TINYINT)), this, "0: Unverified, 1: Verified (OTP)");

    /**
     * The column <code>1137_VET_Car_RP_Database.customers.os_type</code>. 1:
     * iOS, 2: Android
     */
    public final TableField<CustomersRecord, Byte> OS_TYPE = createField(DSL.name("os_type"), SQLDataType.TINYINT, this, "1: iOS, 2: Android");

    /**
     * The column <code>1137_VET_Car_RP_Database.customers.language</code>. 1:
     * English, 2: Khmer, 3: Chinese
     */
    public final TableField<CustomersRecord, Byte> LANGUAGE = createField(DSL.name("language"), SQLDataType.TINYINT.defaultValue(DSL.inline("1", SQLDataType.TINYINT)), this, "1: English, 2: Khmer, 3: Chinese");

    /**
     * The column <code>1137_VET_Car_RP_Database.customers.device_token</code>.
     * FCM Push Token
     */
    public final TableField<CustomersRecord, String> DEVICE_TOKEN = createField(DSL.name("device_token"), SQLDataType.CLOB, this, "FCM Push Token");

    /**
     * The column <code>1137_VET_Car_RP_Database.customers.last_login</code>.
     */
    public final TableField<CustomersRecord, LocalDateTime> LAST_LOGIN = createField(DSL.name("last_login"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>1137_VET_Car_RP_Database.customers.created</code>.
     */
    public final TableField<CustomersRecord, LocalDateTime> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>1137_VET_Car_RP_Database.customers.modified</code>.
     */
    public final TableField<CustomersRecord, LocalDateTime> MODIFIED = createField(DSL.name("modified"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>1137_VET_Car_RP_Database.customers.is_active</code>. 1:
     * Active, 2: Blocked/Deleted
     */
    public final TableField<CustomersRecord, Byte> IS_ACTIVE = createField(DSL.name("is_active"), SQLDataType.TINYINT.defaultValue(DSL.inline("1", SQLDataType.TINYINT)), this, "1: Active, 2: Blocked/Deleted");

    private Customers(Name alias, Table<CustomersRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Customers(Name alias, Table<CustomersRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>1137_VET_Car_RP_Database.customers</code> table
     * reference
     */
    public Customers(String alias) {
        this(DSL.name(alias), CUSTOMERS);
    }

    /**
     * Create an aliased <code>1137_VET_Car_RP_Database.customers</code> table
     * reference
     */
    public Customers(Name alias) {
        this(alias, CUSTOMERS);
    }

    /**
     * Create a <code>1137_VET_Car_RP_Database.customers</code> table reference
     */
    public Customers() {
        this(DSL.name("customers"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : _1137VetCarRpDatabase._1137_VET_CAR_RP_DATABASE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.CUSTOMERS_IDX_CUSTOMERS_IS_ACTIVE);
    }

    @Override
    public Identity<CustomersRecord, Long> getIdentity() {
        return (Identity<CustomersRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<CustomersRecord> getPrimaryKey() {
        return Keys.KEY_CUSTOMERS_PRIMARY;
    }

    @Override
    public List<UniqueKey<CustomersRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_CUSTOMERS_PHONE_NUMBER_UNIQUE);
    }

    @Override
    public Customers as(String alias) {
        return new Customers(DSL.name(alias), this);
    }

    @Override
    public Customers as(Name alias) {
        return new Customers(alias, this);
    }

    @Override
    public Customers as(Table<?> alias) {
        return new Customers(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Customers rename(String name) {
        return new Customers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Customers rename(Name name) {
        return new Customers(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Customers rename(Table<?> name) {
        return new Customers(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Customers where(Condition condition) {
        return new Customers(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Customers where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Customers where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Customers where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Customers where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Customers where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Customers where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Customers where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Customers whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Customers whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
