/*
 * This file is generated by jOOQ.
 */
package com.db_access.jooq.tables;


import com.db_access.jooq.Indexes;
import com.db_access.jooq.Keys;
import com.db_access.jooq._1137VetCarRpDatabase;
import com.db_access.jooq.tables.records.CustomerReviewsRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomerReviews extends TableImpl<CustomerReviewsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>1137_VET_Car_RP_Database.customer_reviews</code>
     */
    public static final CustomerReviews CUSTOMER_REVIEWS = new CustomerReviews();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CustomerReviewsRecord> getRecordType() {
        return CustomerReviewsRecord.class;
    }

    /**
     * The column <code>1137_VET_Car_RP_Database.customer_reviews.id</code>.
     */
    public final TableField<CustomerReviewsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.customer_reviews.customer_id</code>.
     * References customers.id
     */
    public final TableField<CustomerReviewsRecord, Long> CUSTOMER_ID = createField(DSL.name("customer_id"), SQLDataType.BIGINT.nullable(false), this, "References customers.id");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.customer_reviews.sales_order_id</code>.
     * References sales_orders.id
     */
    public final TableField<CustomerReviewsRecord, Long> SALES_ORDER_ID = createField(DSL.name("sales_order_id"), SQLDataType.BIGINT, this, "References sales_orders.id");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.customer_reviews.vehicle_id</code>.
     * References vehicles.id
     */
    public final TableField<CustomerReviewsRecord, Long> VEHICLE_ID = createField(DSL.name("vehicle_id"), SQLDataType.BIGINT.nullable(false), this, "References vehicles.id");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.customer_reviews.rating_stars</code>.
     */
    public final TableField<CustomerReviewsRecord, BigDecimal> RATING_STARS = createField(DSL.name("rating_stars"), SQLDataType.DECIMAL(3, 1).defaultValue(DSL.inline("5.0", SQLDataType.DECIMAL)), this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.customer_reviews.comment</code>.
     */
    public final TableField<CustomerReviewsRecord, String> COMMENT = createField(DSL.name("comment"), SQLDataType.CLOB, this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.customer_reviews.is_disabled</code>. 0:
     * Enabled, 1: Disabled to App
     */
    public final TableField<CustomerReviewsRecord, Byte> IS_DISABLED = createField(DSL.name("is_disabled"), SQLDataType.TINYINT.defaultValue(DSL.inline("0", SQLDataType.TINYINT)), this, "0: Enabled, 1: Disabled to App");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.customer_reviews.created</code>.
     */
    public final TableField<CustomerReviewsRecord, LocalDateTime> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.customer_reviews.created_by</code>.
     */
    public final TableField<CustomerReviewsRecord, Long> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.BIGINT, this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.customer_reviews.modified</code>.
     */
    public final TableField<CustomerReviewsRecord, LocalDateTime> MODIFIED = createField(DSL.name("modified"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.customer_reviews.modified_by</code>.
     */
    public final TableField<CustomerReviewsRecord, Long> MODIFIED_BY = createField(DSL.name("modified_by"), SQLDataType.BIGINT, this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.customer_reviews.is_active</code>. 0:
     * Inactive, 1: Active
     */
    public final TableField<CustomerReviewsRecord, Byte> IS_ACTIVE = createField(DSL.name("is_active"), SQLDataType.TINYINT.defaultValue(DSL.inline("1", SQLDataType.TINYINT)), this, "0: Inactive, 1: Active");

    private CustomerReviews(Name alias, Table<CustomerReviewsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CustomerReviews(Name alias, Table<CustomerReviewsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>1137_VET_Car_RP_Database.customer_reviews</code>
     * table reference
     */
    public CustomerReviews(String alias) {
        this(DSL.name(alias), CUSTOMER_REVIEWS);
    }

    /**
     * Create an aliased <code>1137_VET_Car_RP_Database.customer_reviews</code>
     * table reference
     */
    public CustomerReviews(Name alias) {
        this(alias, CUSTOMER_REVIEWS);
    }

    /**
     * Create a <code>1137_VET_Car_RP_Database.customer_reviews</code> table
     * reference
     */
    public CustomerReviews() {
        this(DSL.name("customer_reviews"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : _1137VetCarRpDatabase._1137_VET_CAR_RP_DATABASE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.CUSTOMER_REVIEWS_IDX_REVIEWS_CUSTOMER, Indexes.CUSTOMER_REVIEWS_IDX_REVIEWS_IS_ACTIVE, Indexes.CUSTOMER_REVIEWS_IDX_REVIEWS_IS_DISABLED, Indexes.CUSTOMER_REVIEWS_IDX_REVIEWS_VEHICLE);
    }

    @Override
    public Identity<CustomerReviewsRecord, Long> getIdentity() {
        return (Identity<CustomerReviewsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<CustomerReviewsRecord> getPrimaryKey() {
        return Keys.KEY_CUSTOMER_REVIEWS_PRIMARY;
    }

    @Override
    public CustomerReviews as(String alias) {
        return new CustomerReviews(DSL.name(alias), this);
    }

    @Override
    public CustomerReviews as(Name alias) {
        return new CustomerReviews(alias, this);
    }

    @Override
    public CustomerReviews as(Table<?> alias) {
        return new CustomerReviews(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CustomerReviews rename(String name) {
        return new CustomerReviews(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CustomerReviews rename(Name name) {
        return new CustomerReviews(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CustomerReviews rename(Table<?> name) {
        return new CustomerReviews(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerReviews where(Condition condition) {
        return new CustomerReviews(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerReviews where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerReviews where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerReviews where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomerReviews where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomerReviews where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomerReviews where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomerReviews where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerReviews whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerReviews whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
