/*
 * This file is generated by jOOQ.
 */
package com.db_access.jooq.tables;


import com.db_access.jooq.Indexes;
import com.db_access.jooq.Keys;
import com.db_access.jooq._1137VetCarRpDatabase;
import com.db_access.jooq.tables.records.CustomerReviewFilesRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomerReviewFiles extends TableImpl<CustomerReviewFilesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>1137_VET_Car_RP_Database.customer_review_files</code>
     */
    public static final CustomerReviewFiles CUSTOMER_REVIEW_FILES = new CustomerReviewFiles();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CustomerReviewFilesRecord> getRecordType() {
        return CustomerReviewFilesRecord.class;
    }

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.customer_review_files.id</code>.
     */
    public final TableField<CustomerReviewFilesRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.customer_review_files.review_id</code>.
     * References customer_reviews.id
     */
    public final TableField<CustomerReviewFilesRecord, Long> REVIEW_ID = createField(DSL.name("review_id"), SQLDataType.BIGINT.nullable(false), this, "References customer_reviews.id");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.customer_review_files.file_name</code>.
     */
    public final TableField<CustomerReviewFilesRecord, String> FILE_NAME = createField(DSL.name("file_name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.customer_review_files.file_url</code>.
     */
    public final TableField<CustomerReviewFilesRecord, String> FILE_URL = createField(DSL.name("file_url"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.customer_review_files.created</code>.
     */
    public final TableField<CustomerReviewFilesRecord, LocalDateTime> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    private CustomerReviewFiles(Name alias, Table<CustomerReviewFilesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CustomerReviewFiles(Name alias, Table<CustomerReviewFilesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased
     * <code>1137_VET_Car_RP_Database.customer_review_files</code> table
     * reference
     */
    public CustomerReviewFiles(String alias) {
        this(DSL.name(alias), CUSTOMER_REVIEW_FILES);
    }

    /**
     * Create an aliased
     * <code>1137_VET_Car_RP_Database.customer_review_files</code> table
     * reference
     */
    public CustomerReviewFiles(Name alias) {
        this(alias, CUSTOMER_REVIEW_FILES);
    }

    /**
     * Create a <code>1137_VET_Car_RP_Database.customer_review_files</code>
     * table reference
     */
    public CustomerReviewFiles() {
        this(DSL.name("customer_review_files"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : _1137VetCarRpDatabase._1137_VET_CAR_RP_DATABASE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.CUSTOMER_REVIEW_FILES_IDX_REVIEW_FILES_REVIEW);
    }

    @Override
    public Identity<CustomerReviewFilesRecord, Long> getIdentity() {
        return (Identity<CustomerReviewFilesRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<CustomerReviewFilesRecord> getPrimaryKey() {
        return Keys.KEY_CUSTOMER_REVIEW_FILES_PRIMARY;
    }

    @Override
    public CustomerReviewFiles as(String alias) {
        return new CustomerReviewFiles(DSL.name(alias), this);
    }

    @Override
    public CustomerReviewFiles as(Name alias) {
        return new CustomerReviewFiles(alias, this);
    }

    @Override
    public CustomerReviewFiles as(Table<?> alias) {
        return new CustomerReviewFiles(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CustomerReviewFiles rename(String name) {
        return new CustomerReviewFiles(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CustomerReviewFiles rename(Name name) {
        return new CustomerReviewFiles(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CustomerReviewFiles rename(Table<?> name) {
        return new CustomerReviewFiles(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerReviewFiles where(Condition condition) {
        return new CustomerReviewFiles(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerReviewFiles where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerReviewFiles where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerReviewFiles where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomerReviewFiles where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomerReviewFiles where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomerReviewFiles where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomerReviewFiles where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerReviewFiles whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerReviewFiles whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
