/*
 * This file is generated by jOOQ.
 */
package com.db_access.jooq.tables;


import com.db_access.jooq.Keys;
import com.db_access.jooq._1137VetCarRpDatabase;
import com.db_access.jooq.tables.records.GroupsApiRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GroupsApi extends TableImpl<GroupsApiRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>1137_VET_Car_RP_Database.groups_api</code>
     */
    public static final GroupsApi GROUPS_API = new GroupsApi();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GroupsApiRecord> getRecordType() {
        return GroupsApiRecord.class;
    }

    /**
     * The column <code>1137_VET_Car_RP_Database.groups_api.id</code>.
     */
    public final TableField<GroupsApiRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>1137_VET_Car_RP_Database.groups_api.sys_code</code>.
     */
    public final TableField<GroupsApiRecord, String> SYS_CODE = createField(DSL.name("sys_code"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>1137_VET_Car_RP_Database.groups_api.name</code>.
     */
    public final TableField<GroupsApiRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>1137_VET_Car_RP_Database.groups_api.created</code>.
     */
    public final TableField<GroupsApiRecord, LocalDateTime> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>1137_VET_Car_RP_Database.groups_api.created_by</code>.
     */
    public final TableField<GroupsApiRecord, Long> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>1137_VET_Car_RP_Database.groups_api.modified</code>.
     */
    public final TableField<GroupsApiRecord, LocalDateTime> MODIFIED = createField(DSL.name("modified"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>1137_VET_Car_RP_Database.groups_api.modified_by</code>.
     */
    public final TableField<GroupsApiRecord, Long> MODIFIED_BY = createField(DSL.name("modified_by"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>1137_VET_Car_RP_Database.groups_api.is_active</code>. 1
     * : active , 2 : delete
     */
    public final TableField<GroupsApiRecord, Byte> IS_ACTIVE = createField(DSL.name("is_active"), SQLDataType.TINYINT.defaultValue(DSL.inline("1", SQLDataType.TINYINT)), this, "1 : active , 2 : delete");

    private GroupsApi(Name alias, Table<GroupsApiRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private GroupsApi(Name alias, Table<GroupsApiRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>1137_VET_Car_RP_Database.groups_api</code> table
     * reference
     */
    public GroupsApi(String alias) {
        this(DSL.name(alias), GROUPS_API);
    }

    /**
     * Create an aliased <code>1137_VET_Car_RP_Database.groups_api</code> table
     * reference
     */
    public GroupsApi(Name alias) {
        this(alias, GROUPS_API);
    }

    /**
     * Create a <code>1137_VET_Car_RP_Database.groups_api</code> table reference
     */
    public GroupsApi() {
        this(DSL.name("groups_api"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : _1137VetCarRpDatabase._1137_VET_CAR_RP_DATABASE;
    }

    @Override
    public Identity<GroupsApiRecord, Long> getIdentity() {
        return (Identity<GroupsApiRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<GroupsApiRecord> getPrimaryKey() {
        return Keys.KEY_GROUPS_API_PRIMARY;
    }

    @Override
    public GroupsApi as(String alias) {
        return new GroupsApi(DSL.name(alias), this);
    }

    @Override
    public GroupsApi as(Name alias) {
        return new GroupsApi(alias, this);
    }

    @Override
    public GroupsApi as(Table<?> alias) {
        return new GroupsApi(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public GroupsApi rename(String name) {
        return new GroupsApi(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GroupsApi rename(Name name) {
        return new GroupsApi(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public GroupsApi rename(Table<?> name) {
        return new GroupsApi(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GroupsApi where(Condition condition) {
        return new GroupsApi(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GroupsApi where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GroupsApi where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GroupsApi where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GroupsApi where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GroupsApi where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GroupsApi where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GroupsApi where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GroupsApi whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GroupsApi whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
