/*
 * This file is generated by jOOQ.
 */
package com.db_access.jooq.tables;


import com.db_access.jooq.Indexes;
import com.db_access.jooq.Keys;
import com.db_access.jooq._1137VetCarRpDatabase;
import com.db_access.jooq.tables.records.PrivacyTermsRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PrivacyTerms extends TableImpl<PrivacyTermsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>1137_VET_Car_RP_Database.privacy_terms</code>
     */
    public static final PrivacyTerms PRIVACY_TERMS = new PrivacyTerms();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PrivacyTermsRecord> getRecordType() {
        return PrivacyTermsRecord.class;
    }

    /**
     * The column <code>1137_VET_Car_RP_Database.privacy_terms.id</code>.
     */
    public final TableField<PrivacyTermsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>1137_VET_Car_RP_Database.privacy_terms.type</code>. 1:
     * Privacy, 2: Terms
     */
    public final TableField<PrivacyTermsRecord, Byte> TYPE = createField(DSL.name("type"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("1", SQLDataType.TINYINT)), this, "1: Privacy, 2: Terms");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.privacy_terms.description_kh</code>.
     */
    public final TableField<PrivacyTermsRecord, String> DESCRIPTION_KH = createField(DSL.name("description_kh"), SQLDataType.CLOB, this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.privacy_terms.description_en</code>.
     */
    public final TableField<PrivacyTermsRecord, String> DESCRIPTION_EN = createField(DSL.name("description_en"), SQLDataType.CLOB, this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.privacy_terms.description_zh</code>.
     */
    public final TableField<PrivacyTermsRecord, String> DESCRIPTION_ZH = createField(DSL.name("description_zh"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>1137_VET_Car_RP_Database.privacy_terms.created</code>.
     */
    public final TableField<PrivacyTermsRecord, LocalDateTime> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.privacy_terms.created_by</code>.
     */
    public final TableField<PrivacyTermsRecord, Long> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>1137_VET_Car_RP_Database.privacy_terms.modified</code>.
     */
    public final TableField<PrivacyTermsRecord, LocalDateTime> MODIFIED = createField(DSL.name("modified"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.privacy_terms.modified_by</code>.
     */
    public final TableField<PrivacyTermsRecord, Long> MODIFIED_BY = createField(DSL.name("modified_by"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>1137_VET_Car_RP_Database.privacy_terms.is_active</code>.
     * 0: Inactive, 1: Active
     */
    public final TableField<PrivacyTermsRecord, Byte> IS_ACTIVE = createField(DSL.name("is_active"), SQLDataType.TINYINT.defaultValue(DSL.inline("1", SQLDataType.TINYINT)), this, "0: Inactive, 1: Active");

    private PrivacyTerms(Name alias, Table<PrivacyTermsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PrivacyTerms(Name alias, Table<PrivacyTermsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>1137_VET_Car_RP_Database.privacy_terms</code>
     * table reference
     */
    public PrivacyTerms(String alias) {
        this(DSL.name(alias), PRIVACY_TERMS);
    }

    /**
     * Create an aliased <code>1137_VET_Car_RP_Database.privacy_terms</code>
     * table reference
     */
    public PrivacyTerms(Name alias) {
        this(alias, PRIVACY_TERMS);
    }

    /**
     * Create a <code>1137_VET_Car_RP_Database.privacy_terms</code> table
     * reference
     */
    public PrivacyTerms() {
        this(DSL.name("privacy_terms"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : _1137VetCarRpDatabase._1137_VET_CAR_RP_DATABASE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.PRIVACY_TERMS_IDX_PRIVACY_TERMS_IS_ACTIVE, Indexes.PRIVACY_TERMS_IDX_PRIVACY_TERMS_TYPE);
    }

    @Override
    public Identity<PrivacyTermsRecord, Long> getIdentity() {
        return (Identity<PrivacyTermsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<PrivacyTermsRecord> getPrimaryKey() {
        return Keys.KEY_PRIVACY_TERMS_PRIMARY;
    }

    @Override
    public PrivacyTerms as(String alias) {
        return new PrivacyTerms(DSL.name(alias), this);
    }

    @Override
    public PrivacyTerms as(Name alias) {
        return new PrivacyTerms(alias, this);
    }

    @Override
    public PrivacyTerms as(Table<?> alias) {
        return new PrivacyTerms(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PrivacyTerms rename(String name) {
        return new PrivacyTerms(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PrivacyTerms rename(Name name) {
        return new PrivacyTerms(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PrivacyTerms rename(Table<?> name) {
        return new PrivacyTerms(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PrivacyTerms where(Condition condition) {
        return new PrivacyTerms(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PrivacyTerms where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PrivacyTerms where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PrivacyTerms where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PrivacyTerms where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PrivacyTerms where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PrivacyTerms where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PrivacyTerms where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PrivacyTerms whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PrivacyTerms whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
