/*
 * This file is generated by jOOQ.
 */
package com.db_access.jooq.tables;


import com.db_access.jooq.Indexes;
import com.db_access.jooq.Keys;
import com.db_access.jooq._1137VetCarRpDatabase;
import com.db_access.jooq.tables.records.SalesOrderPaymentsRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SalesOrderPayments extends TableImpl<SalesOrderPaymentsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>1137_VET_Car_RP_Database.sales_order_payments</code>
     */
    public static final SalesOrderPayments SALES_ORDER_PAYMENTS = new SalesOrderPayments();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SalesOrderPaymentsRecord> getRecordType() {
        return SalesOrderPaymentsRecord.class;
    }

    /**
     * The column <code>1137_VET_Car_RP_Database.sales_order_payments.id</code>.
     */
    public final TableField<SalesOrderPaymentsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.sales_order_payments.sales_order_id</code>.
     */
    public final TableField<SalesOrderPaymentsRecord, Long> SALES_ORDER_ID = createField(DSL.name("sales_order_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.sales_order_payments.transaction_id</code>.
     * tran_id from Payway
     */
    public final TableField<SalesOrderPaymentsRecord, String> TRANSACTION_ID = createField(DSL.name("transaction_id"), SQLDataType.VARCHAR(50), this, "tran_id from Payway");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.sales_order_payments.qr_string</code>.
     */
    public final TableField<SalesOrderPaymentsRecord, String> QR_STRING = createField(DSL.name("qr_string"), SQLDataType.CLOB, this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.sales_order_payments.qr_image</code>.
     */
    public final TableField<SalesOrderPaymentsRecord, String> QR_IMAGE = createField(DSL.name("qr_image"), SQLDataType.CLOB, this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.sales_order_payments.abapay_url</code>.
     */
    public final TableField<SalesOrderPaymentsRecord, String> ABAPAY_URL = createField(DSL.name("abapay_url"), SQLDataType.CLOB, this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.sales_order_payments.currency</code>.
     */
    public final TableField<SalesOrderPaymentsRecord, String> CURRENCY = createField(DSL.name("currency"), SQLDataType.VARCHAR(10).defaultValue(DSL.inline("USD", SQLDataType.VARCHAR)), this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.sales_order_payments.amount</code>.
     */
    public final TableField<SalesOrderPaymentsRecord, BigDecimal> AMOUNT = createField(DSL.name("amount"), SQLDataType.DECIMAL(17, 4).defaultValue(DSL.inline("0.0000", SQLDataType.DECIMAL)), this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.sales_order_payments.created</code>.
     */
    public final TableField<SalesOrderPaymentsRecord, LocalDateTime> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.sales_order_payments.expired</code>.
     */
    public final TableField<SalesOrderPaymentsRecord, LocalDateTime> EXPIRED = createField(DSL.name("expired"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.sales_order_payments.status</code>. 1:
     * Pending, 2: Paid, 3: Expired
     */
    public final TableField<SalesOrderPaymentsRecord, Byte> STATUS = createField(DSL.name("status"), SQLDataType.TINYINT.defaultValue(DSL.inline("1", SQLDataType.TINYINT)), this, "1: Pending, 2: Paid, 3: Expired");

    private SalesOrderPayments(Name alias, Table<SalesOrderPaymentsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private SalesOrderPayments(Name alias, Table<SalesOrderPaymentsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased
     * <code>1137_VET_Car_RP_Database.sales_order_payments</code> table
     * reference
     */
    public SalesOrderPayments(String alias) {
        this(DSL.name(alias), SALES_ORDER_PAYMENTS);
    }

    /**
     * Create an aliased
     * <code>1137_VET_Car_RP_Database.sales_order_payments</code> table
     * reference
     */
    public SalesOrderPayments(Name alias) {
        this(alias, SALES_ORDER_PAYMENTS);
    }

    /**
     * Create a <code>1137_VET_Car_RP_Database.sales_order_payments</code> table
     * reference
     */
    public SalesOrderPayments() {
        this(DSL.name("sales_order_payments"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : _1137VetCarRpDatabase._1137_VET_CAR_RP_DATABASE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.SALES_ORDER_PAYMENTS_SALES_ORDER_IDX, Indexes.SALES_ORDER_PAYMENTS_TRAN_IDX);
    }

    @Override
    public Identity<SalesOrderPaymentsRecord, Long> getIdentity() {
        return (Identity<SalesOrderPaymentsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<SalesOrderPaymentsRecord> getPrimaryKey() {
        return Keys.KEY_SALES_ORDER_PAYMENTS_PRIMARY;
    }

    @Override
    public SalesOrderPayments as(String alias) {
        return new SalesOrderPayments(DSL.name(alias), this);
    }

    @Override
    public SalesOrderPayments as(Name alias) {
        return new SalesOrderPayments(alias, this);
    }

    @Override
    public SalesOrderPayments as(Table<?> alias) {
        return new SalesOrderPayments(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SalesOrderPayments rename(String name) {
        return new SalesOrderPayments(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SalesOrderPayments rename(Name name) {
        return new SalesOrderPayments(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SalesOrderPayments rename(Table<?> name) {
        return new SalesOrderPayments(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SalesOrderPayments where(Condition condition) {
        return new SalesOrderPayments(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SalesOrderPayments where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SalesOrderPayments where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SalesOrderPayments where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SalesOrderPayments where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SalesOrderPayments where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SalesOrderPayments where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SalesOrderPayments where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SalesOrderPayments whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SalesOrderPayments whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
