/*
 * This file is generated by jOOQ.
 */
package com.db_access.jooq.tables;


import com.db_access.jooq.Indexes;
import com.db_access.jooq.Keys;
import com.db_access.jooq._1137VetCarRpDatabase;
import com.db_access.jooq.tables.records.SalesOrderTripSubLocationsRecord;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SalesOrderTripSubLocations extends TableImpl<SalesOrderTripSubLocationsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>1137_VET_Car_RP_Database.sales_order_trip_sub_locations</code>
     */
    public static final SalesOrderTripSubLocations SALES_ORDER_TRIP_SUB_LOCATIONS = new SalesOrderTripSubLocations();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SalesOrderTripSubLocationsRecord> getRecordType() {
        return SalesOrderTripSubLocationsRecord.class;
    }

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.sales_order_trip_sub_locations.id</code>.
     */
    public final TableField<SalesOrderTripSubLocationsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.sales_order_trip_sub_locations.trip_id</code>.
     * References sales_order_trips.id
     */
    public final TableField<SalesOrderTripSubLocationsRecord, Long> TRIP_ID = createField(DSL.name("trip_id"), SQLDataType.BIGINT.nullable(false), this, "References sales_order_trips.id");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.sales_order_trip_sub_locations.sub_location_id</code>.
     * References sub_locations.id
     */
    public final TableField<SalesOrderTripSubLocationsRecord, Long> SUB_LOCATION_ID = createField(DSL.name("sub_location_id"), SQLDataType.BIGINT.nullable(false), this, "References sub_locations.id");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.sales_order_trip_sub_locations.price</code>.
     * Snapshot price at time of order
     */
    public final TableField<SalesOrderTripSubLocationsRecord, BigDecimal> PRICE = createField(DSL.name("price"), SQLDataType.DECIMAL(15, 2).defaultValue(DSL.inline("0.00", SQLDataType.DECIMAL)), this, "Snapshot price at time of order");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.sales_order_trip_sub_locations.sort_order</code>.
     */
    public final TableField<SalesOrderTripSubLocationsRecord, Integer> SORT_ORDER = createField(DSL.name("sort_order"), SQLDataType.INTEGER.defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.sales_order_trip_sub_locations.is_active</code>.
     * 0: Inactive, 1: Active
     */
    public final TableField<SalesOrderTripSubLocationsRecord, Byte> IS_ACTIVE = createField(DSL.name("is_active"), SQLDataType.TINYINT.defaultValue(DSL.inline("1", SQLDataType.TINYINT)), this, "0: Inactive, 1: Active");

    private SalesOrderTripSubLocations(Name alias, Table<SalesOrderTripSubLocationsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private SalesOrderTripSubLocations(Name alias, Table<SalesOrderTripSubLocationsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased
     * <code>1137_VET_Car_RP_Database.sales_order_trip_sub_locations</code>
     * table reference
     */
    public SalesOrderTripSubLocations(String alias) {
        this(DSL.name(alias), SALES_ORDER_TRIP_SUB_LOCATIONS);
    }

    /**
     * Create an aliased
     * <code>1137_VET_Car_RP_Database.sales_order_trip_sub_locations</code>
     * table reference
     */
    public SalesOrderTripSubLocations(Name alias) {
        this(alias, SALES_ORDER_TRIP_SUB_LOCATIONS);
    }

    /**
     * Create a
     * <code>1137_VET_Car_RP_Database.sales_order_trip_sub_locations</code>
     * table reference
     */
    public SalesOrderTripSubLocations() {
        this(DSL.name("sales_order_trip_sub_locations"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : _1137VetCarRpDatabase._1137_VET_CAR_RP_DATABASE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.SALES_ORDER_TRIP_SUB_LOCATIONS_IDX_SO_TRIP_SUB_IS_ACTIVE, Indexes.SALES_ORDER_TRIP_SUB_LOCATIONS_IDX_SO_TRIP_SUB_TRIP);
    }

    @Override
    public Identity<SalesOrderTripSubLocationsRecord, Long> getIdentity() {
        return (Identity<SalesOrderTripSubLocationsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<SalesOrderTripSubLocationsRecord> getPrimaryKey() {
        return Keys.KEY_SALES_ORDER_TRIP_SUB_LOCATIONS_PRIMARY;
    }

    @Override
    public SalesOrderTripSubLocations as(String alias) {
        return new SalesOrderTripSubLocations(DSL.name(alias), this);
    }

    @Override
    public SalesOrderTripSubLocations as(Name alias) {
        return new SalesOrderTripSubLocations(alias, this);
    }

    @Override
    public SalesOrderTripSubLocations as(Table<?> alias) {
        return new SalesOrderTripSubLocations(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SalesOrderTripSubLocations rename(String name) {
        return new SalesOrderTripSubLocations(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SalesOrderTripSubLocations rename(Name name) {
        return new SalesOrderTripSubLocations(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SalesOrderTripSubLocations rename(Table<?> name) {
        return new SalesOrderTripSubLocations(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SalesOrderTripSubLocations where(Condition condition) {
        return new SalesOrderTripSubLocations(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SalesOrderTripSubLocations where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SalesOrderTripSubLocations where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SalesOrderTripSubLocations where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SalesOrderTripSubLocations where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SalesOrderTripSubLocations where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SalesOrderTripSubLocations where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SalesOrderTripSubLocations where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SalesOrderTripSubLocations whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SalesOrderTripSubLocations whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
