/*
 * This file is generated by jOOQ.
 */
package com.db_access.jooq.tables;


import com.db_access.jooq.Indexes;
import com.db_access.jooq.Keys;
import com.db_access.jooq._1137VetCarRpDatabase;
import com.db_access.jooq.tables.records.SalesOrdersRecord;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SalesOrders extends TableImpl<SalesOrdersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>1137_VET_Car_RP_Database.sales_orders</code>
     */
    public static final SalesOrders SALES_ORDERS = new SalesOrders();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SalesOrdersRecord> getRecordType() {
        return SalesOrdersRecord.class;
    }

    /**
     * The column <code>1137_VET_Car_RP_Database.sales_orders.id</code>.
     */
    public final TableField<SalesOrdersRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>1137_VET_Car_RP_Database.sales_orders.order_no</code>.
     */
    public final TableField<SalesOrdersRecord, String> ORDER_NO = createField(DSL.name("order_no"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.sales_orders.customer_id</code>.
     * References customers.id (Walk-in orders are NULL)
     */
    public final TableField<SalesOrdersRecord, Long> CUSTOMER_ID = createField(DSL.name("customer_id"), SQLDataType.BIGINT, this, "References customers.id (Walk-in orders are NULL)");

    /**
     * The column <code>1137_VET_Car_RP_Database.sales_orders.vehicle_id</code>.
     * References vehicles.id
     */
    public final TableField<SalesOrdersRecord, Long> VEHICLE_ID = createField(DSL.name("vehicle_id"), SQLDataType.BIGINT.nullable(false), this, "References vehicles.id");

    /**
     * The column <code>1137_VET_Car_RP_Database.sales_orders.order_type</code>.
     * 1: APP, 2: SYSTEM
     */
    public final TableField<SalesOrdersRecord, Byte> ORDER_TYPE = createField(DSL.name("order_type"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("1", SQLDataType.TINYINT)), this, "1: APP, 2: SYSTEM");

    /**
     * The column <code>1137_VET_Car_RP_Database.sales_orders.order_date</code>.
     */
    public final TableField<SalesOrdersRecord, LocalDateTime> ORDER_DATE = createField(DSL.name("order_date"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.sales_orders.passenger_name</code>.
     */
    public final TableField<SalesOrdersRecord, String> PASSENGER_NAME = createField(DSL.name("passenger_name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.sales_orders.passenger_phone</code>.
     */
    public final TableField<SalesOrdersRecord, String> PASSENGER_PHONE = createField(DSL.name("passenger_phone"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.sales_orders.passenger_nationality_id</code>.
     * References nationalities.id
     */
    public final TableField<SalesOrdersRecord, Long> PASSENGER_NATIONALITY_ID = createField(DSL.name("passenger_nationality_id"), SQLDataType.BIGINT, this, "References nationalities.id");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.sales_orders.amount_of_people</code>.
     */
    public final TableField<SalesOrdersRecord, Integer> AMOUNT_OF_PEOPLE = createField(DSL.name("amount_of_people"), SQLDataType.INTEGER.defaultValue(DSL.inline("1", SQLDataType.INTEGER)), this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.sales_orders.amount_of_vehicles</code>.
     * Number of cars ordered
     */
    public final TableField<SalesOrdersRecord, Integer> AMOUNT_OF_VEHICLES = createField(DSL.name("amount_of_vehicles"), SQLDataType.INTEGER.defaultValue(DSL.inline("1", SQLDataType.INTEGER)), this, "Number of cars ordered");

    /**
     * The column <code>1137_VET_Car_RP_Database.sales_orders.remark</code>.
     */
    public final TableField<SalesOrdersRecord, String> REMARK = createField(DSL.name("remark"), SQLDataType.CLOB, this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.sales_orders.void_remark</code>.
     */
    public final TableField<SalesOrdersRecord, String> VOID_REMARK = createField(DSL.name("void_remark"), SQLDataType.CLOB, this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.sales_orders.vehicle_category_id</code>.
     * References vehicle_categories.id
     */
    public final TableField<SalesOrdersRecord, Long> VEHICLE_CATEGORY_ID = createField(DSL.name("vehicle_category_id"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("1", SQLDataType.BIGINT)), this, "References vehicle_categories.id");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.sales_orders.vehicle_rental_type_id</code>.
     * References vehicle_rental_types.id
     */
    public final TableField<SalesOrdersRecord, Long> VEHICLE_RENTAL_TYPE_ID = createField(DSL.name("vehicle_rental_type_id"), SQLDataType.BIGINT.nullable(false), this, "References vehicle_rental_types.id");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.sales_orders.journey_type</code>. 1:
     * One-Way, 2: One-Day-Tour, 3: Round-Trip, 4: Multi-City
     */
    public final TableField<SalesOrdersRecord, Byte> JOURNEY_TYPE = createField(DSL.name("journey_type"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("1", SQLDataType.TINYINT)), this, "1: One-Way, 2: One-Day-Tour, 3: Round-Trip, 4: Multi-City");

    /**
     * The column <code>1137_VET_Car_RP_Database.sales_orders.start_date</code>.
     */
    public final TableField<SalesOrdersRecord, LocalDate> START_DATE = createField(DSL.name("start_date"), SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>1137_VET_Car_RP_Database.sales_orders.end_date</code>.
     */
    public final TableField<SalesOrdersRecord, LocalDate> END_DATE = createField(DSL.name("end_date"), SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.sales_orders.pickup_location_id</code>.
     * References sub_locations.id (Optional)
     */
    public final TableField<SalesOrdersRecord, Long> PICKUP_LOCATION_ID = createField(DSL.name("pickup_location_id"), SQLDataType.BIGINT, this, "References sub_locations.id (Optional)");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.sales_orders.pickup_address</code>.
     */
    public final TableField<SalesOrdersRecord, String> PICKUP_ADDRESS = createField(DSL.name("pickup_address"), SQLDataType.VARCHAR(500), this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.sales_orders.pickup_latitude</code>.
     */
    public final TableField<SalesOrdersRecord, BigDecimal> PICKUP_LATITUDE = createField(DSL.name("pickup_latitude"), SQLDataType.DECIMAL(10, 8), this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.sales_orders.pickup_longitude</code>.
     */
    public final TableField<SalesOrdersRecord, BigDecimal> PICKUP_LONGITUDE = createField(DSL.name("pickup_longitude"), SQLDataType.DECIMAL(11, 8), this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.sales_orders.pickup_time</code>.
     */
    public final TableField<SalesOrdersRecord, LocalDateTime> PICKUP_TIME = createField(DSL.name("pickup_time"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.sales_orders.dropoff_location_id</code>.
     * References sub_locations.id (Optional)
     */
    public final TableField<SalesOrdersRecord, Long> DROPOFF_LOCATION_ID = createField(DSL.name("dropoff_location_id"), SQLDataType.BIGINT, this, "References sub_locations.id (Optional)");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.sales_orders.dropoff_address</code>.
     */
    public final TableField<SalesOrdersRecord, String> DROPOFF_ADDRESS = createField(DSL.name("dropoff_address"), SQLDataType.VARCHAR(500), this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.sales_orders.dropoff_latitude</code>.
     */
    public final TableField<SalesOrdersRecord, BigDecimal> DROPOFF_LATITUDE = createField(DSL.name("dropoff_latitude"), SQLDataType.DECIMAL(10, 8), this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.sales_orders.dropoff_longitude</code>.
     */
    public final TableField<SalesOrdersRecord, BigDecimal> DROPOFF_LONGITUDE = createField(DSL.name("dropoff_longitude"), SQLDataType.DECIMAL(11, 8), this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.sales_orders.dropoff_time</code>.
     */
    public final TableField<SalesOrdersRecord, LocalDateTime> DROPOFF_TIME = createField(DSL.name("dropoff_time"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.sales_orders.subtotal_amount</code>.
     */
    public final TableField<SalesOrdersRecord, BigDecimal> SUBTOTAL_AMOUNT = createField(DSL.name("subtotal_amount"), SQLDataType.DECIMAL(17, 4).defaultValue(DSL.inline("0.0000", SQLDataType.DECIMAL)), this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.sales_orders.service_fee</code>.
     */
    public final TableField<SalesOrdersRecord, BigDecimal> SERVICE_FEE = createField(DSL.name("service_fee"), SQLDataType.DECIMAL(17, 4).defaultValue(DSL.inline("0.0000", SQLDataType.DECIMAL)), this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.sales_orders.discount_amount</code>.
     */
    public final TableField<SalesOrdersRecord, BigDecimal> DISCOUNT_AMOUNT = createField(DSL.name("discount_amount"), SQLDataType.DECIMAL(17, 4).nullable(false).defaultValue(DSL.inline("0.0000", SQLDataType.DECIMAL)), this, "");

    /**
     * The column <code>1137_VET_Car_RP_Database.sales_orders.tax_amount</code>.
     */
    public final TableField<SalesOrdersRecord, BigDecimal> TAX_AMOUNT = createField(DSL.name("tax_amount"), SQLDataType.DECIMAL(17, 4).defaultValue(DSL.inline("0.0000", SQLDataType.DECIMAL)), this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.sales_orders.total_amount</code>.
     */
    public final TableField<SalesOrdersRecord, BigDecimal> TOTAL_AMOUNT = createField(DSL.name("total_amount"), SQLDataType.DECIMAL(17, 4).defaultValue(DSL.inline("0.0000", SQLDataType.DECIMAL)), this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.sales_orders.deposit_price</code>.
     * Required upfront deposit amount
     */
    public final TableField<SalesOrdersRecord, BigDecimal> DEPOSIT_PRICE = createField(DSL.name("deposit_price"), SQLDataType.DECIMAL(17, 4).defaultValue(DSL.inline("0.0000", SQLDataType.DECIMAL)), this, "Required upfront deposit amount");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.sales_orders.paid_amount</code>. Total
     * amount paid so far
     */
    public final TableField<SalesOrdersRecord, BigDecimal> PAID_AMOUNT = createField(DSL.name("paid_amount"), SQLDataType.DECIMAL(17, 4).defaultValue(DSL.inline("0.0000", SQLDataType.DECIMAL)), this, "Total amount paid so far");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.sales_orders.remaining_amount</code>.
     * Remaining balance amount
     */
    public final TableField<SalesOrdersRecord, BigDecimal> REMAINING_AMOUNT = createField(DSL.name("remaining_amount"), SQLDataType.DECIMAL(17, 4).defaultValue(DSL.inline("0.0000", SQLDataType.DECIMAL)), this, "Remaining balance amount");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.sales_orders.payment_type</code>. 1: Bank
     * Paid, 2: Cash on Hand, 3: KHQR, 4: Deposit
     */
    public final TableField<SalesOrdersRecord, Byte> PAYMENT_TYPE = createField(DSL.name("payment_type"), SQLDataType.TINYINT.defaultValue(DSL.inline("1", SQLDataType.TINYINT)), this, "1: Bank Paid, 2: Cash on Hand, 3: KHQR, 4: Deposit");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.sales_orders.payment_status</code>. 1:
     * Booking, 2: Deposit, 3: Paid, 4: Expired / Cancelled
     */
    public final TableField<SalesOrdersRecord, Byte> PAYMENT_STATUS = createField(DSL.name("payment_status"), SQLDataType.TINYINT.defaultValue(DSL.inline("1", SQLDataType.TINYINT)), this, "1: Booking, 2: Deposit, 3: Paid, 4: Expired / Cancelled");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.sales_orders.payment_method</code>. 1: ABA
     * KHQR, 2: Credit/Debit Card, 3: ACLEDA, 4: Wing Bank, 5: Chip Mong, 6:
     * Canadia, 7: Sathapana, 8: Cash
     */
    public final TableField<SalesOrdersRecord, Byte> PAYMENT_METHOD = createField(DSL.name("payment_method"), SQLDataType.TINYINT.defaultValue(DSL.inline("1", SQLDataType.TINYINT)), this, "1: ABA KHQR, 2: Credit/Debit Card, 3: ACLEDA, 4: Wing Bank, 5: Chip Mong, 6: Canadia, 7: Sathapana, 8: Cash");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.sales_orders.transaction_id</code>.
     */
    public final TableField<SalesOrdersRecord, String> TRANSACTION_ID = createField(DSL.name("transaction_id"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>1137_VET_Car_RP_Database.sales_orders.currency</code>.
     */
    public final TableField<SalesOrdersRecord, String> CURRENCY = createField(DSL.name("currency"), SQLDataType.VARCHAR(10).defaultValue(DSL.inline("USD", SQLDataType.VARCHAR)), this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.sales_orders.receipt_file_name</code>.
     */
    public final TableField<SalesOrdersRecord, String> RECEIPT_FILE_NAME = createField(DSL.name("receipt_file_name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.sales_orders.receipt_file_url</code>.
     */
    public final TableField<SalesOrdersRecord, String> RECEIPT_FILE_URL = createField(DSL.name("receipt_file_url"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.sales_orders.receipt_description</code>.
     * Bank Reference / APV description and payment notes
     */
    public final TableField<SalesOrdersRecord, String> RECEIPT_DESCRIPTION = createField(DSL.name("receipt_description"), SQLDataType.CLOB, this, "Bank Reference / APV description and payment notes");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.sales_orders.order_status</code>. 1: To
     * Do, 2: In Progress, 3: Complete, 4: Void
     */
    public final TableField<SalesOrdersRecord, Byte> ORDER_STATUS = createField(DSL.name("order_status"), SQLDataType.TINYINT.defaultValue(DSL.inline("1", SQLDataType.TINYINT)), this, "1: To Do, 2: In Progress, 3: Complete, 4: Void");

    /**
     * The column <code>1137_VET_Car_RP_Database.sales_orders.created</code>.
     */
    public final TableField<SalesOrdersRecord, LocalDateTime> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>1137_VET_Car_RP_Database.sales_orders.created_by</code>.
     */
    public final TableField<SalesOrdersRecord, Long> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>1137_VET_Car_RP_Database.sales_orders.modified</code>.
     */
    public final TableField<SalesOrdersRecord, LocalDateTime> MODIFIED = createField(DSL.name("modified"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.sales_orders.modified_by</code>.
     */
    public final TableField<SalesOrdersRecord, Long> MODIFIED_BY = createField(DSL.name("modified_by"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>1137_VET_Car_RP_Database.sales_orders.is_active</code>.
     * 0: Inactive, 1: Active
     */
    public final TableField<SalesOrdersRecord, Byte> IS_ACTIVE = createField(DSL.name("is_active"), SQLDataType.TINYINT.defaultValue(DSL.inline("1", SQLDataType.TINYINT)), this, "0: Inactive, 1: Active");

    private SalesOrders(Name alias, Table<SalesOrdersRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private SalesOrders(Name alias, Table<SalesOrdersRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>1137_VET_Car_RP_Database.sales_orders</code>
     * table reference
     */
    public SalesOrders(String alias) {
        this(DSL.name(alias), SALES_ORDERS);
    }

    /**
     * Create an aliased <code>1137_VET_Car_RP_Database.sales_orders</code>
     * table reference
     */
    public SalesOrders(Name alias) {
        this(alias, SALES_ORDERS);
    }

    /**
     * Create a <code>1137_VET_Car_RP_Database.sales_orders</code> table
     * reference
     */
    public SalesOrders() {
        this(DSL.name("sales_orders"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : _1137VetCarRpDatabase._1137_VET_CAR_RP_DATABASE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.SALES_ORDERS_IDX_ORDERS_CUSTOMER, Indexes.SALES_ORDERS_IDX_ORDERS_STATUS, Indexes.SALES_ORDERS_IDX_ORDERS_VEHICLE);
    }

    @Override
    public Identity<SalesOrdersRecord, Long> getIdentity() {
        return (Identity<SalesOrdersRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<SalesOrdersRecord> getPrimaryKey() {
        return Keys.KEY_SALES_ORDERS_PRIMARY;
    }

    @Override
    public List<UniqueKey<SalesOrdersRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_SALES_ORDERS_ORDER_NO_UNIQUE);
    }

    @Override
    public SalesOrders as(String alias) {
        return new SalesOrders(DSL.name(alias), this);
    }

    @Override
    public SalesOrders as(Name alias) {
        return new SalesOrders(alias, this);
    }

    @Override
    public SalesOrders as(Table<?> alias) {
        return new SalesOrders(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SalesOrders rename(String name) {
        return new SalesOrders(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SalesOrders rename(Name name) {
        return new SalesOrders(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SalesOrders rename(Table<?> name) {
        return new SalesOrders(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SalesOrders where(Condition condition) {
        return new SalesOrders(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SalesOrders where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SalesOrders where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SalesOrders where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SalesOrders where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SalesOrders where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SalesOrders where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SalesOrders where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SalesOrders whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SalesOrders whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
