/*
 * This file is generated by jOOQ.
 */
package com.db_access.jooq.tables;


import com.db_access.jooq.Indexes;
import com.db_access.jooq.Keys;
import com.db_access.jooq._1137VetCarRpDatabase;
import com.db_access.jooq.tables.records.UsersApiRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersApi extends TableImpl<UsersApiRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>1137_VET_Car_RP_Database.users_api</code>
     */
    public static final UsersApi USERS_API = new UsersApi();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UsersApiRecord> getRecordType() {
        return UsersApiRecord.class;
    }

    /**
     * The column <code>1137_VET_Car_RP_Database.users_api.id</code>.
     */
    public final TableField<UsersApiRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.users_api.is_super_admin</code>. 0: false,
     * 1: true
     */
    public final TableField<UsersApiRecord, Byte> IS_SUPER_ADMIN = createField(DSL.name("is_super_admin"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.TINYINT)), this, "0: false, 1: true");

    /**
     * The column <code>1137_VET_Car_RP_Database.users_api.first_name</code>.
     */
    public final TableField<UsersApiRecord, String> FIRST_NAME = createField(DSL.name("first_name"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>1137_VET_Car_RP_Database.users_api.last_name</code>.
     */
    public final TableField<UsersApiRecord, String> LAST_NAME = createField(DSL.name("last_name"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>1137_VET_Car_RP_Database.users_api.full_name</code>.
     */
    public final TableField<UsersApiRecord, String> FULL_NAME = createField(DSL.name("full_name"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>1137_VET_Car_RP_Database.users_api.username</code>.
     */
    public final TableField<UsersApiRecord, String> USERNAME = createField(DSL.name("username"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>1137_VET_Car_RP_Database.users_api.password</code>.
     */
    public final TableField<UsersApiRecord, String> PASSWORD = createField(DSL.name("password"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>1137_VET_Car_RP_Database.users_api.photo</code>.
     */
    public final TableField<UsersApiRecord, String> PHOTO = createField(DSL.name("photo"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>1137_VET_Car_RP_Database.users_api.signature</code>.
     */
    public final TableField<UsersApiRecord, String> SIGNATURE = createField(DSL.name("signature"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.users_api.phone_verify_token</code>.
     */
    public final TableField<UsersApiRecord, String> PHONE_VERIFY_TOKEN = createField(DSL.name("phone_verify_token"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>1137_VET_Car_RP_Database.users_api.session_id</code>.
     */
    public final TableField<UsersApiRecord, String> SESSION_ID = createField(DSL.name("session_id"), SQLDataType.VARCHAR(150), this, "");

    /**
     * The column <code>1137_VET_Car_RP_Database.users_api.session_start</code>.
     */
    public final TableField<UsersApiRecord, LocalDateTime> SESSION_START = createField(DSL.name("session_start"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.users_api.session_active</code>.
     */
    public final TableField<UsersApiRecord, LocalDateTime> SESSION_ACTIVE = createField(DSL.name("session_active"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>1137_VET_Car_RP_Database.users_api.session_lat</code>.
     */
    public final TableField<UsersApiRecord, String> SESSION_LAT = createField(DSL.name("session_lat"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>1137_VET_Car_RP_Database.users_api.session_long</code>.
     */
    public final TableField<UsersApiRecord, String> SESSION_LONG = createField(DSL.name("session_long"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.users_api.login_attempt_remote_ip</code>.
     */
    public final TableField<UsersApiRecord, String> LOGIN_ATTEMPT_REMOTE_IP = createField(DSL.name("login_attempt_remote_ip"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.users_api.login_attempt_http_user_agent</code>.
     */
    public final TableField<UsersApiRecord, String> LOGIN_ATTEMPT_HTTP_USER_AGENT = createField(DSL.name("login_attempt_http_user_agent"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>1137_VET_Car_RP_Database.users_api.status_login</code>.
     * 1. never; 2. Ever login
     */
    public final TableField<UsersApiRecord, Byte> STATUS_LOGIN = createField(DSL.name("status_login"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("1", SQLDataType.TINYINT)), this, "1. never; 2. Ever login");

    /**
     * The column <code>1137_VET_Car_RP_Database.users_api.created_by</code>.
     */
    public final TableField<UsersApiRecord, Long> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>1137_VET_Car_RP_Database.users_api.created</code>.
     */
    public final TableField<UsersApiRecord, LocalDateTime> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>1137_VET_Car_RP_Database.users_api.modified</code>.
     */
    public final TableField<UsersApiRecord, LocalDateTime> MODIFIED = createField(DSL.name("modified"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>1137_VET_Car_RP_Database.users_api.modified_by</code>.
     */
    public final TableField<UsersApiRecord, Long> MODIFIED_BY = createField(DSL.name("modified_by"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>1137_VET_Car_RP_Database.users_api.is_active</code>. 1:
     * Pending; 2: Active
     */
    public final TableField<UsersApiRecord, Byte> IS_ACTIVE = createField(DSL.name("is_active"), SQLDataType.TINYINT, this, "1: Pending; 2: Active");

    /**
     * The column <code>1137_VET_Car_RP_Database.users_api.refresh_token</code>.
     */
    public final TableField<UsersApiRecord, String> REFRESH_TOKEN = createField(DSL.name("refresh_token"), SQLDataType.CLOB, this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.users_api.refresh_token_expiration</code>.
     */
    public final TableField<UsersApiRecord, LocalDateTime> REFRESH_TOKEN_EXPIRATION = createField(DSL.name("refresh_token_expiration"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>1137_VET_Car_RP_Database.users_api.device_id</code>.
     */
    public final TableField<UsersApiRecord, String> DEVICE_ID = createField(DSL.name("device_id"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>1137_VET_Car_RP_Database.users_api.device_name</code>.
     */
    public final TableField<UsersApiRecord, String> DEVICE_NAME = createField(DSL.name("device_name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>1137_VET_Car_RP_Database.users_api.push_token</code>.
     */
    public final TableField<UsersApiRecord, String> PUSH_TOKEN = createField(DSL.name("push_token"), SQLDataType.CLOB, this, "");

    private UsersApi(Name alias, Table<UsersApiRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private UsersApi(Name alias, Table<UsersApiRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>1137_VET_Car_RP_Database.users_api</code> table
     * reference
     */
    public UsersApi(String alias) {
        this(DSL.name(alias), USERS_API);
    }

    /**
     * Create an aliased <code>1137_VET_Car_RP_Database.users_api</code> table
     * reference
     */
    public UsersApi(Name alias) {
        this(alias, USERS_API);
    }

    /**
     * Create a <code>1137_VET_Car_RP_Database.users_api</code> table reference
     */
    public UsersApi() {
        this(DSL.name("users_api"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : _1137VetCarRpDatabase._1137_VET_CAR_RP_DATABASE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.USERS_API_CREATED, Indexes.USERS_API_MATCH, Indexes.USERS_API_SEARCHS, Indexes.USERS_API_STATUS);
    }

    @Override
    public Identity<UsersApiRecord, Long> getIdentity() {
        return (Identity<UsersApiRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<UsersApiRecord> getPrimaryKey() {
        return Keys.KEY_USERS_API_PRIMARY;
    }

    @Override
    public UsersApi as(String alias) {
        return new UsersApi(DSL.name(alias), this);
    }

    @Override
    public UsersApi as(Name alias) {
        return new UsersApi(alias, this);
    }

    @Override
    public UsersApi as(Table<?> alias) {
        return new UsersApi(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UsersApi rename(String name) {
        return new UsersApi(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UsersApi rename(Name name) {
        return new UsersApi(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UsersApi rename(Table<?> name) {
        return new UsersApi(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UsersApi where(Condition condition) {
        return new UsersApi(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UsersApi where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UsersApi where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UsersApi where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UsersApi where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UsersApi where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UsersApi where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UsersApi where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UsersApi whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UsersApi whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
