/*
 * This file is generated by jOOQ.
 */
package com.db_access.jooq.tables;


import com.db_access.jooq.Indexes;
import com.db_access.jooq.Keys;
import com.db_access.jooq._1137VetCarRpDatabase;
import com.db_access.jooq.tables.records.VehicleModelsRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VehicleModels extends TableImpl<VehicleModelsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>1137_VET_Car_RP_Database.vehicle_models</code>
     */
    public static final VehicleModels VEHICLE_MODELS = new VehicleModels();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VehicleModelsRecord> getRecordType() {
        return VehicleModelsRecord.class;
    }

    /**
     * The column <code>1137_VET_Car_RP_Database.vehicle_models.id</code>.
     */
    public final TableField<VehicleModelsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>1137_VET_Car_RP_Database.vehicle_models.brand_id</code>.
     * References vehicle_brands.id
     */
    public final TableField<VehicleModelsRecord, Long> BRAND_ID = createField(DSL.name("brand_id"), SQLDataType.BIGINT.nullable(false), this, "References vehicle_brands.id");

    /**
     * The column <code>1137_VET_Car_RP_Database.vehicle_models.name</code>.
     */
    public final TableField<VehicleModelsRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.vehicle_models.description</code>.
     */
    public final TableField<VehicleModelsRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>1137_VET_Car_RP_Database.vehicle_models.created</code>.
     */
    public final TableField<VehicleModelsRecord, LocalDateTime> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.vehicle_models.created_by</code>.
     */
    public final TableField<VehicleModelsRecord, Long> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>1137_VET_Car_RP_Database.vehicle_models.modified</code>.
     */
    public final TableField<VehicleModelsRecord, LocalDateTime> MODIFIED = createField(DSL.name("modified"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.vehicle_models.modified_by</code>.
     */
    public final TableField<VehicleModelsRecord, Long> MODIFIED_BY = createField(DSL.name("modified_by"), SQLDataType.BIGINT, this, "");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.vehicle_models.is_active</code>. 0:
     * Inactive, 1: Active
     */
    public final TableField<VehicleModelsRecord, Byte> IS_ACTIVE = createField(DSL.name("is_active"), SQLDataType.TINYINT.defaultValue(DSL.inline("1", SQLDataType.TINYINT)), this, "0: Inactive, 1: Active");

    private VehicleModels(Name alias, Table<VehicleModelsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private VehicleModels(Name alias, Table<VehicleModelsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>1137_VET_Car_RP_Database.vehicle_models</code>
     * table reference
     */
    public VehicleModels(String alias) {
        this(DSL.name(alias), VEHICLE_MODELS);
    }

    /**
     * Create an aliased <code>1137_VET_Car_RP_Database.vehicle_models</code>
     * table reference
     */
    public VehicleModels(Name alias) {
        this(alias, VEHICLE_MODELS);
    }

    /**
     * Create a <code>1137_VET_Car_RP_Database.vehicle_models</code> table
     * reference
     */
    public VehicleModels() {
        this(DSL.name("vehicle_models"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : _1137VetCarRpDatabase._1137_VET_CAR_RP_DATABASE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.VEHICLE_MODELS_IDX_VEH_MODELS_BRAND, Indexes.VEHICLE_MODELS_IDX_VEH_MODELS_IS_ACTIVE);
    }

    @Override
    public Identity<VehicleModelsRecord, Long> getIdentity() {
        return (Identity<VehicleModelsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<VehicleModelsRecord> getPrimaryKey() {
        return Keys.KEY_VEHICLE_MODELS_PRIMARY;
    }

    @Override
    public VehicleModels as(String alias) {
        return new VehicleModels(DSL.name(alias), this);
    }

    @Override
    public VehicleModels as(Name alias) {
        return new VehicleModels(alias, this);
    }

    @Override
    public VehicleModels as(Table<?> alias) {
        return new VehicleModels(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public VehicleModels rename(String name) {
        return new VehicleModels(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VehicleModels rename(Name name) {
        return new VehicleModels(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public VehicleModels rename(Table<?> name) {
        return new VehicleModels(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VehicleModels where(Condition condition) {
        return new VehicleModels(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VehicleModels where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VehicleModels where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VehicleModels where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VehicleModels where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VehicleModels where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VehicleModels where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VehicleModels where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VehicleModels whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VehicleModels whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
