/*
 * This file is generated by jOOQ.
 */
package com.db_access.jooq.tables;


import com.db_access.jooq.Indexes;
import com.db_access.jooq.Keys;
import com.db_access.jooq._1137VetCarRpDatabase;
import com.db_access.jooq.tables.records.VehicleCategoriesMappingRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VehicleCategoriesMapping extends TableImpl<VehicleCategoriesMappingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>1137_VET_Car_RP_Database.vehicle_categories_mapping</code>
     */
    public static final VehicleCategoriesMapping VEHICLE_CATEGORIES_MAPPING = new VehicleCategoriesMapping();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VehicleCategoriesMappingRecord> getRecordType() {
        return VehicleCategoriesMappingRecord.class;
    }

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.vehicle_categories_mapping.vehicle_id</code>.
     * References vehicles.id
     */
    public final TableField<VehicleCategoriesMappingRecord, Long> VEHICLE_ID = createField(DSL.name("vehicle_id"), SQLDataType.BIGINT.nullable(false), this, "References vehicles.id");

    /**
     * The column
     * <code>1137_VET_Car_RP_Database.vehicle_categories_mapping.category_id</code>.
     * References vehicle_categories.id
     */
    public final TableField<VehicleCategoriesMappingRecord, Long> CATEGORY_ID = createField(DSL.name("category_id"), SQLDataType.BIGINT.nullable(false), this, "References vehicle_categories.id");

    private VehicleCategoriesMapping(Name alias, Table<VehicleCategoriesMappingRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private VehicleCategoriesMapping(Name alias, Table<VehicleCategoriesMappingRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased
     * <code>1137_VET_Car_RP_Database.vehicle_categories_mapping</code> table
     * reference
     */
    public VehicleCategoriesMapping(String alias) {
        this(DSL.name(alias), VEHICLE_CATEGORIES_MAPPING);
    }

    /**
     * Create an aliased
     * <code>1137_VET_Car_RP_Database.vehicle_categories_mapping</code> table
     * reference
     */
    public VehicleCategoriesMapping(Name alias) {
        this(alias, VEHICLE_CATEGORIES_MAPPING);
    }

    /**
     * Create a <code>1137_VET_Car_RP_Database.vehicle_categories_mapping</code>
     * table reference
     */
    public VehicleCategoriesMapping() {
        this(DSL.name("vehicle_categories_mapping"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : _1137VetCarRpDatabase._1137_VET_CAR_RP_DATABASE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.VEHICLE_CATEGORIES_MAPPING_IDX_VCM_CATEGORY);
    }

    @Override
    public UniqueKey<VehicleCategoriesMappingRecord> getPrimaryKey() {
        return Keys.KEY_VEHICLE_CATEGORIES_MAPPING_PRIMARY;
    }

    @Override
    public VehicleCategoriesMapping as(String alias) {
        return new VehicleCategoriesMapping(DSL.name(alias), this);
    }

    @Override
    public VehicleCategoriesMapping as(Name alias) {
        return new VehicleCategoriesMapping(alias, this);
    }

    @Override
    public VehicleCategoriesMapping as(Table<?> alias) {
        return new VehicleCategoriesMapping(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public VehicleCategoriesMapping rename(String name) {
        return new VehicleCategoriesMapping(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VehicleCategoriesMapping rename(Name name) {
        return new VehicleCategoriesMapping(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public VehicleCategoriesMapping rename(Table<?> name) {
        return new VehicleCategoriesMapping(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VehicleCategoriesMapping where(Condition condition) {
        return new VehicleCategoriesMapping(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VehicleCategoriesMapping where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VehicleCategoriesMapping where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VehicleCategoriesMapping where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VehicleCategoriesMapping where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VehicleCategoriesMapping where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VehicleCategoriesMapping where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VehicleCategoriesMapping where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VehicleCategoriesMapping whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VehicleCategoriesMapping whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
