/*
 * This file is generated by jOOQ.
 */
package com.db_access.jooq;


import com.db_access.jooq.tables.AboutUs;
import com.db_access.jooq.tables.CustomerReviewFiles;
import com.db_access.jooq.tables.CustomerReviews;
import com.db_access.jooq.tables.CustomerSupport;
import com.db_access.jooq.tables.Customers;
import com.db_access.jooq.tables.Facilities;
import com.db_access.jooq.tables.JourneyVehiclePrices;
import com.db_access.jooq.tables.Journeys;
import com.db_access.jooq.tables.ModuleTypesApi;
import com.db_access.jooq.tables.ModulesApi;
import com.db_access.jooq.tables.Nationalities;
import com.db_access.jooq.tables.PermissionsApi;
import com.db_access.jooq.tables.PrivacyTerms;
import com.db_access.jooq.tables.Provinces;
import com.db_access.jooq.tables.SalesOrderPaymentHistories;
import com.db_access.jooq.tables.SalesOrderPayments;
import com.db_access.jooq.tables.SalesOrderTripSubLocations;
import com.db_access.jooq.tables.SalesOrderTrips;
import com.db_access.jooq.tables.SalesOrders;
import com.db_access.jooq.tables.SubLocations;
import com.db_access.jooq.tables.SystemActivitiesApi;
import com.db_access.jooq.tables.UserGroupsApi;
import com.db_access.jooq.tables.UsersApi;
import com.db_access.jooq.tables.VehicleBrands;
import com.db_access.jooq.tables.VehicleCategories;
import com.db_access.jooq.tables.VehicleCategoriesMapping;
import com.db_access.jooq.tables.VehicleFacilities;
import com.db_access.jooq.tables.VehicleItems;
import com.db_access.jooq.tables.VehicleModels;
import com.db_access.jooq.tables.VehicleRentalTypes;
import com.db_access.jooq.tables.VehicleRentalTypesMapping;
import com.db_access.jooq.tables.VehicleSlides;
import com.db_access.jooq.tables.Vehicles;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in 1137_VET_Car_RP_Database.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index USERS_API_CREATED = Internal.createIndex(DSL.name("created"), UsersApi.USERS_API, new OrderField[] { UsersApi.USERS_API.CREATED }, false);
    public static final Index MODULES_API_FILTERS = Internal.createIndex(DSL.name("filters"), ModulesApi.MODULES_API, new OrderField[] { ModulesApi.MODULES_API.STATUS, ModulesApi.MODULES_API.TYPE }, false);
    public static final Index MODULE_TYPES_API_FILTERS = Internal.createIndex(DSL.name("filters"), ModuleTypesApi.MODULE_TYPES_API, new OrderField[] { ModuleTypesApi.MODULE_TYPES_API.STATUS }, false);
    public static final Index PERMISSIONS_API_GROUP_ID = Internal.createIndex(DSL.name("group_id"), PermissionsApi.PERMISSIONS_API, new OrderField[] { PermissionsApi.PERMISSIONS_API.GROUP_ID }, false);
    public static final Index USER_GROUPS_API_GROUP_ID = Internal.createIndex(DSL.name("group_id"), UserGroupsApi.USER_GROUPS_API, new OrderField[] { UserGroupsApi.USER_GROUPS_API.GROUP_ID }, false);
    public static final Index ABOUT_US_IDX_ABOUT_IS_ACTIVE = Internal.createIndex(DSL.name("idx_about_is_active"), AboutUs.ABOUT_US, new OrderField[] { AboutUs.ABOUT_US.IS_ACTIVE }, false);
    public static final Index CUSTOMER_SUPPORT_IDX_CONTACTS_IS_ACTIVE = Internal.createIndex(DSL.name("idx_contacts_is_active"), CustomerSupport.CUSTOMER_SUPPORT, new OrderField[] { CustomerSupport.CUSTOMER_SUPPORT.IS_ACTIVE }, false);
    public static final Index CUSTOMER_SUPPORT_IDX_CONTACTS_SORT_ORDER = Internal.createIndex(DSL.name("idx_contacts_sort_order"), CustomerSupport.CUSTOMER_SUPPORT, new OrderField[] { CustomerSupport.CUSTOMER_SUPPORT.SORT_ORDER }, false);
    public static final Index CUSTOMER_SUPPORT_IDX_CONTACTS_TYPE = Internal.createIndex(DSL.name("idx_contacts_type"), CustomerSupport.CUSTOMER_SUPPORT, new OrderField[] { CustomerSupport.CUSTOMER_SUPPORT.CONTACT_TYPE }, false);
    public static final Index CUSTOMERS_IDX_CUSTOMERS_IS_ACTIVE = Internal.createIndex(DSL.name("idx_customers_is_active"), Customers.CUSTOMERS, new OrderField[] { Customers.CUSTOMERS.IS_ACTIVE }, false);
    public static final Index FACILITIES_IDX_FACILITIES_IS_ACTIVE = Internal.createIndex(DSL.name("idx_facilities_is_active"), Facilities.FACILITIES, new OrderField[] { Facilities.FACILITIES.IS_ACTIVE }, false);
    public static final Index FACILITIES_IDX_FACILITIES_SORT_ORDER = Internal.createIndex(DSL.name("idx_facilities_sort_order"), Facilities.FACILITIES, new OrderField[] { Facilities.FACILITIES.SORT_ORDER }, false);
    public static final Index JOURNEYS_IDX_JOURNEYS_FROM_TO = Internal.createIndex(DSL.name("idx_journeys_from_to"), Journeys.JOURNEYS, new OrderField[] { Journeys.JOURNEYS.FROM_PROVINCE_ID, Journeys.JOURNEYS.TO_PROVINCE_ID }, false);
    public static final Index JOURNEYS_IDX_JOURNEYS_IS_ACTIVE = Internal.createIndex(DSL.name("idx_journeys_is_active"), Journeys.JOURNEYS, new OrderField[] { Journeys.JOURNEYS.IS_ACTIVE }, false);
    public static final Index JOURNEY_VEHICLE_PRICES_IDX_JVP_IS_ACTIVE = Internal.createIndex(DSL.name("idx_jvp_is_active"), JourneyVehiclePrices.JOURNEY_VEHICLE_PRICES, new OrderField[] { JourneyVehiclePrices.JOURNEY_VEHICLE_PRICES.IS_ACTIVE }, false);
    public static final Index JOURNEY_VEHICLE_PRICES_IDX_JVP_JOURNEY = Internal.createIndex(DSL.name("idx_jvp_journey"), JourneyVehiclePrices.JOURNEY_VEHICLE_PRICES, new OrderField[] { JourneyVehiclePrices.JOURNEY_VEHICLE_PRICES.JOURNEY_ID }, false);
    public static final Index JOURNEY_VEHICLE_PRICES_IDX_JVP_VEHICLE_MODEL = Internal.createIndex(DSL.name("idx_jvp_vehicle_model"), JourneyVehiclePrices.JOURNEY_VEHICLE_PRICES, new OrderField[] { JourneyVehiclePrices.JOURNEY_VEHICLE_PRICES.VEHICLE_MODEL_ID }, false);
    public static final Index NATIONALITIES_IDX_NATIONALITIES_IS_ACTIVE = Internal.createIndex(DSL.name("idx_nationalities_is_active"), Nationalities.NATIONALITIES, new OrderField[] { Nationalities.NATIONALITIES.IS_ACTIVE }, false);
    public static final Index SALES_ORDERS_IDX_ORDERS_CUSTOMER = Internal.createIndex(DSL.name("idx_orders_customer"), SalesOrders.SALES_ORDERS, new OrderField[] { SalesOrders.SALES_ORDERS.CUSTOMER_ID }, false);
    public static final Index SALES_ORDERS_IDX_ORDERS_STATUS = Internal.createIndex(DSL.name("idx_orders_status"), SalesOrders.SALES_ORDERS, new OrderField[] { SalesOrders.SALES_ORDERS.ORDER_STATUS, SalesOrders.SALES_ORDERS.PAYMENT_STATUS }, false);
    public static final Index SALES_ORDERS_IDX_ORDERS_VEHICLE = Internal.createIndex(DSL.name("idx_orders_vehicle"), SalesOrders.SALES_ORDERS, new OrderField[] { SalesOrders.SALES_ORDERS.VEHICLE_ID }, false);
    public static final Index PRIVACY_TERMS_IDX_PRIVACY_TERMS_IS_ACTIVE = Internal.createIndex(DSL.name("idx_privacy_terms_is_active"), PrivacyTerms.PRIVACY_TERMS, new OrderField[] { PrivacyTerms.PRIVACY_TERMS.IS_ACTIVE }, false);
    public static final Index PRIVACY_TERMS_IDX_PRIVACY_TERMS_TYPE = Internal.createIndex(DSL.name("idx_privacy_terms_type"), PrivacyTerms.PRIVACY_TERMS, new OrderField[] { PrivacyTerms.PRIVACY_TERMS.TYPE }, false);
    public static final Index PROVINCES_IDX_PROVINCES_IS_ACTIVE = Internal.createIndex(DSL.name("idx_provinces_is_active"), Provinces.PROVINCES, new OrderField[] { Provinces.PROVINCES.IS_ACTIVE }, false);
    public static final Index VEHICLE_RENTAL_TYPES_IDX_RENTAL_TYPES_CATEGORY = Internal.createIndex(DSL.name("idx_rental_types_category"), VehicleRentalTypes.VEHICLE_RENTAL_TYPES, new OrderField[] { VehicleRentalTypes.VEHICLE_RENTAL_TYPES.CATEGORY_ID }, false);
    public static final Index VEHICLE_RENTAL_TYPES_IDX_RENTAL_TYPES_IS_ACTIVE = Internal.createIndex(DSL.name("idx_rental_types_is_active"), VehicleRentalTypes.VEHICLE_RENTAL_TYPES, new OrderField[] { VehicleRentalTypes.VEHICLE_RENTAL_TYPES.IS_ACTIVE }, false);
    public static final Index CUSTOMER_REVIEW_FILES_IDX_REVIEW_FILES_REVIEW = Internal.createIndex(DSL.name("idx_review_files_review"), CustomerReviewFiles.CUSTOMER_REVIEW_FILES, new OrderField[] { CustomerReviewFiles.CUSTOMER_REVIEW_FILES.REVIEW_ID }, false);
    public static final Index CUSTOMER_REVIEWS_IDX_REVIEWS_CUSTOMER = Internal.createIndex(DSL.name("idx_reviews_customer"), CustomerReviews.CUSTOMER_REVIEWS, new OrderField[] { CustomerReviews.CUSTOMER_REVIEWS.CUSTOMER_ID }, false);
    public static final Index CUSTOMER_REVIEWS_IDX_REVIEWS_IS_ACTIVE = Internal.createIndex(DSL.name("idx_reviews_is_active"), CustomerReviews.CUSTOMER_REVIEWS, new OrderField[] { CustomerReviews.CUSTOMER_REVIEWS.IS_ACTIVE }, false);
    public static final Index CUSTOMER_REVIEWS_IDX_REVIEWS_IS_DISABLED = Internal.createIndex(DSL.name("idx_reviews_is_disabled"), CustomerReviews.CUSTOMER_REVIEWS, new OrderField[] { CustomerReviews.CUSTOMER_REVIEWS.IS_DISABLED }, false);
    public static final Index CUSTOMER_REVIEWS_IDX_REVIEWS_VEHICLE = Internal.createIndex(DSL.name("idx_reviews_vehicle"), CustomerReviews.CUSTOMER_REVIEWS, new OrderField[] { CustomerReviews.CUSTOMER_REVIEWS.VEHICLE_ID }, false);
    public static final Index SALES_ORDER_TRIP_SUB_LOCATIONS_IDX_SO_TRIP_SUB_IS_ACTIVE = Internal.createIndex(DSL.name("idx_so_trip_sub_is_active"), SalesOrderTripSubLocations.SALES_ORDER_TRIP_SUB_LOCATIONS, new OrderField[] { SalesOrderTripSubLocations.SALES_ORDER_TRIP_SUB_LOCATIONS.IS_ACTIVE }, false);
    public static final Index SALES_ORDER_TRIP_SUB_LOCATIONS_IDX_SO_TRIP_SUB_TRIP = Internal.createIndex(DSL.name("idx_so_trip_sub_trip"), SalesOrderTripSubLocations.SALES_ORDER_TRIP_SUB_LOCATIONS, new OrderField[] { SalesOrderTripSubLocations.SALES_ORDER_TRIP_SUB_LOCATIONS.TRIP_ID }, false);
    public static final Index SALES_ORDER_TRIPS_IDX_SO_TRIPS_IS_ACTIVE = Internal.createIndex(DSL.name("idx_so_trips_is_active"), SalesOrderTrips.SALES_ORDER_TRIPS, new OrderField[] { SalesOrderTrips.SALES_ORDER_TRIPS.IS_ACTIVE }, false);
    public static final Index SALES_ORDER_TRIPS_IDX_SO_TRIPS_ORDER = Internal.createIndex(DSL.name("idx_so_trips_order"), SalesOrderTrips.SALES_ORDER_TRIPS, new OrderField[] { SalesOrderTrips.SALES_ORDER_TRIPS.SALES_ORDER_ID }, false);
    public static final Index SALES_ORDER_PAYMENT_HISTORIES_IDX_SOPH_SALES_ORDER = Internal.createIndex(DSL.name("idx_soph_sales_order"), SalesOrderPaymentHistories.SALES_ORDER_PAYMENT_HISTORIES, new OrderField[] { SalesOrderPaymentHistories.SALES_ORDER_PAYMENT_HISTORIES.SALES_ORDER_ID }, false);
    public static final Index SUB_LOCATIONS_IDX_SUB_LOC_IS_ACTIVE = Internal.createIndex(DSL.name("idx_sub_loc_is_active"), SubLocations.SUB_LOCATIONS, new OrderField[] { SubLocations.SUB_LOCATIONS.IS_ACTIVE }, false);
    public static final Index SUB_LOCATIONS_IDX_SUB_LOC_PROVINCE = Internal.createIndex(DSL.name("idx_sub_loc_province"), SubLocations.SUB_LOCATIONS, new OrderField[] { SubLocations.SUB_LOCATIONS.PROVINCE_ID }, false);
    public static final Index VEHICLE_CATEGORIES_MAPPING_IDX_VCM_CATEGORY = Internal.createIndex(DSL.name("idx_vcm_category"), VehicleCategoriesMapping.VEHICLE_CATEGORIES_MAPPING, new OrderField[] { VehicleCategoriesMapping.VEHICLE_CATEGORIES_MAPPING.CATEGORY_ID }, false);
    public static final Index VEHICLE_BRANDS_IDX_VEH_BRANDS_IS_ACTIVE = Internal.createIndex(DSL.name("idx_veh_brands_is_active"), VehicleBrands.VEHICLE_BRANDS, new OrderField[] { VehicleBrands.VEHICLE_BRANDS.IS_ACTIVE }, false);
    public static final Index VEHICLE_BRANDS_IDX_VEH_BRANDS_SORT_ORDER = Internal.createIndex(DSL.name("idx_veh_brands_sort_order"), VehicleBrands.VEHICLE_BRANDS, new OrderField[] { VehicleBrands.VEHICLE_BRANDS.SORT_ORDER }, false);
    public static final Index VEHICLE_CATEGORIES_IDX_VEH_CATS_IS_ACTIVE = Internal.createIndex(DSL.name("idx_veh_cats_is_active"), VehicleCategories.VEHICLE_CATEGORIES, new OrderField[] { VehicleCategories.VEHICLE_CATEGORIES.IS_ACTIVE }, false);
    public static final Index VEHICLE_CATEGORIES_IDX_VEH_CATS_SORT_ORDER = Internal.createIndex(DSL.name("idx_veh_cats_sort_order"), VehicleCategories.VEHICLE_CATEGORIES, new OrderField[] { VehicleCategories.VEHICLE_CATEGORIES.SORT_ORDER }, false);
    public static final Index VEHICLE_MODELS_IDX_VEH_MODELS_BRAND = Internal.createIndex(DSL.name("idx_veh_models_brand"), VehicleModels.VEHICLE_MODELS, new OrderField[] { VehicleModels.VEHICLE_MODELS.BRAND_ID }, false);
    public static final Index VEHICLE_MODELS_IDX_VEH_MODELS_IS_ACTIVE = Internal.createIndex(DSL.name("idx_veh_models_is_active"), VehicleModels.VEHICLE_MODELS, new OrderField[] { VehicleModels.VEHICLE_MODELS.IS_ACTIVE }, false);
    public static final Index VEHICLES_IDX_VEHICLES_BRAND = Internal.createIndex(DSL.name("idx_vehicles_brand"), Vehicles.VEHICLES, new OrderField[] { Vehicles.VEHICLES.BRAND_ID }, false);
    public static final Index VEHICLES_IDX_VEHICLES_IS_ACTIVE = Internal.createIndex(DSL.name("idx_vehicles_is_active"), Vehicles.VEHICLES, new OrderField[] { Vehicles.VEHICLES.IS_ACTIVE }, false);
    public static final Index VEHICLES_IDX_VEHICLES_IS_PUBLIC = Internal.createIndex(DSL.name("idx_vehicles_is_public"), Vehicles.VEHICLES, new OrderField[] { Vehicles.VEHICLES.IS_PUBLIC }, false);
    public static final Index VEHICLES_IDX_VEHICLES_MODEL = Internal.createIndex(DSL.name("idx_vehicles_model"), Vehicles.VEHICLES, new OrderField[] { Vehicles.VEHICLES.MODEL_ID }, false);
    public static final Index VEHICLE_FACILITIES_IDX_VFAC_FACILITY = Internal.createIndex(DSL.name("idx_vfac_facility"), VehicleFacilities.VEHICLE_FACILITIES, new OrderField[] { VehicleFacilities.VEHICLE_FACILITIES.FACILITY_ID }, false);
    public static final Index VEHICLE_FACILITIES_IDX_VFAC_VEHICLE = Internal.createIndex(DSL.name("idx_vfac_vehicle"), VehicleFacilities.VEHICLE_FACILITIES, new OrderField[] { VehicleFacilities.VEHICLE_FACILITIES.VEHICLE_ID }, false);
    public static final Index VEHICLE_ITEMS_IDX_VITEMS_IS_ACTIVE = Internal.createIndex(DSL.name("idx_vitems_is_active"), VehicleItems.VEHICLE_ITEMS, new OrderField[] { VehicleItems.VEHICLE_ITEMS.IS_ACTIVE }, false);
    public static final Index VEHICLE_ITEMS_IDX_VITEMS_VEHICLE = Internal.createIndex(DSL.name("idx_vitems_vehicle"), VehicleItems.VEHICLE_ITEMS, new OrderField[] { VehicleItems.VEHICLE_ITEMS.VEHICLE_ID }, false);
    public static final Index VEHICLE_RENTAL_TYPES_MAPPING_IDX_VRTM_RENTAL_TYPE = Internal.createIndex(DSL.name("idx_vrtm_rental_type"), VehicleRentalTypesMapping.VEHICLE_RENTAL_TYPES_MAPPING, new OrderField[] { VehicleRentalTypesMapping.VEHICLE_RENTAL_TYPES_MAPPING.RENTAL_TYPE_ID }, false);
    public static final Index VEHICLE_SLIDES_IDX_VSLIDES_VEHICLE = Internal.createIndex(DSL.name("idx_vslides_vehicle"), VehicleSlides.VEHICLE_SLIDES, new OrderField[] { VehicleSlides.VEHICLE_SLIDES.VEHICLE_ID }, false);
    public static final Index SYSTEM_ACTIVITIES_API_KEY_SEARCH = Internal.createIndex(DSL.name("key_search"), SystemActivitiesApi.SYSTEM_ACTIVITIES_API, new OrderField[] { SystemActivitiesApi.SYSTEM_ACTIVITIES_API.MODULE, SystemActivitiesApi.SYSTEM_ACTIVITIES_API.ACT }, false);
    public static final Index USERS_API_MATCH = Internal.createIndex(DSL.name("match"), UsersApi.USERS_API, new OrderField[] { UsersApi.USERS_API.USERNAME, UsersApi.USERS_API.PASSWORD }, false);
    public static final Index PERMISSIONS_API_MODULE_ID = Internal.createIndex(DSL.name("module_id"), PermissionsApi.PERMISSIONS_API, new OrderField[] { PermissionsApi.PERMISSIONS_API.MODULE_ID }, false);
    public static final Index MODULES_API_MODULE_TYPE_ID = Internal.createIndex(DSL.name("module_type_id"), ModulesApi.MODULES_API, new OrderField[] { ModulesApi.MODULES_API.MODULE_TYPE_ID }, false);
    public static final Index SALES_ORDER_PAYMENTS_SALES_ORDER_IDX = Internal.createIndex(DSL.name("sales_order_idx"), SalesOrderPayments.SALES_ORDER_PAYMENTS, new OrderField[] { SalesOrderPayments.SALES_ORDER_PAYMENTS.SALES_ORDER_ID }, false);
    public static final Index USERS_API_SEARCHS = Internal.createIndex(DSL.name("searchs"), UsersApi.USERS_API, new OrderField[] { UsersApi.USERS_API.FULL_NAME }, false);
    public static final Index SYSTEM_ACTIVITIES_API_STATUS = Internal.createIndex(DSL.name("status"), SystemActivitiesApi.SYSTEM_ACTIVITIES_API, new OrderField[] { SystemActivitiesApi.SYSTEM_ACTIVITIES_API.STATUS }, false);
    public static final Index USERS_API_STATUS = Internal.createIndex(DSL.name("status"), UsersApi.USERS_API, new OrderField[] { UsersApi.USERS_API.IS_ACTIVE }, false);
    public static final Index SALES_ORDER_PAYMENTS_TRAN_IDX = Internal.createIndex(DSL.name("tran_idx"), SalesOrderPayments.SALES_ORDER_PAYMENTS, new OrderField[] { SalesOrderPayments.SALES_ORDER_PAYMENTS.TRANSACTION_ID }, false);
    public static final Index USER_GROUPS_API_USER_ID = Internal.createIndex(DSL.name("user_id"), UserGroupsApi.USER_GROUPS_API, new OrderField[] { UserGroupsApi.USER_GROUPS_API.USER_ID }, false);
}
