/*
 * This file is generated by jOOQ.
 */
package com.db_access.jooq.tables.pojos;


import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomerReviews implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long customerId;
    private Long salesOrderId;
    private Long vehicleId;
    private BigDecimal ratingStars;
    private String comment;
    private Byte isDisabled;
    private LocalDateTime created;
    private Long createdBy;
    private LocalDateTime modified;
    private Long modifiedBy;
    private Byte isActive;

    public CustomerReviews() {}

    public CustomerReviews(CustomerReviews value) {
        this.id = value.id;
        this.customerId = value.customerId;
        this.salesOrderId = value.salesOrderId;
        this.vehicleId = value.vehicleId;
        this.ratingStars = value.ratingStars;
        this.comment = value.comment;
        this.isDisabled = value.isDisabled;
        this.created = value.created;
        this.createdBy = value.createdBy;
        this.modified = value.modified;
        this.modifiedBy = value.modifiedBy;
        this.isActive = value.isActive;
    }

    public CustomerReviews(
        Long id,
        Long customerId,
        Long salesOrderId,
        Long vehicleId,
        BigDecimal ratingStars,
        String comment,
        Byte isDisabled,
        LocalDateTime created,
        Long createdBy,
        LocalDateTime modified,
        Long modifiedBy,
        Byte isActive
    ) {
        this.id = id;
        this.customerId = customerId;
        this.salesOrderId = salesOrderId;
        this.vehicleId = vehicleId;
        this.ratingStars = ratingStars;
        this.comment = comment;
        this.isDisabled = isDisabled;
        this.created = created;
        this.createdBy = createdBy;
        this.modified = modified;
        this.modifiedBy = modifiedBy;
        this.isActive = isActive;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.customer_reviews.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.customer_reviews.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.customer_reviews.customer_id</code>.
     * References customers.id
     */
    @NotNull
    public Long getCustomerId() {
        return this.customerId;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.customer_reviews.customer_id</code>.
     * References customers.id
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.customer_reviews.sales_order_id</code>.
     * References sales_orders.id
     */
    public Long getSalesOrderId() {
        return this.salesOrderId;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.customer_reviews.sales_order_id</code>.
     * References sales_orders.id
     */
    public void setSalesOrderId(Long salesOrderId) {
        this.salesOrderId = salesOrderId;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.customer_reviews.vehicle_id</code>.
     * References vehicles.id
     */
    @NotNull
    public Long getVehicleId() {
        return this.vehicleId;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.customer_reviews.vehicle_id</code>.
     * References vehicles.id
     */
    public void setVehicleId(Long vehicleId) {
        this.vehicleId = vehicleId;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.customer_reviews.rating_stars</code>.
     */
    public BigDecimal getRatingStars() {
        return this.ratingStars;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.customer_reviews.rating_stars</code>.
     */
    public void setRatingStars(BigDecimal ratingStars) {
        this.ratingStars = ratingStars;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.customer_reviews.comment</code>.
     */
    @Size(max = 65535)
    public String getComment() {
        return this.comment;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.customer_reviews.comment</code>.
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.customer_reviews.is_disabled</code>. 0:
     * Enabled, 1: Disabled to App
     */
    public Byte getIsDisabled() {
        return this.isDisabled;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.customer_reviews.is_disabled</code>. 0:
     * Enabled, 1: Disabled to App
     */
    public void setIsDisabled(Byte isDisabled) {
        this.isDisabled = isDisabled;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.customer_reviews.created</code>.
     */
    @NotNull
    public LocalDateTime getCreated() {
        return this.created;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.customer_reviews.created</code>.
     */
    public void setCreated(LocalDateTime created) {
        this.created = created;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.customer_reviews.created_by</code>.
     */
    public Long getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.customer_reviews.created_by</code>.
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.customer_reviews.modified</code>.
     */
    public LocalDateTime getModified() {
        return this.modified;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.customer_reviews.modified</code>.
     */
    public void setModified(LocalDateTime modified) {
        this.modified = modified;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.customer_reviews.modified_by</code>.
     */
    public Long getModifiedBy() {
        return this.modifiedBy;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.customer_reviews.modified_by</code>.
     */
    public void setModifiedBy(Long modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.customer_reviews.is_active</code>. 0:
     * Inactive, 1: Active
     */
    public Byte getIsActive() {
        return this.isActive;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.customer_reviews.is_active</code>. 0:
     * Inactive, 1: Active
     */
    public void setIsActive(Byte isActive) {
        this.isActive = isActive;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final CustomerReviews other = (CustomerReviews) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.customerId == null) {
            if (other.customerId != null)
                return false;
        }
        else if (!this.customerId.equals(other.customerId))
            return false;
        if (this.salesOrderId == null) {
            if (other.salesOrderId != null)
                return false;
        }
        else if (!this.salesOrderId.equals(other.salesOrderId))
            return false;
        if (this.vehicleId == null) {
            if (other.vehicleId != null)
                return false;
        }
        else if (!this.vehicleId.equals(other.vehicleId))
            return false;
        if (this.ratingStars == null) {
            if (other.ratingStars != null)
                return false;
        }
        else if (!this.ratingStars.equals(other.ratingStars))
            return false;
        if (this.comment == null) {
            if (other.comment != null)
                return false;
        }
        else if (!this.comment.equals(other.comment))
            return false;
        if (this.isDisabled == null) {
            if (other.isDisabled != null)
                return false;
        }
        else if (!this.isDisabled.equals(other.isDisabled))
            return false;
        if (this.created == null) {
            if (other.created != null)
                return false;
        }
        else if (!this.created.equals(other.created))
            return false;
        if (this.createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!this.createdBy.equals(other.createdBy))
            return false;
        if (this.modified == null) {
            if (other.modified != null)
                return false;
        }
        else if (!this.modified.equals(other.modified))
            return false;
        if (this.modifiedBy == null) {
            if (other.modifiedBy != null)
                return false;
        }
        else if (!this.modifiedBy.equals(other.modifiedBy))
            return false;
        if (this.isActive == null) {
            if (other.isActive != null)
                return false;
        }
        else if (!this.isActive.equals(other.isActive))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.customerId == null) ? 0 : this.customerId.hashCode());
        result = prime * result + ((this.salesOrderId == null) ? 0 : this.salesOrderId.hashCode());
        result = prime * result + ((this.vehicleId == null) ? 0 : this.vehicleId.hashCode());
        result = prime * result + ((this.ratingStars == null) ? 0 : this.ratingStars.hashCode());
        result = prime * result + ((this.comment == null) ? 0 : this.comment.hashCode());
        result = prime * result + ((this.isDisabled == null) ? 0 : this.isDisabled.hashCode());
        result = prime * result + ((this.created == null) ? 0 : this.created.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.modified == null) ? 0 : this.modified.hashCode());
        result = prime * result + ((this.modifiedBy == null) ? 0 : this.modifiedBy.hashCode());
        result = prime * result + ((this.isActive == null) ? 0 : this.isActive.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CustomerReviews (");

        sb.append(id);
        sb.append(", ").append(customerId);
        sb.append(", ").append(salesOrderId);
        sb.append(", ").append(vehicleId);
        sb.append(", ").append(ratingStars);
        sb.append(", ").append(comment);
        sb.append(", ").append(isDisabled);
        sb.append(", ").append(created);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(modified);
        sb.append(", ").append(modifiedBy);
        sb.append(", ").append(isActive);

        sb.append(")");
        return sb.toString();
    }
}
