/*
 * This file is generated by jOOQ.
 */
package com.db_access.jooq.tables.pojos;


import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomerReviewFiles implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long reviewId;
    private String fileName;
    private String fileUrl;
    private LocalDateTime created;

    public CustomerReviewFiles() {}

    public CustomerReviewFiles(CustomerReviewFiles value) {
        this.id = value.id;
        this.reviewId = value.reviewId;
        this.fileName = value.fileName;
        this.fileUrl = value.fileUrl;
        this.created = value.created;
    }

    public CustomerReviewFiles(
        Long id,
        Long reviewId,
        String fileName,
        String fileUrl,
        LocalDateTime created
    ) {
        this.id = id;
        this.reviewId = reviewId;
        this.fileName = fileName;
        this.fileUrl = fileUrl;
        this.created = created;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.customer_review_files.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.customer_review_files.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.customer_review_files.review_id</code>.
     * References customer_reviews.id
     */
    @NotNull
    public Long getReviewId() {
        return this.reviewId;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.customer_review_files.review_id</code>.
     * References customer_reviews.id
     */
    public void setReviewId(Long reviewId) {
        this.reviewId = reviewId;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.customer_review_files.file_name</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getFileName() {
        return this.fileName;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.customer_review_files.file_name</code>.
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.customer_review_files.file_url</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getFileUrl() {
        return this.fileUrl;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.customer_review_files.file_url</code>.
     */
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.customer_review_files.created</code>.
     */
    @NotNull
    public LocalDateTime getCreated() {
        return this.created;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.customer_review_files.created</code>.
     */
    public void setCreated(LocalDateTime created) {
        this.created = created;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final CustomerReviewFiles other = (CustomerReviewFiles) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.reviewId == null) {
            if (other.reviewId != null)
                return false;
        }
        else if (!this.reviewId.equals(other.reviewId))
            return false;
        if (this.fileName == null) {
            if (other.fileName != null)
                return false;
        }
        else if (!this.fileName.equals(other.fileName))
            return false;
        if (this.fileUrl == null) {
            if (other.fileUrl != null)
                return false;
        }
        else if (!this.fileUrl.equals(other.fileUrl))
            return false;
        if (this.created == null) {
            if (other.created != null)
                return false;
        }
        else if (!this.created.equals(other.created))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.reviewId == null) ? 0 : this.reviewId.hashCode());
        result = prime * result + ((this.fileName == null) ? 0 : this.fileName.hashCode());
        result = prime * result + ((this.fileUrl == null) ? 0 : this.fileUrl.hashCode());
        result = prime * result + ((this.created == null) ? 0 : this.created.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CustomerReviewFiles (");

        sb.append(id);
        sb.append(", ").append(reviewId);
        sb.append(", ").append(fileName);
        sb.append(", ").append(fileUrl);
        sb.append(", ").append(created);

        sb.append(")");
        return sb.toString();
    }
}
