/*
 * This file is generated by jOOQ.
 */
package com.db_access.jooq.tables.pojos;


import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Customers implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String fullName;
    private String phoneNumber;
    private String email;
    private String password;
    private String fileName;
    private String fileUrl;
    private Byte isVerified;
    private Byte osType;
    private Byte language;
    private String deviceToken;
    private LocalDateTime lastLogin;
    private LocalDateTime created;
    private LocalDateTime modified;
    private Byte isActive;

    public Customers() {}

    public Customers(Customers value) {
        this.id = value.id;
        this.fullName = value.fullName;
        this.phoneNumber = value.phoneNumber;
        this.email = value.email;
        this.password = value.password;
        this.fileName = value.fileName;
        this.fileUrl = value.fileUrl;
        this.isVerified = value.isVerified;
        this.osType = value.osType;
        this.language = value.language;
        this.deviceToken = value.deviceToken;
        this.lastLogin = value.lastLogin;
        this.created = value.created;
        this.modified = value.modified;
        this.isActive = value.isActive;
    }

    public Customers(
        Long id,
        String fullName,
        String phoneNumber,
        String email,
        String password,
        String fileName,
        String fileUrl,
        Byte isVerified,
        Byte osType,
        Byte language,
        String deviceToken,
        LocalDateTime lastLogin,
        LocalDateTime created,
        LocalDateTime modified,
        Byte isActive
    ) {
        this.id = id;
        this.fullName = fullName;
        this.phoneNumber = phoneNumber;
        this.email = email;
        this.password = password;
        this.fileName = fileName;
        this.fileUrl = fileUrl;
        this.isVerified = isVerified;
        this.osType = osType;
        this.language = language;
        this.deviceToken = deviceToken;
        this.lastLogin = lastLogin;
        this.created = created;
        this.modified = modified;
        this.isActive = isActive;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.customers.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.customers.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.customers.full_name</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getFullName() {
        return this.fullName;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.customers.full_name</code>.
     */
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.customers.phone_number</code>.
     */
    @NotNull
    @Size(max = 50)
    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.customers.phone_number</code>.
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.customers.email</code>.
     */
    @Size(max = 255)
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.customers.email</code>.
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.customers.password</code>.
     */
    @Size(max = 255)
    public String getPassword() {
        return this.password;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.customers.password</code>.
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.customers.file_name</code>.
     */
    @Size(max = 255)
    public String getFileName() {
        return this.fileName;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.customers.file_name</code>.
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.customers.file_url</code>.
     */
    @Size(max = 255)
    public String getFileUrl() {
        return this.fileUrl;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.customers.file_url</code>.
     */
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.customers.is_verified</code>.
     * 0: Unverified, 1: Verified (OTP)
     */
    public Byte getIsVerified() {
        return this.isVerified;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.customers.is_verified</code>.
     * 0: Unverified, 1: Verified (OTP)
     */
    public void setIsVerified(Byte isVerified) {
        this.isVerified = isVerified;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.customers.os_type</code>. 1:
     * iOS, 2: Android
     */
    public Byte getOsType() {
        return this.osType;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.customers.os_type</code>. 1:
     * iOS, 2: Android
     */
    public void setOsType(Byte osType) {
        this.osType = osType;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.customers.language</code>. 1:
     * English, 2: Khmer, 3: Chinese
     */
    public Byte getLanguage() {
        return this.language;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.customers.language</code>. 1:
     * English, 2: Khmer, 3: Chinese
     */
    public void setLanguage(Byte language) {
        this.language = language;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.customers.device_token</code>.
     * FCM Push Token
     */
    @Size(max = 65535)
    public String getDeviceToken() {
        return this.deviceToken;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.customers.device_token</code>.
     * FCM Push Token
     */
    public void setDeviceToken(String deviceToken) {
        this.deviceToken = deviceToken;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.customers.last_login</code>.
     */
    public LocalDateTime getLastLogin() {
        return this.lastLogin;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.customers.last_login</code>.
     */
    public void setLastLogin(LocalDateTime lastLogin) {
        this.lastLogin = lastLogin;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.customers.created</code>.
     */
    public LocalDateTime getCreated() {
        return this.created;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.customers.created</code>.
     */
    public void setCreated(LocalDateTime created) {
        this.created = created;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.customers.modified</code>.
     */
    public LocalDateTime getModified() {
        return this.modified;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.customers.modified</code>.
     */
    public void setModified(LocalDateTime modified) {
        this.modified = modified;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.customers.is_active</code>. 1:
     * Active, 2: Blocked/Deleted
     */
    public Byte getIsActive() {
        return this.isActive;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.customers.is_active</code>. 1:
     * Active, 2: Blocked/Deleted
     */
    public void setIsActive(Byte isActive) {
        this.isActive = isActive;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Customers other = (Customers) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.fullName == null) {
            if (other.fullName != null)
                return false;
        }
        else if (!this.fullName.equals(other.fullName))
            return false;
        if (this.phoneNumber == null) {
            if (other.phoneNumber != null)
                return false;
        }
        else if (!this.phoneNumber.equals(other.phoneNumber))
            return false;
        if (this.email == null) {
            if (other.email != null)
                return false;
        }
        else if (!this.email.equals(other.email))
            return false;
        if (this.password == null) {
            if (other.password != null)
                return false;
        }
        else if (!this.password.equals(other.password))
            return false;
        if (this.fileName == null) {
            if (other.fileName != null)
                return false;
        }
        else if (!this.fileName.equals(other.fileName))
            return false;
        if (this.fileUrl == null) {
            if (other.fileUrl != null)
                return false;
        }
        else if (!this.fileUrl.equals(other.fileUrl))
            return false;
        if (this.isVerified == null) {
            if (other.isVerified != null)
                return false;
        }
        else if (!this.isVerified.equals(other.isVerified))
            return false;
        if (this.osType == null) {
            if (other.osType != null)
                return false;
        }
        else if (!this.osType.equals(other.osType))
            return false;
        if (this.language == null) {
            if (other.language != null)
                return false;
        }
        else if (!this.language.equals(other.language))
            return false;
        if (this.deviceToken == null) {
            if (other.deviceToken != null)
                return false;
        }
        else if (!this.deviceToken.equals(other.deviceToken))
            return false;
        if (this.lastLogin == null) {
            if (other.lastLogin != null)
                return false;
        }
        else if (!this.lastLogin.equals(other.lastLogin))
            return false;
        if (this.created == null) {
            if (other.created != null)
                return false;
        }
        else if (!this.created.equals(other.created))
            return false;
        if (this.modified == null) {
            if (other.modified != null)
                return false;
        }
        else if (!this.modified.equals(other.modified))
            return false;
        if (this.isActive == null) {
            if (other.isActive != null)
                return false;
        }
        else if (!this.isActive.equals(other.isActive))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.fullName == null) ? 0 : this.fullName.hashCode());
        result = prime * result + ((this.phoneNumber == null) ? 0 : this.phoneNumber.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        result = prime * result + ((this.password == null) ? 0 : this.password.hashCode());
        result = prime * result + ((this.fileName == null) ? 0 : this.fileName.hashCode());
        result = prime * result + ((this.fileUrl == null) ? 0 : this.fileUrl.hashCode());
        result = prime * result + ((this.isVerified == null) ? 0 : this.isVerified.hashCode());
        result = prime * result + ((this.osType == null) ? 0 : this.osType.hashCode());
        result = prime * result + ((this.language == null) ? 0 : this.language.hashCode());
        result = prime * result + ((this.deviceToken == null) ? 0 : this.deviceToken.hashCode());
        result = prime * result + ((this.lastLogin == null) ? 0 : this.lastLogin.hashCode());
        result = prime * result + ((this.created == null) ? 0 : this.created.hashCode());
        result = prime * result + ((this.modified == null) ? 0 : this.modified.hashCode());
        result = prime * result + ((this.isActive == null) ? 0 : this.isActive.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Customers (");

        sb.append(id);
        sb.append(", ").append(fullName);
        sb.append(", ").append(phoneNumber);
        sb.append(", ").append(email);
        sb.append(", ").append(password);
        sb.append(", ").append(fileName);
        sb.append(", ").append(fileUrl);
        sb.append(", ").append(isVerified);
        sb.append(", ").append(osType);
        sb.append(", ").append(language);
        sb.append(", ").append(deviceToken);
        sb.append(", ").append(lastLogin);
        sb.append(", ").append(created);
        sb.append(", ").append(modified);
        sb.append(", ").append(isActive);

        sb.append(")");
        return sb.toString();
    }
}
