/*
 * This file is generated by jOOQ.
 */
package com.db_access.jooq.tables.pojos;


import jakarta.validation.constraints.NotNull;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JourneyVehiclePrices implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long journeyId;
    private Long vehicleModelId;
    private BigDecimal oneWayPrice;
    private BigDecimal roundTripPrice;
    private BigDecimal oneDayTourPrice;
    private BigDecimal multiCityPrice;
    private BigDecimal cityTourPrice;
    private LocalDateTime created;
    private Long createdBy;
    private LocalDateTime modified;
    private Long modifiedBy;
    private Byte isActive;

    public JourneyVehiclePrices() {}

    public JourneyVehiclePrices(JourneyVehiclePrices value) {
        this.id = value.id;
        this.journeyId = value.journeyId;
        this.vehicleModelId = value.vehicleModelId;
        this.oneWayPrice = value.oneWayPrice;
        this.roundTripPrice = value.roundTripPrice;
        this.oneDayTourPrice = value.oneDayTourPrice;
        this.multiCityPrice = value.multiCityPrice;
        this.cityTourPrice = value.cityTourPrice;
        this.created = value.created;
        this.createdBy = value.createdBy;
        this.modified = value.modified;
        this.modifiedBy = value.modifiedBy;
        this.isActive = value.isActive;
    }

    public JourneyVehiclePrices(
        Long id,
        Long journeyId,
        Long vehicleModelId,
        BigDecimal oneWayPrice,
        BigDecimal roundTripPrice,
        BigDecimal oneDayTourPrice,
        BigDecimal multiCityPrice,
        BigDecimal cityTourPrice,
        LocalDateTime created,
        Long createdBy,
        LocalDateTime modified,
        Long modifiedBy,
        Byte isActive
    ) {
        this.id = id;
        this.journeyId = journeyId;
        this.vehicleModelId = vehicleModelId;
        this.oneWayPrice = oneWayPrice;
        this.roundTripPrice = roundTripPrice;
        this.oneDayTourPrice = oneDayTourPrice;
        this.multiCityPrice = multiCityPrice;
        this.cityTourPrice = cityTourPrice;
        this.created = created;
        this.createdBy = createdBy;
        this.modified = modified;
        this.modifiedBy = modifiedBy;
        this.isActive = isActive;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.journey_vehicle_prices.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.journey_vehicle_prices.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.journey_vehicle_prices.journey_id</code>.
     * References journeys.id
     */
    @NotNull
    public Long getJourneyId() {
        return this.journeyId;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.journey_vehicle_prices.journey_id</code>.
     * References journeys.id
     */
    public void setJourneyId(Long journeyId) {
        this.journeyId = journeyId;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.journey_vehicle_prices.vehicle_model_id</code>.
     * References vehicle_models.id
     */
    @NotNull
    public Long getVehicleModelId() {
        return this.vehicleModelId;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.journey_vehicle_prices.vehicle_model_id</code>.
     * References vehicle_models.id
     */
    public void setVehicleModelId(Long vehicleModelId) {
        this.vehicleModelId = vehicleModelId;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.journey_vehicle_prices.one_way_price</code>.
     */
    public BigDecimal getOneWayPrice() {
        return this.oneWayPrice;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.journey_vehicle_prices.one_way_price</code>.
     */
    public void setOneWayPrice(BigDecimal oneWayPrice) {
        this.oneWayPrice = oneWayPrice;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.journey_vehicle_prices.round_trip_price</code>.
     */
    public BigDecimal getRoundTripPrice() {
        return this.roundTripPrice;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.journey_vehicle_prices.round_trip_price</code>.
     */
    public void setRoundTripPrice(BigDecimal roundTripPrice) {
        this.roundTripPrice = roundTripPrice;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.journey_vehicle_prices.one_day_tour_price</code>.
     */
    public BigDecimal getOneDayTourPrice() {
        return this.oneDayTourPrice;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.journey_vehicle_prices.one_day_tour_price</code>.
     */
    public void setOneDayTourPrice(BigDecimal oneDayTourPrice) {
        this.oneDayTourPrice = oneDayTourPrice;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.journey_vehicle_prices.multi_city_price</code>.
     */
    public BigDecimal getMultiCityPrice() {
        return this.multiCityPrice;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.journey_vehicle_prices.multi_city_price</code>.
     */
    public void setMultiCityPrice(BigDecimal multiCityPrice) {
        this.multiCityPrice = multiCityPrice;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.journey_vehicle_prices.city_tour_price</code>.
     * City Tour Price (journeyType=5)
     */
    public BigDecimal getCityTourPrice() {
        return this.cityTourPrice;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.journey_vehicle_prices.city_tour_price</code>.
     * City Tour Price (journeyType=5)
     */
    public void setCityTourPrice(BigDecimal cityTourPrice) {
        this.cityTourPrice = cityTourPrice;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.journey_vehicle_prices.created</code>.
     */
    @NotNull
    public LocalDateTime getCreated() {
        return this.created;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.journey_vehicle_prices.created</code>.
     */
    public void setCreated(LocalDateTime created) {
        this.created = created;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.journey_vehicle_prices.created_by</code>.
     */
    public Long getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.journey_vehicle_prices.created_by</code>.
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.journey_vehicle_prices.modified</code>.
     */
    public LocalDateTime getModified() {
        return this.modified;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.journey_vehicle_prices.modified</code>.
     */
    public void setModified(LocalDateTime modified) {
        this.modified = modified;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.journey_vehicle_prices.modified_by</code>.
     */
    public Long getModifiedBy() {
        return this.modifiedBy;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.journey_vehicle_prices.modified_by</code>.
     */
    public void setModifiedBy(Long modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.journey_vehicle_prices.is_active</code>.
     * 0: Inactive, 1: Active
     */
    public Byte getIsActive() {
        return this.isActive;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.journey_vehicle_prices.is_active</code>.
     * 0: Inactive, 1: Active
     */
    public void setIsActive(Byte isActive) {
        this.isActive = isActive;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final JourneyVehiclePrices other = (JourneyVehiclePrices) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.journeyId == null) {
            if (other.journeyId != null)
                return false;
        }
        else if (!this.journeyId.equals(other.journeyId))
            return false;
        if (this.vehicleModelId == null) {
            if (other.vehicleModelId != null)
                return false;
        }
        else if (!this.vehicleModelId.equals(other.vehicleModelId))
            return false;
        if (this.oneWayPrice == null) {
            if (other.oneWayPrice != null)
                return false;
        }
        else if (!this.oneWayPrice.equals(other.oneWayPrice))
            return false;
        if (this.roundTripPrice == null) {
            if (other.roundTripPrice != null)
                return false;
        }
        else if (!this.roundTripPrice.equals(other.roundTripPrice))
            return false;
        if (this.oneDayTourPrice == null) {
            if (other.oneDayTourPrice != null)
                return false;
        }
        else if (!this.oneDayTourPrice.equals(other.oneDayTourPrice))
            return false;
        if (this.multiCityPrice == null) {
            if (other.multiCityPrice != null)
                return false;
        }
        else if (!this.multiCityPrice.equals(other.multiCityPrice))
            return false;
        if (this.cityTourPrice == null) {
            if (other.cityTourPrice != null)
                return false;
        }
        else if (!this.cityTourPrice.equals(other.cityTourPrice))
            return false;
        if (this.created == null) {
            if (other.created != null)
                return false;
        }
        else if (!this.created.equals(other.created))
            return false;
        if (this.createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!this.createdBy.equals(other.createdBy))
            return false;
        if (this.modified == null) {
            if (other.modified != null)
                return false;
        }
        else if (!this.modified.equals(other.modified))
            return false;
        if (this.modifiedBy == null) {
            if (other.modifiedBy != null)
                return false;
        }
        else if (!this.modifiedBy.equals(other.modifiedBy))
            return false;
        if (this.isActive == null) {
            if (other.isActive != null)
                return false;
        }
        else if (!this.isActive.equals(other.isActive))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.journeyId == null) ? 0 : this.journeyId.hashCode());
        result = prime * result + ((this.vehicleModelId == null) ? 0 : this.vehicleModelId.hashCode());
        result = prime * result + ((this.oneWayPrice == null) ? 0 : this.oneWayPrice.hashCode());
        result = prime * result + ((this.roundTripPrice == null) ? 0 : this.roundTripPrice.hashCode());
        result = prime * result + ((this.oneDayTourPrice == null) ? 0 : this.oneDayTourPrice.hashCode());
        result = prime * result + ((this.multiCityPrice == null) ? 0 : this.multiCityPrice.hashCode());
        result = prime * result + ((this.cityTourPrice == null) ? 0 : this.cityTourPrice.hashCode());
        result = prime * result + ((this.created == null) ? 0 : this.created.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.modified == null) ? 0 : this.modified.hashCode());
        result = prime * result + ((this.modifiedBy == null) ? 0 : this.modifiedBy.hashCode());
        result = prime * result + ((this.isActive == null) ? 0 : this.isActive.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("JourneyVehiclePrices (");

        sb.append(id);
        sb.append(", ").append(journeyId);
        sb.append(", ").append(vehicleModelId);
        sb.append(", ").append(oneWayPrice);
        sb.append(", ").append(roundTripPrice);
        sb.append(", ").append(oneDayTourPrice);
        sb.append(", ").append(multiCityPrice);
        sb.append(", ").append(cityTourPrice);
        sb.append(", ").append(created);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(modified);
        sb.append(", ").append(modifiedBy);
        sb.append(", ").append(isActive);

        sb.append(")");
        return sb.toString();
    }
}
