/*
 * This file is generated by jOOQ.
 */
package com.db_access.jooq.tables.pojos;


import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Journeys implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long fromProvinceId;
    private Long toProvinceId;
    private String description;
    private LocalDateTime created;
    private Long createdBy;
    private LocalDateTime modified;
    private Long modifiedBy;
    private Byte isActive;

    public Journeys() {}

    public Journeys(Journeys value) {
        this.id = value.id;
        this.fromProvinceId = value.fromProvinceId;
        this.toProvinceId = value.toProvinceId;
        this.description = value.description;
        this.created = value.created;
        this.createdBy = value.createdBy;
        this.modified = value.modified;
        this.modifiedBy = value.modifiedBy;
        this.isActive = value.isActive;
    }

    public Journeys(
        Long id,
        Long fromProvinceId,
        Long toProvinceId,
        String description,
        LocalDateTime created,
        Long createdBy,
        LocalDateTime modified,
        Long modifiedBy,
        Byte isActive
    ) {
        this.id = id;
        this.fromProvinceId = fromProvinceId;
        this.toProvinceId = toProvinceId;
        this.description = description;
        this.created = created;
        this.createdBy = createdBy;
        this.modified = modified;
        this.modifiedBy = modifiedBy;
        this.isActive = isActive;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.journeys.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.journeys.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.journeys.from_province_id</code>.
     * References provinces.id (Source)
     */
    @NotNull
    public Long getFromProvinceId() {
        return this.fromProvinceId;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.journeys.from_province_id</code>.
     * References provinces.id (Source)
     */
    public void setFromProvinceId(Long fromProvinceId) {
        this.fromProvinceId = fromProvinceId;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.journeys.to_province_id</code>.
     * References provinces.id (Destination)
     */
    @NotNull
    public Long getToProvinceId() {
        return this.toProvinceId;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.journeys.to_province_id</code>.
     * References provinces.id (Destination)
     */
    public void setToProvinceId(Long toProvinceId) {
        this.toProvinceId = toProvinceId;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.journeys.description</code>.
     */
    @Size(max = 65535)
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.journeys.description</code>.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.journeys.created</code>.
     */
    @NotNull
    public LocalDateTime getCreated() {
        return this.created;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.journeys.created</code>.
     */
    public void setCreated(LocalDateTime created) {
        this.created = created;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.journeys.created_by</code>.
     */
    public Long getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.journeys.created_by</code>.
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.journeys.modified</code>.
     */
    public LocalDateTime getModified() {
        return this.modified;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.journeys.modified</code>.
     */
    public void setModified(LocalDateTime modified) {
        this.modified = modified;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.journeys.modified_by</code>.
     */
    public Long getModifiedBy() {
        return this.modifiedBy;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.journeys.modified_by</code>.
     */
    public void setModifiedBy(Long modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.journeys.is_active</code>. 0:
     * Inactive, 1: Active
     */
    public Byte getIsActive() {
        return this.isActive;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.journeys.is_active</code>. 0:
     * Inactive, 1: Active
     */
    public void setIsActive(Byte isActive) {
        this.isActive = isActive;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Journeys other = (Journeys) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.fromProvinceId == null) {
            if (other.fromProvinceId != null)
                return false;
        }
        else if (!this.fromProvinceId.equals(other.fromProvinceId))
            return false;
        if (this.toProvinceId == null) {
            if (other.toProvinceId != null)
                return false;
        }
        else if (!this.toProvinceId.equals(other.toProvinceId))
            return false;
        if (this.description == null) {
            if (other.description != null)
                return false;
        }
        else if (!this.description.equals(other.description))
            return false;
        if (this.created == null) {
            if (other.created != null)
                return false;
        }
        else if (!this.created.equals(other.created))
            return false;
        if (this.createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!this.createdBy.equals(other.createdBy))
            return false;
        if (this.modified == null) {
            if (other.modified != null)
                return false;
        }
        else if (!this.modified.equals(other.modified))
            return false;
        if (this.modifiedBy == null) {
            if (other.modifiedBy != null)
                return false;
        }
        else if (!this.modifiedBy.equals(other.modifiedBy))
            return false;
        if (this.isActive == null) {
            if (other.isActive != null)
                return false;
        }
        else if (!this.isActive.equals(other.isActive))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.fromProvinceId == null) ? 0 : this.fromProvinceId.hashCode());
        result = prime * result + ((this.toProvinceId == null) ? 0 : this.toProvinceId.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.created == null) ? 0 : this.created.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.modified == null) ? 0 : this.modified.hashCode());
        result = prime * result + ((this.modifiedBy == null) ? 0 : this.modifiedBy.hashCode());
        result = prime * result + ((this.isActive == null) ? 0 : this.isActive.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Journeys (");

        sb.append(id);
        sb.append(", ").append(fromProvinceId);
        sb.append(", ").append(toProvinceId);
        sb.append(", ").append(description);
        sb.append(", ").append(created);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(modified);
        sb.append(", ").append(modifiedBy);
        sb.append(", ").append(isActive);

        sb.append(")");
        return sb.toString();
    }
}
