/*
 * This file is generated by jOOQ.
 */
package com.db_access.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PermissionsApi implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long groupId;
    private Long moduleId;

    public PermissionsApi() {}

    public PermissionsApi(PermissionsApi value) {
        this.id = value.id;
        this.groupId = value.groupId;
        this.moduleId = value.moduleId;
    }

    public PermissionsApi(
        Long id,
        Long groupId,
        Long moduleId
    ) {
        this.id = id;
        this.groupId = groupId;
        this.moduleId = moduleId;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.permissions_api.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.permissions_api.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.permissions_api.group_id</code>.
     */
    public Long getGroupId() {
        return this.groupId;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.permissions_api.group_id</code>.
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.permissions_api.module_id</code>.
     */
    public Long getModuleId() {
        return this.moduleId;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.permissions_api.module_id</code>.
     */
    public void setModuleId(Long moduleId) {
        this.moduleId = moduleId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PermissionsApi other = (PermissionsApi) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.groupId == null) {
            if (other.groupId != null)
                return false;
        }
        else if (!this.groupId.equals(other.groupId))
            return false;
        if (this.moduleId == null) {
            if (other.moduleId != null)
                return false;
        }
        else if (!this.moduleId.equals(other.moduleId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.groupId == null) ? 0 : this.groupId.hashCode());
        result = prime * result + ((this.moduleId == null) ? 0 : this.moduleId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PermissionsApi (");

        sb.append(id);
        sb.append(", ").append(groupId);
        sb.append(", ").append(moduleId);

        sb.append(")");
        return sb.toString();
    }
}
