/*
 * This file is generated by jOOQ.
 */
package com.db_access.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PrivacyTerms implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Byte type;
    private String descriptionKh;
    private String descriptionEn;
    private String descriptionZh;
    private LocalDateTime created;
    private Long createdBy;
    private LocalDateTime modified;
    private Long modifiedBy;
    private Byte isActive;

    public PrivacyTerms() {}

    public PrivacyTerms(PrivacyTerms value) {
        this.id = value.id;
        this.type = value.type;
        this.descriptionKh = value.descriptionKh;
        this.descriptionEn = value.descriptionEn;
        this.descriptionZh = value.descriptionZh;
        this.created = value.created;
        this.createdBy = value.createdBy;
        this.modified = value.modified;
        this.modifiedBy = value.modifiedBy;
        this.isActive = value.isActive;
    }

    public PrivacyTerms(
        Long id,
        Byte type,
        String descriptionKh,
        String descriptionEn,
        String descriptionZh,
        LocalDateTime created,
        Long createdBy,
        LocalDateTime modified,
        Long modifiedBy,
        Byte isActive
    ) {
        this.id = id;
        this.type = type;
        this.descriptionKh = descriptionKh;
        this.descriptionEn = descriptionEn;
        this.descriptionZh = descriptionZh;
        this.created = created;
        this.createdBy = createdBy;
        this.modified = modified;
        this.modifiedBy = modifiedBy;
        this.isActive = isActive;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.privacy_terms.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.privacy_terms.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.privacy_terms.type</code>. 1:
     * Privacy, 2: Terms
     */
    public Byte getType() {
        return this.type;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.privacy_terms.type</code>. 1:
     * Privacy, 2: Terms
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.privacy_terms.description_kh</code>.
     */
    public String getDescriptionKh() {
        return this.descriptionKh;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.privacy_terms.description_kh</code>.
     */
    public void setDescriptionKh(String descriptionKh) {
        this.descriptionKh = descriptionKh;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.privacy_terms.description_en</code>.
     */
    public String getDescriptionEn() {
        return this.descriptionEn;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.privacy_terms.description_en</code>.
     */
    public void setDescriptionEn(String descriptionEn) {
        this.descriptionEn = descriptionEn;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.privacy_terms.description_zh</code>.
     */
    public String getDescriptionZh() {
        return this.descriptionZh;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.privacy_terms.description_zh</code>.
     */
    public void setDescriptionZh(String descriptionZh) {
        this.descriptionZh = descriptionZh;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.privacy_terms.created</code>.
     */
    public LocalDateTime getCreated() {
        return this.created;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.privacy_terms.created</code>.
     */
    public void setCreated(LocalDateTime created) {
        this.created = created;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.privacy_terms.created_by</code>.
     */
    public Long getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.privacy_terms.created_by</code>.
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.privacy_terms.modified</code>.
     */
    public LocalDateTime getModified() {
        return this.modified;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.privacy_terms.modified</code>.
     */
    public void setModified(LocalDateTime modified) {
        this.modified = modified;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.privacy_terms.modified_by</code>.
     */
    public Long getModifiedBy() {
        return this.modifiedBy;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.privacy_terms.modified_by</code>.
     */
    public void setModifiedBy(Long modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.privacy_terms.is_active</code>.
     * 0: Inactive, 1: Active
     */
    public Byte getIsActive() {
        return this.isActive;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.privacy_terms.is_active</code>.
     * 0: Inactive, 1: Active
     */
    public void setIsActive(Byte isActive) {
        this.isActive = isActive;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PrivacyTerms other = (PrivacyTerms) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.type == null) {
            if (other.type != null)
                return false;
        }
        else if (!this.type.equals(other.type))
            return false;
        if (this.descriptionKh == null) {
            if (other.descriptionKh != null)
                return false;
        }
        else if (!this.descriptionKh.equals(other.descriptionKh))
            return false;
        if (this.descriptionEn == null) {
            if (other.descriptionEn != null)
                return false;
        }
        else if (!this.descriptionEn.equals(other.descriptionEn))
            return false;
        if (this.descriptionZh == null) {
            if (other.descriptionZh != null)
                return false;
        }
        else if (!this.descriptionZh.equals(other.descriptionZh))
            return false;
        if (this.created == null) {
            if (other.created != null)
                return false;
        }
        else if (!this.created.equals(other.created))
            return false;
        if (this.createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!this.createdBy.equals(other.createdBy))
            return false;
        if (this.modified == null) {
            if (other.modified != null)
                return false;
        }
        else if (!this.modified.equals(other.modified))
            return false;
        if (this.modifiedBy == null) {
            if (other.modifiedBy != null)
                return false;
        }
        else if (!this.modifiedBy.equals(other.modifiedBy))
            return false;
        if (this.isActive == null) {
            if (other.isActive != null)
                return false;
        }
        else if (!this.isActive.equals(other.isActive))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.type == null) ? 0 : this.type.hashCode());
        result = prime * result + ((this.descriptionKh == null) ? 0 : this.descriptionKh.hashCode());
        result = prime * result + ((this.descriptionEn == null) ? 0 : this.descriptionEn.hashCode());
        result = prime * result + ((this.descriptionZh == null) ? 0 : this.descriptionZh.hashCode());
        result = prime * result + ((this.created == null) ? 0 : this.created.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.modified == null) ? 0 : this.modified.hashCode());
        result = prime * result + ((this.modifiedBy == null) ? 0 : this.modifiedBy.hashCode());
        result = prime * result + ((this.isActive == null) ? 0 : this.isActive.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PrivacyTerms (");

        sb.append(id);
        sb.append(", ").append(type);
        sb.append(", ").append(descriptionKh);
        sb.append(", ").append(descriptionEn);
        sb.append(", ").append(descriptionZh);
        sb.append(", ").append(created);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(modified);
        sb.append(", ").append(modifiedBy);
        sb.append(", ").append(isActive);

        sb.append(")");
        return sb.toString();
    }
}
