/*
 * This file is generated by jOOQ.
 */
package com.db_access.jooq.tables.pojos;


import jakarta.validation.constraints.Size;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SalesOrderPayments implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long salesOrderId;
    private String transactionId;
    private String qrString;
    private String qrImage;
    private String abapayUrl;
    private String currency;
    private BigDecimal amount;
    private LocalDateTime created;
    private LocalDateTime expired;
    private Byte status;

    public SalesOrderPayments() {}

    public SalesOrderPayments(SalesOrderPayments value) {
        this.id = value.id;
        this.salesOrderId = value.salesOrderId;
        this.transactionId = value.transactionId;
        this.qrString = value.qrString;
        this.qrImage = value.qrImage;
        this.abapayUrl = value.abapayUrl;
        this.currency = value.currency;
        this.amount = value.amount;
        this.created = value.created;
        this.expired = value.expired;
        this.status = value.status;
    }

    public SalesOrderPayments(
        Long id,
        Long salesOrderId,
        String transactionId,
        String qrString,
        String qrImage,
        String abapayUrl,
        String currency,
        BigDecimal amount,
        LocalDateTime created,
        LocalDateTime expired,
        Byte status
    ) {
        this.id = id;
        this.salesOrderId = salesOrderId;
        this.transactionId = transactionId;
        this.qrString = qrString;
        this.qrImage = qrImage;
        this.abapayUrl = abapayUrl;
        this.currency = currency;
        this.amount = amount;
        this.created = created;
        this.expired = expired;
        this.status = status;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.sales_order_payments.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.sales_order_payments.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.sales_order_payments.sales_order_id</code>.
     */
    public Long getSalesOrderId() {
        return this.salesOrderId;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.sales_order_payments.sales_order_id</code>.
     */
    public void setSalesOrderId(Long salesOrderId) {
        this.salesOrderId = salesOrderId;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.sales_order_payments.transaction_id</code>.
     * tran_id from Payway
     */
    @Size(max = 50)
    public String getTransactionId() {
        return this.transactionId;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.sales_order_payments.transaction_id</code>.
     * tran_id from Payway
     */
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.sales_order_payments.qr_string</code>.
     */
    @Size(max = 65535)
    public String getQrString() {
        return this.qrString;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.sales_order_payments.qr_string</code>.
     */
    public void setQrString(String qrString) {
        this.qrString = qrString;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.sales_order_payments.qr_image</code>.
     */
    @Size(max = 65535)
    public String getQrImage() {
        return this.qrImage;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.sales_order_payments.qr_image</code>.
     */
    public void setQrImage(String qrImage) {
        this.qrImage = qrImage;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.sales_order_payments.abapay_url</code>.
     */
    @Size(max = 65535)
    public String getAbapayUrl() {
        return this.abapayUrl;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.sales_order_payments.abapay_url</code>.
     */
    public void setAbapayUrl(String abapayUrl) {
        this.abapayUrl = abapayUrl;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.sales_order_payments.currency</code>.
     */
    @Size(max = 10)
    public String getCurrency() {
        return this.currency;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.sales_order_payments.currency</code>.
     */
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.sales_order_payments.amount</code>.
     */
    public BigDecimal getAmount() {
        return this.amount;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.sales_order_payments.amount</code>.
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.sales_order_payments.created</code>.
     */
    public LocalDateTime getCreated() {
        return this.created;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.sales_order_payments.created</code>.
     */
    public void setCreated(LocalDateTime created) {
        this.created = created;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.sales_order_payments.expired</code>.
     */
    public LocalDateTime getExpired() {
        return this.expired;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.sales_order_payments.expired</code>.
     */
    public void setExpired(LocalDateTime expired) {
        this.expired = expired;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.sales_order_payments.status</code>. 1:
     * Pending, 2: Paid, 3: Expired
     */
    public Byte getStatus() {
        return this.status;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.sales_order_payments.status</code>. 1:
     * Pending, 2: Paid, 3: Expired
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final SalesOrderPayments other = (SalesOrderPayments) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.salesOrderId == null) {
            if (other.salesOrderId != null)
                return false;
        }
        else if (!this.salesOrderId.equals(other.salesOrderId))
            return false;
        if (this.transactionId == null) {
            if (other.transactionId != null)
                return false;
        }
        else if (!this.transactionId.equals(other.transactionId))
            return false;
        if (this.qrString == null) {
            if (other.qrString != null)
                return false;
        }
        else if (!this.qrString.equals(other.qrString))
            return false;
        if (this.qrImage == null) {
            if (other.qrImage != null)
                return false;
        }
        else if (!this.qrImage.equals(other.qrImage))
            return false;
        if (this.abapayUrl == null) {
            if (other.abapayUrl != null)
                return false;
        }
        else if (!this.abapayUrl.equals(other.abapayUrl))
            return false;
        if (this.currency == null) {
            if (other.currency != null)
                return false;
        }
        else if (!this.currency.equals(other.currency))
            return false;
        if (this.amount == null) {
            if (other.amount != null)
                return false;
        }
        else if (!this.amount.equals(other.amount))
            return false;
        if (this.created == null) {
            if (other.created != null)
                return false;
        }
        else if (!this.created.equals(other.created))
            return false;
        if (this.expired == null) {
            if (other.expired != null)
                return false;
        }
        else if (!this.expired.equals(other.expired))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.salesOrderId == null) ? 0 : this.salesOrderId.hashCode());
        result = prime * result + ((this.transactionId == null) ? 0 : this.transactionId.hashCode());
        result = prime * result + ((this.qrString == null) ? 0 : this.qrString.hashCode());
        result = prime * result + ((this.qrImage == null) ? 0 : this.qrImage.hashCode());
        result = prime * result + ((this.abapayUrl == null) ? 0 : this.abapayUrl.hashCode());
        result = prime * result + ((this.currency == null) ? 0 : this.currency.hashCode());
        result = prime * result + ((this.amount == null) ? 0 : this.amount.hashCode());
        result = prime * result + ((this.created == null) ? 0 : this.created.hashCode());
        result = prime * result + ((this.expired == null) ? 0 : this.expired.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SalesOrderPayments (");

        sb.append(id);
        sb.append(", ").append(salesOrderId);
        sb.append(", ").append(transactionId);
        sb.append(", ").append(qrString);
        sb.append(", ").append(qrImage);
        sb.append(", ").append(abapayUrl);
        sb.append(", ").append(currency);
        sb.append(", ").append(amount);
        sb.append(", ").append(created);
        sb.append(", ").append(expired);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
