/*
 * This file is generated by jOOQ.
 */
package com.db_access.jooq.tables.pojos;


import jakarta.validation.constraints.Size;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SystemActivitiesApi implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String endpoint;
    private String module;
    private Long moduleId;
    private String act;
    private String description;
    private String bug;
    private String lineCode;
    private String browser;
    private String operatingSystem;
    private String ip;
    private String hostName;
    private Integer duration;
    private LocalDateTime created;
    private Long createdBy;
    private Byte status;

    public SystemActivitiesApi() {}

    public SystemActivitiesApi(SystemActivitiesApi value) {
        this.id = value.id;
        this.endpoint = value.endpoint;
        this.module = value.module;
        this.moduleId = value.moduleId;
        this.act = value.act;
        this.description = value.description;
        this.bug = value.bug;
        this.lineCode = value.lineCode;
        this.browser = value.browser;
        this.operatingSystem = value.operatingSystem;
        this.ip = value.ip;
        this.hostName = value.hostName;
        this.duration = value.duration;
        this.created = value.created;
        this.createdBy = value.createdBy;
        this.status = value.status;
    }

    public SystemActivitiesApi(
        Long id,
        String endpoint,
        String module,
        Long moduleId,
        String act,
        String description,
        String bug,
        String lineCode,
        String browser,
        String operatingSystem,
        String ip,
        String hostName,
        Integer duration,
        LocalDateTime created,
        Long createdBy,
        Byte status
    ) {
        this.id = id;
        this.endpoint = endpoint;
        this.module = module;
        this.moduleId = moduleId;
        this.act = act;
        this.description = description;
        this.bug = bug;
        this.lineCode = lineCode;
        this.browser = browser;
        this.operatingSystem = operatingSystem;
        this.ip = ip;
        this.hostName = hostName;
        this.duration = duration;
        this.created = created;
        this.createdBy = createdBy;
        this.status = status;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.system_activities_api.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.system_activities_api.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.system_activities_api.endpoint</code>.
     */
    @Size(max = 50)
    public String getEndpoint() {
        return this.endpoint;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.system_activities_api.endpoint</code>.
     */
    public void setEndpoint(String endpoint) {
        this.endpoint = endpoint;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.system_activities_api.module</code>.
     */
    @Size(max = 50)
    public String getModule() {
        return this.module;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.system_activities_api.module</code>.
     */
    public void setModule(String module) {
        this.module = module;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.system_activities_api.module_id</code>.
     */
    public Long getModuleId() {
        return this.moduleId;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.system_activities_api.module_id</code>.
     */
    public void setModuleId(Long moduleId) {
        this.moduleId = moduleId;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.system_activities_api.act</code>.
     */
    @Size(max = 50)
    public String getAct() {
        return this.act;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.system_activities_api.act</code>.
     */
    public void setAct(String act) {
        this.act = act;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.system_activities_api.description</code>.
     */
    @Size(max = 65535)
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.system_activities_api.description</code>.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.system_activities_api.bug</code>.
     */
    public String getBug() {
        return this.bug;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.system_activities_api.bug</code>.
     */
    public void setBug(String bug) {
        this.bug = bug;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.system_activities_api.line_code</code>.
     */
    @Size(max = 50)
    public String getLineCode() {
        return this.lineCode;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.system_activities_api.line_code</code>.
     */
    public void setLineCode(String lineCode) {
        this.lineCode = lineCode;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.system_activities_api.browser</code>.
     */
    @Size(max = 250)
    public String getBrowser() {
        return this.browser;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.system_activities_api.browser</code>.
     */
    public void setBrowser(String browser) {
        this.browser = browser;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.system_activities_api.operating_system</code>.
     */
    @Size(max = 250)
    public String getOperatingSystem() {
        return this.operatingSystem;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.system_activities_api.operating_system</code>.
     */
    public void setOperatingSystem(String operatingSystem) {
        this.operatingSystem = operatingSystem;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.system_activities_api.ip</code>.
     */
    @Size(max = 50)
    public String getIp() {
        return this.ip;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.system_activities_api.ip</code>.
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.system_activities_api.host_name</code>.
     */
    @Size(max = 50)
    public String getHostName() {
        return this.hostName;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.system_activities_api.host_name</code>.
     */
    public void setHostName(String hostName) {
        this.hostName = hostName;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.system_activities_api.duration</code>.
     * SECONDS
     */
    public Integer getDuration() {
        return this.duration;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.system_activities_api.duration</code>.
     * SECONDS
     */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.system_activities_api.created</code>.
     */
    public LocalDateTime getCreated() {
        return this.created;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.system_activities_api.created</code>.
     */
    public void setCreated(LocalDateTime created) {
        this.created = created;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.system_activities_api.created_by</code>.
     */
    public Long getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.system_activities_api.created_by</code>.
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.system_activities_api.status</code>. 1:
     * Complete; 2: Bug
     */
    public Byte getStatus() {
        return this.status;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.system_activities_api.status</code>. 1:
     * Complete; 2: Bug
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final SystemActivitiesApi other = (SystemActivitiesApi) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.endpoint == null) {
            if (other.endpoint != null)
                return false;
        }
        else if (!this.endpoint.equals(other.endpoint))
            return false;
        if (this.module == null) {
            if (other.module != null)
                return false;
        }
        else if (!this.module.equals(other.module))
            return false;
        if (this.moduleId == null) {
            if (other.moduleId != null)
                return false;
        }
        else if (!this.moduleId.equals(other.moduleId))
            return false;
        if (this.act == null) {
            if (other.act != null)
                return false;
        }
        else if (!this.act.equals(other.act))
            return false;
        if (this.description == null) {
            if (other.description != null)
                return false;
        }
        else if (!this.description.equals(other.description))
            return false;
        if (this.bug == null) {
            if (other.bug != null)
                return false;
        }
        else if (!this.bug.equals(other.bug))
            return false;
        if (this.lineCode == null) {
            if (other.lineCode != null)
                return false;
        }
        else if (!this.lineCode.equals(other.lineCode))
            return false;
        if (this.browser == null) {
            if (other.browser != null)
                return false;
        }
        else if (!this.browser.equals(other.browser))
            return false;
        if (this.operatingSystem == null) {
            if (other.operatingSystem != null)
                return false;
        }
        else if (!this.operatingSystem.equals(other.operatingSystem))
            return false;
        if (this.ip == null) {
            if (other.ip != null)
                return false;
        }
        else if (!this.ip.equals(other.ip))
            return false;
        if (this.hostName == null) {
            if (other.hostName != null)
                return false;
        }
        else if (!this.hostName.equals(other.hostName))
            return false;
        if (this.duration == null) {
            if (other.duration != null)
                return false;
        }
        else if (!this.duration.equals(other.duration))
            return false;
        if (this.created == null) {
            if (other.created != null)
                return false;
        }
        else if (!this.created.equals(other.created))
            return false;
        if (this.createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!this.createdBy.equals(other.createdBy))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.endpoint == null) ? 0 : this.endpoint.hashCode());
        result = prime * result + ((this.module == null) ? 0 : this.module.hashCode());
        result = prime * result + ((this.moduleId == null) ? 0 : this.moduleId.hashCode());
        result = prime * result + ((this.act == null) ? 0 : this.act.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.bug == null) ? 0 : this.bug.hashCode());
        result = prime * result + ((this.lineCode == null) ? 0 : this.lineCode.hashCode());
        result = prime * result + ((this.browser == null) ? 0 : this.browser.hashCode());
        result = prime * result + ((this.operatingSystem == null) ? 0 : this.operatingSystem.hashCode());
        result = prime * result + ((this.ip == null) ? 0 : this.ip.hashCode());
        result = prime * result + ((this.hostName == null) ? 0 : this.hostName.hashCode());
        result = prime * result + ((this.duration == null) ? 0 : this.duration.hashCode());
        result = prime * result + ((this.created == null) ? 0 : this.created.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SystemActivitiesApi (");

        sb.append(id);
        sb.append(", ").append(endpoint);
        sb.append(", ").append(module);
        sb.append(", ").append(moduleId);
        sb.append(", ").append(act);
        sb.append(", ").append(description);
        sb.append(", ").append(bug);
        sb.append(", ").append(lineCode);
        sb.append(", ").append(browser);
        sb.append(", ").append(operatingSystem);
        sb.append(", ").append(ip);
        sb.append(", ").append(hostName);
        sb.append(", ").append(duration);
        sb.append(", ").append(created);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
