/*
 * This file is generated by jOOQ.
 */
package com.db_access.jooq.tables.pojos;


import jakarta.validation.constraints.Size;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersApi implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Byte isSuperAdmin;
    private String firstName;
    private String lastName;
    private String fullName;
    private String username;
    private String password;
    private String photo;
    private String signature;
    private String phoneVerifyToken;
    private String sessionId;
    private LocalDateTime sessionStart;
    private LocalDateTime sessionActive;
    private String sessionLat;
    private String sessionLong;
    private String loginAttemptRemoteIp;
    private String loginAttemptHttpUserAgent;
    private Byte statusLogin;
    private Long createdBy;
    private LocalDateTime created;
    private LocalDateTime modified;
    private Long modifiedBy;
    private Byte isActive;
    private String refreshToken;
    private LocalDateTime refreshTokenExpiration;
    private String deviceId;
    private String deviceName;
    private String pushToken;

    public UsersApi() {}

    public UsersApi(UsersApi value) {
        this.id = value.id;
        this.isSuperAdmin = value.isSuperAdmin;
        this.firstName = value.firstName;
        this.lastName = value.lastName;
        this.fullName = value.fullName;
        this.username = value.username;
        this.password = value.password;
        this.photo = value.photo;
        this.signature = value.signature;
        this.phoneVerifyToken = value.phoneVerifyToken;
        this.sessionId = value.sessionId;
        this.sessionStart = value.sessionStart;
        this.sessionActive = value.sessionActive;
        this.sessionLat = value.sessionLat;
        this.sessionLong = value.sessionLong;
        this.loginAttemptRemoteIp = value.loginAttemptRemoteIp;
        this.loginAttemptHttpUserAgent = value.loginAttemptHttpUserAgent;
        this.statusLogin = value.statusLogin;
        this.createdBy = value.createdBy;
        this.created = value.created;
        this.modified = value.modified;
        this.modifiedBy = value.modifiedBy;
        this.isActive = value.isActive;
        this.refreshToken = value.refreshToken;
        this.refreshTokenExpiration = value.refreshTokenExpiration;
        this.deviceId = value.deviceId;
        this.deviceName = value.deviceName;
        this.pushToken = value.pushToken;
    }

    public UsersApi(
        Long id,
        Byte isSuperAdmin,
        String firstName,
        String lastName,
        String fullName,
        String username,
        String password,
        String photo,
        String signature,
        String phoneVerifyToken,
        String sessionId,
        LocalDateTime sessionStart,
        LocalDateTime sessionActive,
        String sessionLat,
        String sessionLong,
        String loginAttemptRemoteIp,
        String loginAttemptHttpUserAgent,
        Byte statusLogin,
        Long createdBy,
        LocalDateTime created,
        LocalDateTime modified,
        Long modifiedBy,
        Byte isActive,
        String refreshToken,
        LocalDateTime refreshTokenExpiration,
        String deviceId,
        String deviceName,
        String pushToken
    ) {
        this.id = id;
        this.isSuperAdmin = isSuperAdmin;
        this.firstName = firstName;
        this.lastName = lastName;
        this.fullName = fullName;
        this.username = username;
        this.password = password;
        this.photo = photo;
        this.signature = signature;
        this.phoneVerifyToken = phoneVerifyToken;
        this.sessionId = sessionId;
        this.sessionStart = sessionStart;
        this.sessionActive = sessionActive;
        this.sessionLat = sessionLat;
        this.sessionLong = sessionLong;
        this.loginAttemptRemoteIp = loginAttemptRemoteIp;
        this.loginAttemptHttpUserAgent = loginAttemptHttpUserAgent;
        this.statusLogin = statusLogin;
        this.createdBy = createdBy;
        this.created = created;
        this.modified = modified;
        this.modifiedBy = modifiedBy;
        this.isActive = isActive;
        this.refreshToken = refreshToken;
        this.refreshTokenExpiration = refreshTokenExpiration;
        this.deviceId = deviceId;
        this.deviceName = deviceName;
        this.pushToken = pushToken;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.users_api.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.users_api.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.users_api.is_super_admin</code>. 0: false,
     * 1: true
     */
    public Byte getIsSuperAdmin() {
        return this.isSuperAdmin;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.users_api.is_super_admin</code>. 0: false,
     * 1: true
     */
    public void setIsSuperAdmin(Byte isSuperAdmin) {
        this.isSuperAdmin = isSuperAdmin;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.users_api.first_name</code>.
     */
    @Size(max = 50)
    public String getFirstName() {
        return this.firstName;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.users_api.first_name</code>.
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.users_api.last_name</code>.
     */
    @Size(max = 50)
    public String getLastName() {
        return this.lastName;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.users_api.last_name</code>.
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.users_api.full_name</code>.
     */
    @Size(max = 50)
    public String getFullName() {
        return this.fullName;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.users_api.full_name</code>.
     */
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.users_api.username</code>.
     */
    @Size(max = 50)
    public String getUsername() {
        return this.username;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.users_api.username</code>.
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.users_api.password</code>.
     */
    @Size(max = 255)
    public String getPassword() {
        return this.password;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.users_api.password</code>.
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.users_api.photo</code>.
     */
    @Size(max = 255)
    public String getPhoto() {
        return this.photo;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.users_api.photo</code>.
     */
    public void setPhoto(String photo) {
        this.photo = photo;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.users_api.signature</code>.
     */
    @Size(max = 255)
    public String getSignature() {
        return this.signature;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.users_api.signature</code>.
     */
    public void setSignature(String signature) {
        this.signature = signature;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.users_api.phone_verify_token</code>.
     */
    @Size(max = 255)
    public String getPhoneVerifyToken() {
        return this.phoneVerifyToken;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.users_api.phone_verify_token</code>.
     */
    public void setPhoneVerifyToken(String phoneVerifyToken) {
        this.phoneVerifyToken = phoneVerifyToken;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.users_api.session_id</code>.
     */
    @Size(max = 150)
    public String getSessionId() {
        return this.sessionId;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.users_api.session_id</code>.
     */
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.users_api.session_start</code>.
     */
    public LocalDateTime getSessionStart() {
        return this.sessionStart;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.users_api.session_start</code>.
     */
    public void setSessionStart(LocalDateTime sessionStart) {
        this.sessionStart = sessionStart;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.users_api.session_active</code>.
     */
    public LocalDateTime getSessionActive() {
        return this.sessionActive;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.users_api.session_active</code>.
     */
    public void setSessionActive(LocalDateTime sessionActive) {
        this.sessionActive = sessionActive;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.users_api.session_lat</code>.
     */
    @Size(max = 50)
    public String getSessionLat() {
        return this.sessionLat;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.users_api.session_lat</code>.
     */
    public void setSessionLat(String sessionLat) {
        this.sessionLat = sessionLat;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.users_api.session_long</code>.
     */
    @Size(max = 50)
    public String getSessionLong() {
        return this.sessionLong;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.users_api.session_long</code>.
     */
    public void setSessionLong(String sessionLong) {
        this.sessionLong = sessionLong;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.users_api.login_attempt_remote_ip</code>.
     */
    @Size(max = 50)
    public String getLoginAttemptRemoteIp() {
        return this.loginAttemptRemoteIp;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.users_api.login_attempt_remote_ip</code>.
     */
    public void setLoginAttemptRemoteIp(String loginAttemptRemoteIp) {
        this.loginAttemptRemoteIp = loginAttemptRemoteIp;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.users_api.login_attempt_http_user_agent</code>.
     */
    @Size(max = 50)
    public String getLoginAttemptHttpUserAgent() {
        return this.loginAttemptHttpUserAgent;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.users_api.login_attempt_http_user_agent</code>.
     */
    public void setLoginAttemptHttpUserAgent(String loginAttemptHttpUserAgent) {
        this.loginAttemptHttpUserAgent = loginAttemptHttpUserAgent;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.users_api.status_login</code>.
     * 1. never; 2. Ever login
     */
    public Byte getStatusLogin() {
        return this.statusLogin;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.users_api.status_login</code>.
     * 1. never; 2. Ever login
     */
    public void setStatusLogin(Byte statusLogin) {
        this.statusLogin = statusLogin;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.users_api.created_by</code>.
     */
    public Long getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.users_api.created_by</code>.
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.users_api.created</code>.
     */
    public LocalDateTime getCreated() {
        return this.created;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.users_api.created</code>.
     */
    public void setCreated(LocalDateTime created) {
        this.created = created;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.users_api.modified</code>.
     */
    public LocalDateTime getModified() {
        return this.modified;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.users_api.modified</code>.
     */
    public void setModified(LocalDateTime modified) {
        this.modified = modified;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.users_api.modified_by</code>.
     */
    public Long getModifiedBy() {
        return this.modifiedBy;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.users_api.modified_by</code>.
     */
    public void setModifiedBy(Long modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.users_api.is_active</code>. 1:
     * Pending; 2: Active
     */
    public Byte getIsActive() {
        return this.isActive;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.users_api.is_active</code>. 1:
     * Pending; 2: Active
     */
    public void setIsActive(Byte isActive) {
        this.isActive = isActive;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.users_api.refresh_token</code>.
     */
    @Size(max = 65535)
    public String getRefreshToken() {
        return this.refreshToken;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.users_api.refresh_token</code>.
     */
    public void setRefreshToken(String refreshToken) {
        this.refreshToken = refreshToken;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.users_api.refresh_token_expiration</code>.
     */
    public LocalDateTime getRefreshTokenExpiration() {
        return this.refreshTokenExpiration;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.users_api.refresh_token_expiration</code>.
     */
    public void setRefreshTokenExpiration(LocalDateTime refreshTokenExpiration) {
        this.refreshTokenExpiration = refreshTokenExpiration;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.users_api.device_id</code>.
     */
    @Size(max = 255)
    public String getDeviceId() {
        return this.deviceId;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.users_api.device_id</code>.
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.users_api.device_name</code>.
     */
    @Size(max = 255)
    public String getDeviceName() {
        return this.deviceName;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.users_api.device_name</code>.
     */
    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.users_api.push_token</code>.
     */
    @Size(max = 65535)
    public String getPushToken() {
        return this.pushToken;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.users_api.push_token</code>.
     */
    public void setPushToken(String pushToken) {
        this.pushToken = pushToken;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UsersApi other = (UsersApi) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.isSuperAdmin == null) {
            if (other.isSuperAdmin != null)
                return false;
        }
        else if (!this.isSuperAdmin.equals(other.isSuperAdmin))
            return false;
        if (this.firstName == null) {
            if (other.firstName != null)
                return false;
        }
        else if (!this.firstName.equals(other.firstName))
            return false;
        if (this.lastName == null) {
            if (other.lastName != null)
                return false;
        }
        else if (!this.lastName.equals(other.lastName))
            return false;
        if (this.fullName == null) {
            if (other.fullName != null)
                return false;
        }
        else if (!this.fullName.equals(other.fullName))
            return false;
        if (this.username == null) {
            if (other.username != null)
                return false;
        }
        else if (!this.username.equals(other.username))
            return false;
        if (this.password == null) {
            if (other.password != null)
                return false;
        }
        else if (!this.password.equals(other.password))
            return false;
        if (this.photo == null) {
            if (other.photo != null)
                return false;
        }
        else if (!this.photo.equals(other.photo))
            return false;
        if (this.signature == null) {
            if (other.signature != null)
                return false;
        }
        else if (!this.signature.equals(other.signature))
            return false;
        if (this.phoneVerifyToken == null) {
            if (other.phoneVerifyToken != null)
                return false;
        }
        else if (!this.phoneVerifyToken.equals(other.phoneVerifyToken))
            return false;
        if (this.sessionId == null) {
            if (other.sessionId != null)
                return false;
        }
        else if (!this.sessionId.equals(other.sessionId))
            return false;
        if (this.sessionStart == null) {
            if (other.sessionStart != null)
                return false;
        }
        else if (!this.sessionStart.equals(other.sessionStart))
            return false;
        if (this.sessionActive == null) {
            if (other.sessionActive != null)
                return false;
        }
        else if (!this.sessionActive.equals(other.sessionActive))
            return false;
        if (this.sessionLat == null) {
            if (other.sessionLat != null)
                return false;
        }
        else if (!this.sessionLat.equals(other.sessionLat))
            return false;
        if (this.sessionLong == null) {
            if (other.sessionLong != null)
                return false;
        }
        else if (!this.sessionLong.equals(other.sessionLong))
            return false;
        if (this.loginAttemptRemoteIp == null) {
            if (other.loginAttemptRemoteIp != null)
                return false;
        }
        else if (!this.loginAttemptRemoteIp.equals(other.loginAttemptRemoteIp))
            return false;
        if (this.loginAttemptHttpUserAgent == null) {
            if (other.loginAttemptHttpUserAgent != null)
                return false;
        }
        else if (!this.loginAttemptHttpUserAgent.equals(other.loginAttemptHttpUserAgent))
            return false;
        if (this.statusLogin == null) {
            if (other.statusLogin != null)
                return false;
        }
        else if (!this.statusLogin.equals(other.statusLogin))
            return false;
        if (this.createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!this.createdBy.equals(other.createdBy))
            return false;
        if (this.created == null) {
            if (other.created != null)
                return false;
        }
        else if (!this.created.equals(other.created))
            return false;
        if (this.modified == null) {
            if (other.modified != null)
                return false;
        }
        else if (!this.modified.equals(other.modified))
            return false;
        if (this.modifiedBy == null) {
            if (other.modifiedBy != null)
                return false;
        }
        else if (!this.modifiedBy.equals(other.modifiedBy))
            return false;
        if (this.isActive == null) {
            if (other.isActive != null)
                return false;
        }
        else if (!this.isActive.equals(other.isActive))
            return false;
        if (this.refreshToken == null) {
            if (other.refreshToken != null)
                return false;
        }
        else if (!this.refreshToken.equals(other.refreshToken))
            return false;
        if (this.refreshTokenExpiration == null) {
            if (other.refreshTokenExpiration != null)
                return false;
        }
        else if (!this.refreshTokenExpiration.equals(other.refreshTokenExpiration))
            return false;
        if (this.deviceId == null) {
            if (other.deviceId != null)
                return false;
        }
        else if (!this.deviceId.equals(other.deviceId))
            return false;
        if (this.deviceName == null) {
            if (other.deviceName != null)
                return false;
        }
        else if (!this.deviceName.equals(other.deviceName))
            return false;
        if (this.pushToken == null) {
            if (other.pushToken != null)
                return false;
        }
        else if (!this.pushToken.equals(other.pushToken))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.isSuperAdmin == null) ? 0 : this.isSuperAdmin.hashCode());
        result = prime * result + ((this.firstName == null) ? 0 : this.firstName.hashCode());
        result = prime * result + ((this.lastName == null) ? 0 : this.lastName.hashCode());
        result = prime * result + ((this.fullName == null) ? 0 : this.fullName.hashCode());
        result = prime * result + ((this.username == null) ? 0 : this.username.hashCode());
        result = prime * result + ((this.password == null) ? 0 : this.password.hashCode());
        result = prime * result + ((this.photo == null) ? 0 : this.photo.hashCode());
        result = prime * result + ((this.signature == null) ? 0 : this.signature.hashCode());
        result = prime * result + ((this.phoneVerifyToken == null) ? 0 : this.phoneVerifyToken.hashCode());
        result = prime * result + ((this.sessionId == null) ? 0 : this.sessionId.hashCode());
        result = prime * result + ((this.sessionStart == null) ? 0 : this.sessionStart.hashCode());
        result = prime * result + ((this.sessionActive == null) ? 0 : this.sessionActive.hashCode());
        result = prime * result + ((this.sessionLat == null) ? 0 : this.sessionLat.hashCode());
        result = prime * result + ((this.sessionLong == null) ? 0 : this.sessionLong.hashCode());
        result = prime * result + ((this.loginAttemptRemoteIp == null) ? 0 : this.loginAttemptRemoteIp.hashCode());
        result = prime * result + ((this.loginAttemptHttpUserAgent == null) ? 0 : this.loginAttemptHttpUserAgent.hashCode());
        result = prime * result + ((this.statusLogin == null) ? 0 : this.statusLogin.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.created == null) ? 0 : this.created.hashCode());
        result = prime * result + ((this.modified == null) ? 0 : this.modified.hashCode());
        result = prime * result + ((this.modifiedBy == null) ? 0 : this.modifiedBy.hashCode());
        result = prime * result + ((this.isActive == null) ? 0 : this.isActive.hashCode());
        result = prime * result + ((this.refreshToken == null) ? 0 : this.refreshToken.hashCode());
        result = prime * result + ((this.refreshTokenExpiration == null) ? 0 : this.refreshTokenExpiration.hashCode());
        result = prime * result + ((this.deviceId == null) ? 0 : this.deviceId.hashCode());
        result = prime * result + ((this.deviceName == null) ? 0 : this.deviceName.hashCode());
        result = prime * result + ((this.pushToken == null) ? 0 : this.pushToken.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UsersApi (");

        sb.append(id);
        sb.append(", ").append(isSuperAdmin);
        sb.append(", ").append(firstName);
        sb.append(", ").append(lastName);
        sb.append(", ").append(fullName);
        sb.append(", ").append(username);
        sb.append(", ").append(password);
        sb.append(", ").append(photo);
        sb.append(", ").append(signature);
        sb.append(", ").append(phoneVerifyToken);
        sb.append(", ").append(sessionId);
        sb.append(", ").append(sessionStart);
        sb.append(", ").append(sessionActive);
        sb.append(", ").append(sessionLat);
        sb.append(", ").append(sessionLong);
        sb.append(", ").append(loginAttemptRemoteIp);
        sb.append(", ").append(loginAttemptHttpUserAgent);
        sb.append(", ").append(statusLogin);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(created);
        sb.append(", ").append(modified);
        sb.append(", ").append(modifiedBy);
        sb.append(", ").append(isActive);
        sb.append(", ").append(refreshToken);
        sb.append(", ").append(refreshTokenExpiration);
        sb.append(", ").append(deviceId);
        sb.append(", ").append(deviceName);
        sb.append(", ").append(pushToken);

        sb.append(")");
        return sb.toString();
    }
}
