/*
 * This file is generated by jOOQ.
 */
package com.db_access.jooq.tables.pojos;


import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Vehicles implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long brandId;
    private Long modelId;
    private String nameKh;
    private String nameEn;
    private String nameZh;
    private String vehicleCode;
    private String plateNumber;
    private String fileName;
    private String fileUrl;
    private Integer quantity;
    private Integer passengers;
    private Byte isPublic;
    private LocalDateTime created;
    private Long createdBy;
    private LocalDateTime modified;
    private Long modifiedBy;
    private Byte isActive;

    public Vehicles() {}

    public Vehicles(Vehicles value) {
        this.id = value.id;
        this.brandId = value.brandId;
        this.modelId = value.modelId;
        this.nameKh = value.nameKh;
        this.nameEn = value.nameEn;
        this.nameZh = value.nameZh;
        this.vehicleCode = value.vehicleCode;
        this.plateNumber = value.plateNumber;
        this.fileName = value.fileName;
        this.fileUrl = value.fileUrl;
        this.quantity = value.quantity;
        this.passengers = value.passengers;
        this.isPublic = value.isPublic;
        this.created = value.created;
        this.createdBy = value.createdBy;
        this.modified = value.modified;
        this.modifiedBy = value.modifiedBy;
        this.isActive = value.isActive;
    }

    public Vehicles(
        Long id,
        Long brandId,
        Long modelId,
        String nameKh,
        String nameEn,
        String nameZh,
        String vehicleCode,
        String plateNumber,
        String fileName,
        String fileUrl,
        Integer quantity,
        Integer passengers,
        Byte isPublic,
        LocalDateTime created,
        Long createdBy,
        LocalDateTime modified,
        Long modifiedBy,
        Byte isActive
    ) {
        this.id = id;
        this.brandId = brandId;
        this.modelId = modelId;
        this.nameKh = nameKh;
        this.nameEn = nameEn;
        this.nameZh = nameZh;
        this.vehicleCode = vehicleCode;
        this.plateNumber = plateNumber;
        this.fileName = fileName;
        this.fileUrl = fileUrl;
        this.quantity = quantity;
        this.passengers = passengers;
        this.isPublic = isPublic;
        this.created = created;
        this.createdBy = createdBy;
        this.modified = modified;
        this.modifiedBy = modifiedBy;
        this.isActive = isActive;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.vehicles.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.vehicles.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.vehicles.brand_id</code>.
     * References vehicle_brands.id
     */
    @NotNull
    public Long getBrandId() {
        return this.brandId;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.vehicles.brand_id</code>.
     * References vehicle_brands.id
     */
    public void setBrandId(Long brandId) {
        this.brandId = brandId;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.vehicles.model_id</code>.
     * References vehicle_models.id
     */
    @NotNull
    public Long getModelId() {
        return this.modelId;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.vehicles.model_id</code>.
     * References vehicle_models.id
     */
    public void setModelId(Long modelId) {
        this.modelId = modelId;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.vehicles.name_kh</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getNameKh() {
        return this.nameKh;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.vehicles.name_kh</code>.
     */
    public void setNameKh(String nameKh) {
        this.nameKh = nameKh;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.vehicles.name_en</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getNameEn() {
        return this.nameEn;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.vehicles.name_en</code>.
     */
    public void setNameEn(String nameEn) {
        this.nameEn = nameEn;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.vehicles.name_zh</code>.
     */
    @Size(max = 255)
    public String getNameZh() {
        return this.nameZh;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.vehicles.name_zh</code>.
     */
    public void setNameZh(String nameZh) {
        this.nameZh = nameZh;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.vehicles.vehicle_code</code>.
     */
    @Size(max = 100)
    public String getVehicleCode() {
        return this.vehicleCode;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.vehicles.vehicle_code</code>.
     */
    public void setVehicleCode(String vehicleCode) {
        this.vehicleCode = vehicleCode;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.vehicles.plate_number</code>.
     */
    @Size(max = 100)
    public String getPlateNumber() {
        return this.plateNumber;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.vehicles.plate_number</code>.
     */
    public void setPlateNumber(String plateNumber) {
        this.plateNumber = plateNumber;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.vehicles.file_name</code>.
     */
    @Size(max = 255)
    public String getFileName() {
        return this.fileName;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.vehicles.file_name</code>.
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.vehicles.file_url</code>.
     */
    @Size(max = 255)
    public String getFileUrl() {
        return this.fileUrl;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.vehicles.file_url</code>.
     */
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.vehicles.quantity</code>.
     */
    public Integer getQuantity() {
        return this.quantity;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.vehicles.quantity</code>.
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.vehicles.passengers</code>.
     */
    public Integer getPassengers() {
        return this.passengers;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.vehicles.passengers</code>.
     */
    public void setPassengers(Integer passengers) {
        this.passengers = passengers;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.vehicles.is_public</code>. 0:
     * Hidden, 1: Public To App
     */
    public Byte getIsPublic() {
        return this.isPublic;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.vehicles.is_public</code>. 0:
     * Hidden, 1: Public To App
     */
    public void setIsPublic(Byte isPublic) {
        this.isPublic = isPublic;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.vehicles.created</code>.
     */
    @NotNull
    public LocalDateTime getCreated() {
        return this.created;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.vehicles.created</code>.
     */
    public void setCreated(LocalDateTime created) {
        this.created = created;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.vehicles.created_by</code>.
     */
    public Long getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.vehicles.created_by</code>.
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.vehicles.modified</code>.
     */
    public LocalDateTime getModified() {
        return this.modified;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.vehicles.modified</code>.
     */
    public void setModified(LocalDateTime modified) {
        this.modified = modified;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.vehicles.modified_by</code>.
     */
    public Long getModifiedBy() {
        return this.modifiedBy;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.vehicles.modified_by</code>.
     */
    public void setModifiedBy(Long modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.vehicles.is_active</code>. 0:
     * Inactive, 1: Active
     */
    public Byte getIsActive() {
        return this.isActive;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.vehicles.is_active</code>. 0:
     * Inactive, 1: Active
     */
    public void setIsActive(Byte isActive) {
        this.isActive = isActive;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Vehicles other = (Vehicles) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.brandId == null) {
            if (other.brandId != null)
                return false;
        }
        else if (!this.brandId.equals(other.brandId))
            return false;
        if (this.modelId == null) {
            if (other.modelId != null)
                return false;
        }
        else if (!this.modelId.equals(other.modelId))
            return false;
        if (this.nameKh == null) {
            if (other.nameKh != null)
                return false;
        }
        else if (!this.nameKh.equals(other.nameKh))
            return false;
        if (this.nameEn == null) {
            if (other.nameEn != null)
                return false;
        }
        else if (!this.nameEn.equals(other.nameEn))
            return false;
        if (this.nameZh == null) {
            if (other.nameZh != null)
                return false;
        }
        else if (!this.nameZh.equals(other.nameZh))
            return false;
        if (this.vehicleCode == null) {
            if (other.vehicleCode != null)
                return false;
        }
        else if (!this.vehicleCode.equals(other.vehicleCode))
            return false;
        if (this.plateNumber == null) {
            if (other.plateNumber != null)
                return false;
        }
        else if (!this.plateNumber.equals(other.plateNumber))
            return false;
        if (this.fileName == null) {
            if (other.fileName != null)
                return false;
        }
        else if (!this.fileName.equals(other.fileName))
            return false;
        if (this.fileUrl == null) {
            if (other.fileUrl != null)
                return false;
        }
        else if (!this.fileUrl.equals(other.fileUrl))
            return false;
        if (this.quantity == null) {
            if (other.quantity != null)
                return false;
        }
        else if (!this.quantity.equals(other.quantity))
            return false;
        if (this.passengers == null) {
            if (other.passengers != null)
                return false;
        }
        else if (!this.passengers.equals(other.passengers))
            return false;
        if (this.isPublic == null) {
            if (other.isPublic != null)
                return false;
        }
        else if (!this.isPublic.equals(other.isPublic))
            return false;
        if (this.created == null) {
            if (other.created != null)
                return false;
        }
        else if (!this.created.equals(other.created))
            return false;
        if (this.createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!this.createdBy.equals(other.createdBy))
            return false;
        if (this.modified == null) {
            if (other.modified != null)
                return false;
        }
        else if (!this.modified.equals(other.modified))
            return false;
        if (this.modifiedBy == null) {
            if (other.modifiedBy != null)
                return false;
        }
        else if (!this.modifiedBy.equals(other.modifiedBy))
            return false;
        if (this.isActive == null) {
            if (other.isActive != null)
                return false;
        }
        else if (!this.isActive.equals(other.isActive))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.brandId == null) ? 0 : this.brandId.hashCode());
        result = prime * result + ((this.modelId == null) ? 0 : this.modelId.hashCode());
        result = prime * result + ((this.nameKh == null) ? 0 : this.nameKh.hashCode());
        result = prime * result + ((this.nameEn == null) ? 0 : this.nameEn.hashCode());
        result = prime * result + ((this.nameZh == null) ? 0 : this.nameZh.hashCode());
        result = prime * result + ((this.vehicleCode == null) ? 0 : this.vehicleCode.hashCode());
        result = prime * result + ((this.plateNumber == null) ? 0 : this.plateNumber.hashCode());
        result = prime * result + ((this.fileName == null) ? 0 : this.fileName.hashCode());
        result = prime * result + ((this.fileUrl == null) ? 0 : this.fileUrl.hashCode());
        result = prime * result + ((this.quantity == null) ? 0 : this.quantity.hashCode());
        result = prime * result + ((this.passengers == null) ? 0 : this.passengers.hashCode());
        result = prime * result + ((this.isPublic == null) ? 0 : this.isPublic.hashCode());
        result = prime * result + ((this.created == null) ? 0 : this.created.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.modified == null) ? 0 : this.modified.hashCode());
        result = prime * result + ((this.modifiedBy == null) ? 0 : this.modifiedBy.hashCode());
        result = prime * result + ((this.isActive == null) ? 0 : this.isActive.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Vehicles (");

        sb.append(id);
        sb.append(", ").append(brandId);
        sb.append(", ").append(modelId);
        sb.append(", ").append(nameKh);
        sb.append(", ").append(nameEn);
        sb.append(", ").append(nameZh);
        sb.append(", ").append(vehicleCode);
        sb.append(", ").append(plateNumber);
        sb.append(", ").append(fileName);
        sb.append(", ").append(fileUrl);
        sb.append(", ").append(quantity);
        sb.append(", ").append(passengers);
        sb.append(", ").append(isPublic);
        sb.append(", ").append(created);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(modified);
        sb.append(", ").append(modifiedBy);
        sb.append(", ").append(isActive);

        sb.append(")");
        return sb.toString();
    }
}
