/*
 * This file is generated by jOOQ.
 */
package com.db_access.jooq.tables.pojos;


import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VehicleModels implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long brandId;
    private String name;
    private String description;
    private LocalDateTime created;
    private Long createdBy;
    private LocalDateTime modified;
    private Long modifiedBy;
    private Byte isActive;

    public VehicleModels() {}

    public VehicleModels(VehicleModels value) {
        this.id = value.id;
        this.brandId = value.brandId;
        this.name = value.name;
        this.description = value.description;
        this.created = value.created;
        this.createdBy = value.createdBy;
        this.modified = value.modified;
        this.modifiedBy = value.modifiedBy;
        this.isActive = value.isActive;
    }

    public VehicleModels(
        Long id,
        Long brandId,
        String name,
        String description,
        LocalDateTime created,
        Long createdBy,
        LocalDateTime modified,
        Long modifiedBy,
        Byte isActive
    ) {
        this.id = id;
        this.brandId = brandId;
        this.name = name;
        this.description = description;
        this.created = created;
        this.createdBy = createdBy;
        this.modified = modified;
        this.modifiedBy = modifiedBy;
        this.isActive = isActive;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.vehicle_models.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.vehicle_models.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.vehicle_models.brand_id</code>.
     * References vehicle_brands.id
     */
    @NotNull
    public Long getBrandId() {
        return this.brandId;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.vehicle_models.brand_id</code>.
     * References vehicle_brands.id
     */
    public void setBrandId(Long brandId) {
        this.brandId = brandId;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.vehicle_models.name</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.vehicle_models.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.vehicle_models.description</code>.
     */
    @Size(max = 65535)
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.vehicle_models.description</code>.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.vehicle_models.created</code>.
     */
    @NotNull
    public LocalDateTime getCreated() {
        return this.created;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.vehicle_models.created</code>.
     */
    public void setCreated(LocalDateTime created) {
        this.created = created;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.vehicle_models.created_by</code>.
     */
    public Long getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.vehicle_models.created_by</code>.
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.vehicle_models.modified</code>.
     */
    public LocalDateTime getModified() {
        return this.modified;
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.vehicle_models.modified</code>.
     */
    public void setModified(LocalDateTime modified) {
        this.modified = modified;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.vehicle_models.modified_by</code>.
     */
    public Long getModifiedBy() {
        return this.modifiedBy;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.vehicle_models.modified_by</code>.
     */
    public void setModifiedBy(Long modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.vehicle_models.is_active</code>. 0:
     * Inactive, 1: Active
     */
    public Byte getIsActive() {
        return this.isActive;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.vehicle_models.is_active</code>. 0:
     * Inactive, 1: Active
     */
    public void setIsActive(Byte isActive) {
        this.isActive = isActive;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final VehicleModels other = (VehicleModels) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.brandId == null) {
            if (other.brandId != null)
                return false;
        }
        else if (!this.brandId.equals(other.brandId))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.description == null) {
            if (other.description != null)
                return false;
        }
        else if (!this.description.equals(other.description))
            return false;
        if (this.created == null) {
            if (other.created != null)
                return false;
        }
        else if (!this.created.equals(other.created))
            return false;
        if (this.createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!this.createdBy.equals(other.createdBy))
            return false;
        if (this.modified == null) {
            if (other.modified != null)
                return false;
        }
        else if (!this.modified.equals(other.modified))
            return false;
        if (this.modifiedBy == null) {
            if (other.modifiedBy != null)
                return false;
        }
        else if (!this.modifiedBy.equals(other.modifiedBy))
            return false;
        if (this.isActive == null) {
            if (other.isActive != null)
                return false;
        }
        else if (!this.isActive.equals(other.isActive))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.brandId == null) ? 0 : this.brandId.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.created == null) ? 0 : this.created.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.modified == null) ? 0 : this.modified.hashCode());
        result = prime * result + ((this.modifiedBy == null) ? 0 : this.modifiedBy.hashCode());
        result = prime * result + ((this.isActive == null) ? 0 : this.isActive.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("VehicleModels (");

        sb.append(id);
        sb.append(", ").append(brandId);
        sb.append(", ").append(name);
        sb.append(", ").append(description);
        sb.append(", ").append(created);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(modified);
        sb.append(", ").append(modifiedBy);
        sb.append(", ").append(isActive);

        sb.append(")");
        return sb.toString();
    }
}
