/*
 * This file is generated by jOOQ.
 */
package com.db_access.jooq.tables.pojos;


import jakarta.validation.constraints.NotNull;

import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VehicleRentalTypesMapping implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long vehicleId;
    private Long rentalTypeId;

    public VehicleRentalTypesMapping() {}

    public VehicleRentalTypesMapping(VehicleRentalTypesMapping value) {
        this.vehicleId = value.vehicleId;
        this.rentalTypeId = value.rentalTypeId;
    }

    public VehicleRentalTypesMapping(
        Long vehicleId,
        Long rentalTypeId
    ) {
        this.vehicleId = vehicleId;
        this.rentalTypeId = rentalTypeId;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.vehicle_rental_types_mapping.vehicle_id</code>.
     * References vehicles.id
     */
    @NotNull
    public Long getVehicleId() {
        return this.vehicleId;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.vehicle_rental_types_mapping.vehicle_id</code>.
     * References vehicles.id
     */
    public void setVehicleId(Long vehicleId) {
        this.vehicleId = vehicleId;
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.vehicle_rental_types_mapping.rental_type_id</code>.
     * References vehicle_rental_types.id
     */
    @NotNull
    public Long getRentalTypeId() {
        return this.rentalTypeId;
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.vehicle_rental_types_mapping.rental_type_id</code>.
     * References vehicle_rental_types.id
     */
    public void setRentalTypeId(Long rentalTypeId) {
        this.rentalTypeId = rentalTypeId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final VehicleRentalTypesMapping other = (VehicleRentalTypesMapping) obj;
        if (this.vehicleId == null) {
            if (other.vehicleId != null)
                return false;
        }
        else if (!this.vehicleId.equals(other.vehicleId))
            return false;
        if (this.rentalTypeId == null) {
            if (other.rentalTypeId != null)
                return false;
        }
        else if (!this.rentalTypeId.equals(other.rentalTypeId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.vehicleId == null) ? 0 : this.vehicleId.hashCode());
        result = prime * result + ((this.rentalTypeId == null) ? 0 : this.rentalTypeId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("VehicleRentalTypesMapping (");

        sb.append(vehicleId);
        sb.append(", ").append(rentalTypeId);

        sb.append(")");
        return sb.toString();
    }
}
