/*
 * This file is generated by jOOQ.
 */
package com.db_access.jooq.tables.records;


import com.db_access.jooq.tables.CustomerReviewFiles;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomerReviewFilesRecord extends UpdatableRecordImpl<CustomerReviewFilesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.customer_review_files.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.customer_review_files.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.customer_review_files.review_id</code>.
     * References customer_reviews.id
     */
    public void setReviewId(Long value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.customer_review_files.review_id</code>.
     * References customer_reviews.id
     */
    @NotNull
    public Long getReviewId() {
        return (Long) get(1);
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.customer_review_files.file_name</code>.
     */
    public void setFileName(String value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.customer_review_files.file_name</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getFileName() {
        return (String) get(2);
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.customer_review_files.file_url</code>.
     */
    public void setFileUrl(String value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.customer_review_files.file_url</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getFileUrl() {
        return (String) get(3);
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.customer_review_files.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.customer_review_files.created</code>.
     */
    @NotNull
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CustomerReviewFilesRecord
     */
    public CustomerReviewFilesRecord() {
        super(CustomerReviewFiles.CUSTOMER_REVIEW_FILES);
    }

    /**
     * Create a detached, initialised CustomerReviewFilesRecord
     */
    public CustomerReviewFilesRecord(Long id, Long reviewId, String fileName, String fileUrl, LocalDateTime created) {
        super(CustomerReviewFiles.CUSTOMER_REVIEW_FILES);

        setId(id);
        setReviewId(reviewId);
        setFileName(fileName);
        setFileUrl(fileUrl);
        setCreated(created);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised CustomerReviewFilesRecord
     */
    public CustomerReviewFilesRecord(com.db_access.jooq.tables.pojos.CustomerReviewFiles value) {
        super(CustomerReviewFiles.CUSTOMER_REVIEW_FILES);

        if (value != null) {
            setId(value.getId());
            setReviewId(value.getReviewId());
            setFileName(value.getFileName());
            setFileUrl(value.getFileUrl());
            setCreated(value.getCreated());
            resetChangedOnNotNull();
        }
    }
}
