/*
 * This file is generated by jOOQ.
 */
package com.db_access.jooq.tables.records;


import com.db_access.jooq.tables.ModuleTypesApi;

import jakarta.validation.constraints.Size;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ModuleTypesApiRecord extends UpdatableRecordImpl<ModuleTypesApiRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>1137_VET_Car_RP_Database.module_types_api.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.module_types_api.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.module_types_api.sys_code</code>.
     */
    public void setSysCode(String value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.module_types_api.sys_code</code>.
     */
    @Size(max = 255)
    public String getSysCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.module_types_api.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.module_types_api.name</code>.
     */
    @Size(max = 255)
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.module_types_api.name_other</code>.
     */
    public void setNameOther(String value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.module_types_api.name_other</code>.
     */
    @Size(max = 255)
    public String getNameOther() {
        return (String) get(3);
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.module_types_api.ordering</code>.
     */
    public void setOrdering(Integer value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.module_types_api.ordering</code>.
     */
    public Integer getOrdering() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.module_types_api.status</code>.
     * 0: Disabled; 1: Enable
     */
    public void setStatus(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.module_types_api.status</code>.
     * 0: Disabled; 1: Enable
     */
    public Byte getStatus() {
        return (Byte) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ModuleTypesApiRecord
     */
    public ModuleTypesApiRecord() {
        super(ModuleTypesApi.MODULE_TYPES_API);
    }

    /**
     * Create a detached, initialised ModuleTypesApiRecord
     */
    public ModuleTypesApiRecord(Long id, String sysCode, String name, String nameOther, Integer ordering, Byte status) {
        super(ModuleTypesApi.MODULE_TYPES_API);

        setId(id);
        setSysCode(sysCode);
        setName(name);
        setNameOther(nameOther);
        setOrdering(ordering);
        setStatus(status);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ModuleTypesApiRecord
     */
    public ModuleTypesApiRecord(com.db_access.jooq.tables.pojos.ModuleTypesApi value) {
        super(ModuleTypesApi.MODULE_TYPES_API);

        if (value != null) {
            setId(value.getId());
            setSysCode(value.getSysCode());
            setName(value.getName());
            setNameOther(value.getNameOther());
            setOrdering(value.getOrdering());
            setStatus(value.getStatus());
            resetChangedOnNotNull();
        }
    }
}
