/*
 * This file is generated by jOOQ.
 */
package com.db_access.jooq.tables.records;


import com.db_access.jooq.tables.PermissionsApi;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PermissionsApiRecord extends UpdatableRecordImpl<PermissionsApiRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>1137_VET_Car_RP_Database.permissions_api.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.permissions_api.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.permissions_api.group_id</code>.
     */
    public void setGroupId(Long value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.permissions_api.group_id</code>.
     */
    public Long getGroupId() {
        return (Long) get(1);
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.permissions_api.module_id</code>.
     */
    public void setModuleId(Long value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.permissions_api.module_id</code>.
     */
    public Long getModuleId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PermissionsApiRecord
     */
    public PermissionsApiRecord() {
        super(PermissionsApi.PERMISSIONS_API);
    }

    /**
     * Create a detached, initialised PermissionsApiRecord
     */
    public PermissionsApiRecord(Long id, Long groupId, Long moduleId) {
        super(PermissionsApi.PERMISSIONS_API);

        setId(id);
        setGroupId(groupId);
        setModuleId(moduleId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised PermissionsApiRecord
     */
    public PermissionsApiRecord(com.db_access.jooq.tables.pojos.PermissionsApi value) {
        super(PermissionsApi.PERMISSIONS_API);

        if (value != null) {
            setId(value.getId());
            setGroupId(value.getGroupId());
            setModuleId(value.getModuleId());
            resetChangedOnNotNull();
        }
    }
}
