/*
 * This file is generated by jOOQ.
 */
package com.db_access.jooq.tables.records;


import com.db_access.jooq.tables.SalesOrderTripSubLocations;

import jakarta.validation.constraints.NotNull;

import java.math.BigDecimal;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SalesOrderTripSubLocationsRecord extends UpdatableRecordImpl<SalesOrderTripSubLocationsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.sales_order_trip_sub_locations.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.sales_order_trip_sub_locations.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.sales_order_trip_sub_locations.trip_id</code>.
     * References sales_order_trips.id
     */
    public void setTripId(Long value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.sales_order_trip_sub_locations.trip_id</code>.
     * References sales_order_trips.id
     */
    @NotNull
    public Long getTripId() {
        return (Long) get(1);
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.sales_order_trip_sub_locations.sub_location_id</code>.
     * References sub_locations.id
     */
    public void setSubLocationId(Long value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.sales_order_trip_sub_locations.sub_location_id</code>.
     * References sub_locations.id
     */
    @NotNull
    public Long getSubLocationId() {
        return (Long) get(2);
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.sales_order_trip_sub_locations.price</code>.
     * Snapshot price at time of order
     */
    public void setPrice(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.sales_order_trip_sub_locations.price</code>.
     * Snapshot price at time of order
     */
    public BigDecimal getPrice() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.sales_order_trip_sub_locations.sort_order</code>.
     */
    public void setSortOrder(Integer value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.sales_order_trip_sub_locations.sort_order</code>.
     */
    public Integer getSortOrder() {
        return (Integer) get(4);
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.sales_order_trip_sub_locations.is_active</code>.
     * 0: Inactive, 1: Active
     */
    public void setIsActive(Byte value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.sales_order_trip_sub_locations.is_active</code>.
     * 0: Inactive, 1: Active
     */
    public Byte getIsActive() {
        return (Byte) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SalesOrderTripSubLocationsRecord
     */
    public SalesOrderTripSubLocationsRecord() {
        super(SalesOrderTripSubLocations.SALES_ORDER_TRIP_SUB_LOCATIONS);
    }

    /**
     * Create a detached, initialised SalesOrderTripSubLocationsRecord
     */
    public SalesOrderTripSubLocationsRecord(Long id, Long tripId, Long subLocationId, BigDecimal price, Integer sortOrder, Byte isActive) {
        super(SalesOrderTripSubLocations.SALES_ORDER_TRIP_SUB_LOCATIONS);

        setId(id);
        setTripId(tripId);
        setSubLocationId(subLocationId);
        setPrice(price);
        setSortOrder(sortOrder);
        setIsActive(isActive);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised SalesOrderTripSubLocationsRecord
     */
    public SalesOrderTripSubLocationsRecord(com.db_access.jooq.tables.pojos.SalesOrderTripSubLocations value) {
        super(SalesOrderTripSubLocations.SALES_ORDER_TRIP_SUB_LOCATIONS);

        if (value != null) {
            setId(value.getId());
            setTripId(value.getTripId());
            setSubLocationId(value.getSubLocationId());
            setPrice(value.getPrice());
            setSortOrder(value.getSortOrder());
            setIsActive(value.getIsActive());
            resetChangedOnNotNull();
        }
    }
}
