/*
 * This file is generated by jOOQ.
 */
package com.db_access.jooq.tables.records;


import com.db_access.jooq.tables.UsersApi;

import jakarta.validation.constraints.Size;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersApiRecord extends UpdatableRecordImpl<UsersApiRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>1137_VET_Car_RP_Database.users_api.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.users_api.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.users_api.is_super_admin</code>. 0: false,
     * 1: true
     */
    public void setIsSuperAdmin(Byte value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.users_api.is_super_admin</code>. 0: false,
     * 1: true
     */
    public Byte getIsSuperAdmin() {
        return (Byte) get(1);
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.users_api.first_name</code>.
     */
    public void setFirstName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.users_api.first_name</code>.
     */
    @Size(max = 50)
    public String getFirstName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.users_api.last_name</code>.
     */
    public void setLastName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.users_api.last_name</code>.
     */
    @Size(max = 50)
    public String getLastName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.users_api.full_name</code>.
     */
    public void setFullName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.users_api.full_name</code>.
     */
    @Size(max = 50)
    public String getFullName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.users_api.username</code>.
     */
    public void setUsername(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.users_api.username</code>.
     */
    @Size(max = 50)
    public String getUsername() {
        return (String) get(5);
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.users_api.password</code>.
     */
    public void setPassword(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.users_api.password</code>.
     */
    @Size(max = 255)
    public String getPassword() {
        return (String) get(6);
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.users_api.photo</code>.
     */
    public void setPhoto(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.users_api.photo</code>.
     */
    @Size(max = 255)
    public String getPhoto() {
        return (String) get(7);
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.users_api.signature</code>.
     */
    public void setSignature(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.users_api.signature</code>.
     */
    @Size(max = 255)
    public String getSignature() {
        return (String) get(8);
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.users_api.phone_verify_token</code>.
     */
    public void setPhoneVerifyToken(String value) {
        set(9, value);
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.users_api.phone_verify_token</code>.
     */
    @Size(max = 255)
    public String getPhoneVerifyToken() {
        return (String) get(9);
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.users_api.session_id</code>.
     */
    public void setSessionId(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.users_api.session_id</code>.
     */
    @Size(max = 150)
    public String getSessionId() {
        return (String) get(10);
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.users_api.session_start</code>.
     */
    public void setSessionStart(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.users_api.session_start</code>.
     */
    public LocalDateTime getSessionStart() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.users_api.session_active</code>.
     */
    public void setSessionActive(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.users_api.session_active</code>.
     */
    public LocalDateTime getSessionActive() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.users_api.session_lat</code>.
     */
    public void setSessionLat(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.users_api.session_lat</code>.
     */
    @Size(max = 50)
    public String getSessionLat() {
        return (String) get(13);
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.users_api.session_long</code>.
     */
    public void setSessionLong(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.users_api.session_long</code>.
     */
    @Size(max = 50)
    public String getSessionLong() {
        return (String) get(14);
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.users_api.login_attempt_remote_ip</code>.
     */
    public void setLoginAttemptRemoteIp(String value) {
        set(15, value);
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.users_api.login_attempt_remote_ip</code>.
     */
    @Size(max = 50)
    public String getLoginAttemptRemoteIp() {
        return (String) get(15);
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.users_api.login_attempt_http_user_agent</code>.
     */
    public void setLoginAttemptHttpUserAgent(String value) {
        set(16, value);
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.users_api.login_attempt_http_user_agent</code>.
     */
    @Size(max = 50)
    public String getLoginAttemptHttpUserAgent() {
        return (String) get(16);
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.users_api.status_login</code>.
     * 1. never; 2. Ever login
     */
    public void setStatusLogin(Byte value) {
        set(17, value);
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.users_api.status_login</code>.
     * 1. never; 2. Ever login
     */
    public Byte getStatusLogin() {
        return (Byte) get(17);
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.users_api.created_by</code>.
     */
    public void setCreatedBy(Long value) {
        set(18, value);
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.users_api.created_by</code>.
     */
    public Long getCreatedBy() {
        return (Long) get(18);
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.users_api.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(19, value);
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.users_api.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(19);
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.users_api.modified</code>.
     */
    public void setModified(LocalDateTime value) {
        set(20, value);
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.users_api.modified</code>.
     */
    public LocalDateTime getModified() {
        return (LocalDateTime) get(20);
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.users_api.modified_by</code>.
     */
    public void setModifiedBy(Long value) {
        set(21, value);
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.users_api.modified_by</code>.
     */
    public Long getModifiedBy() {
        return (Long) get(21);
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.users_api.is_active</code>. 1:
     * Pending; 2: Active
     */
    public void setIsActive(Byte value) {
        set(22, value);
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.users_api.is_active</code>. 1:
     * Pending; 2: Active
     */
    public Byte getIsActive() {
        return (Byte) get(22);
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.users_api.refresh_token</code>.
     */
    public void setRefreshToken(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.users_api.refresh_token</code>.
     */
    @Size(max = 65535)
    public String getRefreshToken() {
        return (String) get(23);
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.users_api.refresh_token_expiration</code>.
     */
    public void setRefreshTokenExpiration(LocalDateTime value) {
        set(24, value);
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.users_api.refresh_token_expiration</code>.
     */
    public LocalDateTime getRefreshTokenExpiration() {
        return (LocalDateTime) get(24);
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.users_api.device_id</code>.
     */
    public void setDeviceId(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.users_api.device_id</code>.
     */
    @Size(max = 255)
    public String getDeviceId() {
        return (String) get(25);
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.users_api.device_name</code>.
     */
    public void setDeviceName(String value) {
        set(26, value);
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.users_api.device_name</code>.
     */
    @Size(max = 255)
    public String getDeviceName() {
        return (String) get(26);
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.users_api.push_token</code>.
     */
    public void setPushToken(String value) {
        set(27, value);
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.users_api.push_token</code>.
     */
    @Size(max = 65535)
    public String getPushToken() {
        return (String) get(27);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersApiRecord
     */
    public UsersApiRecord() {
        super(UsersApi.USERS_API);
    }

    /**
     * Create a detached, initialised UsersApiRecord
     */
    public UsersApiRecord(Long id, Byte isSuperAdmin, String firstName, String lastName, String fullName, String username, String password, String photo, String signature, String phoneVerifyToken, String sessionId, LocalDateTime sessionStart, LocalDateTime sessionActive, String sessionLat, String sessionLong, String loginAttemptRemoteIp, String loginAttemptHttpUserAgent, Byte statusLogin, Long createdBy, LocalDateTime created, LocalDateTime modified, Long modifiedBy, Byte isActive, String refreshToken, LocalDateTime refreshTokenExpiration, String deviceId, String deviceName, String pushToken) {
        super(UsersApi.USERS_API);

        setId(id);
        setIsSuperAdmin(isSuperAdmin);
        setFirstName(firstName);
        setLastName(lastName);
        setFullName(fullName);
        setUsername(username);
        setPassword(password);
        setPhoto(photo);
        setSignature(signature);
        setPhoneVerifyToken(phoneVerifyToken);
        setSessionId(sessionId);
        setSessionStart(sessionStart);
        setSessionActive(sessionActive);
        setSessionLat(sessionLat);
        setSessionLong(sessionLong);
        setLoginAttemptRemoteIp(loginAttemptRemoteIp);
        setLoginAttemptHttpUserAgent(loginAttemptHttpUserAgent);
        setStatusLogin(statusLogin);
        setCreatedBy(createdBy);
        setCreated(created);
        setModified(modified);
        setModifiedBy(modifiedBy);
        setIsActive(isActive);
        setRefreshToken(refreshToken);
        setRefreshTokenExpiration(refreshTokenExpiration);
        setDeviceId(deviceId);
        setDeviceName(deviceName);
        setPushToken(pushToken);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised UsersApiRecord
     */
    public UsersApiRecord(com.db_access.jooq.tables.pojos.UsersApi value) {
        super(UsersApi.USERS_API);

        if (value != null) {
            setId(value.getId());
            setIsSuperAdmin(value.getIsSuperAdmin());
            setFirstName(value.getFirstName());
            setLastName(value.getLastName());
            setFullName(value.getFullName());
            setUsername(value.getUsername());
            setPassword(value.getPassword());
            setPhoto(value.getPhoto());
            setSignature(value.getSignature());
            setPhoneVerifyToken(value.getPhoneVerifyToken());
            setSessionId(value.getSessionId());
            setSessionStart(value.getSessionStart());
            setSessionActive(value.getSessionActive());
            setSessionLat(value.getSessionLat());
            setSessionLong(value.getSessionLong());
            setLoginAttemptRemoteIp(value.getLoginAttemptRemoteIp());
            setLoginAttemptHttpUserAgent(value.getLoginAttemptHttpUserAgent());
            setStatusLogin(value.getStatusLogin());
            setCreatedBy(value.getCreatedBy());
            setCreated(value.getCreated());
            setModified(value.getModified());
            setModifiedBy(value.getModifiedBy());
            setIsActive(value.getIsActive());
            setRefreshToken(value.getRefreshToken());
            setRefreshTokenExpiration(value.getRefreshTokenExpiration());
            setDeviceId(value.getDeviceId());
            setDeviceName(value.getDeviceName());
            setPushToken(value.getPushToken());
            resetChangedOnNotNull();
        }
    }
}
