/*
 * This file is generated by jOOQ.
 */
package com.db_access.jooq.tables.records;


import com.db_access.jooq.tables.VehicleRentalTypes;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VehicleRentalTypesRecord extends UpdatableRecordImpl<VehicleRentalTypesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>1137_VET_Car_RP_Database.vehicle_rental_types.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.vehicle_rental_types.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.vehicle_rental_types.category_id</code>.
     * References vehicle_categories.id
     */
    public void setCategoryId(Long value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.vehicle_rental_types.category_id</code>.
     * References vehicle_categories.id
     */
    @NotNull
    public Long getCategoryId() {
        return (Long) get(1);
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.vehicle_rental_types.name_kh</code>.
     */
    public void setNameKh(String value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.vehicle_rental_types.name_kh</code>.
     */
    @Size(max = 255)
    public String getNameKh() {
        return (String) get(2);
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.vehicle_rental_types.name_en</code>.
     */
    public void setNameEn(String value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.vehicle_rental_types.name_en</code>.
     */
    @Size(max = 255)
    public String getNameEn() {
        return (String) get(3);
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.vehicle_rental_types.name_zh</code>.
     */
    public void setNameZh(String value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.vehicle_rental_types.name_zh</code>.
     */
    @Size(max = 255)
    public String getNameZh() {
        return (String) get(4);
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.vehicle_rental_types.google_map_url</code>.
     */
    public void setGoogleMapUrl(String value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.vehicle_rental_types.google_map_url</code>.
     */
    @Size(max = 500)
    public String getGoogleMapUrl() {
        return (String) get(5);
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.vehicle_rental_types.description_kh</code>.
     */
    public void setDescriptionKh(String value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.vehicle_rental_types.description_kh</code>.
     */
    @Size(max = 65535)
    public String getDescriptionKh() {
        return (String) get(6);
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.vehicle_rental_types.description_en</code>.
     */
    public void setDescriptionEn(String value) {
        set(7, value);
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.vehicle_rental_types.description_en</code>.
     */
    @Size(max = 65535)
    public String getDescriptionEn() {
        return (String) get(7);
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.vehicle_rental_types.description_zh</code>.
     */
    public void setDescriptionZh(String value) {
        set(8, value);
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.vehicle_rental_types.description_zh</code>.
     */
    @Size(max = 65535)
    public String getDescriptionZh() {
        return (String) get(8);
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.vehicle_rental_types.file_name</code>.
     */
    public void setFileName(String value) {
        set(9, value);
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.vehicle_rental_types.file_name</code>.
     */
    @Size(max = 255)
    public String getFileName() {
        return (String) get(9);
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.vehicle_rental_types.file_url</code>.
     */
    public void setFileUrl(String value) {
        set(10, value);
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.vehicle_rental_types.file_url</code>.
     */
    @Size(max = 255)
    public String getFileUrl() {
        return (String) get(10);
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.vehicle_rental_types.sort_order</code>.
     */
    public void setSortOrder(Integer value) {
        set(11, value);
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.vehicle_rental_types.sort_order</code>.
     */
    public Integer getSortOrder() {
        return (Integer) get(11);
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.vehicle_rental_types.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.vehicle_rental_types.created</code>.
     */
    @NotNull
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.vehicle_rental_types.created_by</code>.
     */
    public void setCreatedBy(Long value) {
        set(13, value);
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.vehicle_rental_types.created_by</code>.
     */
    public Long getCreatedBy() {
        return (Long) get(13);
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.vehicle_rental_types.modified</code>.
     */
    public void setModified(LocalDateTime value) {
        set(14, value);
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.vehicle_rental_types.modified</code>.
     */
    public LocalDateTime getModified() {
        return (LocalDateTime) get(14);
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.vehicle_rental_types.modified_by</code>.
     */
    public void setModifiedBy(Long value) {
        set(15, value);
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.vehicle_rental_types.modified_by</code>.
     */
    public Long getModifiedBy() {
        return (Long) get(15);
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.vehicle_rental_types.is_active</code>. 0:
     * Inactive, 1: Active
     */
    public void setIsActive(Byte value) {
        set(16, value);
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.vehicle_rental_types.is_active</code>. 0:
     * Inactive, 1: Active
     */
    public Byte getIsActive() {
        return (Byte) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VehicleRentalTypesRecord
     */
    public VehicleRentalTypesRecord() {
        super(VehicleRentalTypes.VEHICLE_RENTAL_TYPES);
    }

    /**
     * Create a detached, initialised VehicleRentalTypesRecord
     */
    public VehicleRentalTypesRecord(Long id, Long categoryId, String nameKh, String nameEn, String nameZh, String googleMapUrl, String descriptionKh, String descriptionEn, String descriptionZh, String fileName, String fileUrl, Integer sortOrder, LocalDateTime created, Long createdBy, LocalDateTime modified, Long modifiedBy, Byte isActive) {
        super(VehicleRentalTypes.VEHICLE_RENTAL_TYPES);

        setId(id);
        setCategoryId(categoryId);
        setNameKh(nameKh);
        setNameEn(nameEn);
        setNameZh(nameZh);
        setGoogleMapUrl(googleMapUrl);
        setDescriptionKh(descriptionKh);
        setDescriptionEn(descriptionEn);
        setDescriptionZh(descriptionZh);
        setFileName(fileName);
        setFileUrl(fileUrl);
        setSortOrder(sortOrder);
        setCreated(created);
        setCreatedBy(createdBy);
        setModified(modified);
        setModifiedBy(modifiedBy);
        setIsActive(isActive);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised VehicleRentalTypesRecord
     */
    public VehicleRentalTypesRecord(com.db_access.jooq.tables.pojos.VehicleRentalTypes value) {
        super(VehicleRentalTypes.VEHICLE_RENTAL_TYPES);

        if (value != null) {
            setId(value.getId());
            setCategoryId(value.getCategoryId());
            setNameKh(value.getNameKh());
            setNameEn(value.getNameEn());
            setNameZh(value.getNameZh());
            setGoogleMapUrl(value.getGoogleMapUrl());
            setDescriptionKh(value.getDescriptionKh());
            setDescriptionEn(value.getDescriptionEn());
            setDescriptionZh(value.getDescriptionZh());
            setFileName(value.getFileName());
            setFileUrl(value.getFileUrl());
            setSortOrder(value.getSortOrder());
            setCreated(value.getCreated());
            setCreatedBy(value.getCreatedBy());
            setModified(value.getModified());
            setModifiedBy(value.getModifiedBy());
            setIsActive(value.getIsActive());
            resetChangedOnNotNull();
        }
    }
}
