/*
 * This file is generated by jOOQ.
 */
package com.db_access.jooq.tables.records;


import com.db_access.jooq.tables.VehicleModels;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VehicleModelsRecord extends UpdatableRecordImpl<VehicleModelsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>1137_VET_Car_RP_Database.vehicle_models.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.vehicle_models.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.vehicle_models.brand_id</code>.
     * References vehicle_brands.id
     */
    public void setBrandId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.vehicle_models.brand_id</code>.
     * References vehicle_brands.id
     */
    @NotNull
    public Long getBrandId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.vehicle_models.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.vehicle_models.name</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.vehicle_models.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.vehicle_models.description</code>.
     */
    @Size(max = 65535)
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.vehicle_models.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.vehicle_models.created</code>.
     */
    @NotNull
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.vehicle_models.created_by</code>.
     */
    public void setCreatedBy(Long value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.vehicle_models.created_by</code>.
     */
    public Long getCreatedBy() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.vehicle_models.modified</code>.
     */
    public void setModified(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.vehicle_models.modified</code>.
     */
    public LocalDateTime getModified() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.vehicle_models.modified_by</code>.
     */
    public void setModifiedBy(Long value) {
        set(7, value);
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.vehicle_models.modified_by</code>.
     */
    public Long getModifiedBy() {
        return (Long) get(7);
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.vehicle_models.is_active</code>. 0:
     * Inactive, 1: Active
     */
    public void setIsActive(Byte value) {
        set(8, value);
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.vehicle_models.is_active</code>. 0:
     * Inactive, 1: Active
     */
    public Byte getIsActive() {
        return (Byte) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VehicleModelsRecord
     */
    public VehicleModelsRecord() {
        super(VehicleModels.VEHICLE_MODELS);
    }

    /**
     * Create a detached, initialised VehicleModelsRecord
     */
    public VehicleModelsRecord(Long id, Long brandId, String name, String description, LocalDateTime created, Long createdBy, LocalDateTime modified, Long modifiedBy, Byte isActive) {
        super(VehicleModels.VEHICLE_MODELS);

        setId(id);
        setBrandId(brandId);
        setName(name);
        setDescription(description);
        setCreated(created);
        setCreatedBy(createdBy);
        setModified(modified);
        setModifiedBy(modifiedBy);
        setIsActive(isActive);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised VehicleModelsRecord
     */
    public VehicleModelsRecord(com.db_access.jooq.tables.pojos.VehicleModels value) {
        super(VehicleModels.VEHICLE_MODELS);

        if (value != null) {
            setId(value.getId());
            setBrandId(value.getBrandId());
            setName(value.getName());
            setDescription(value.getDescription());
            setCreated(value.getCreated());
            setCreatedBy(value.getCreatedBy());
            setModified(value.getModified());
            setModifiedBy(value.getModifiedBy());
            setIsActive(value.getIsActive());
            resetChangedOnNotNull();
        }
    }
}
