/*
 * This file is generated by jOOQ.
 */
package com.db_access.jooq.tables.records;


import com.db_access.jooq.tables.VehicleSlides;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VehicleSlidesRecord extends UpdatableRecordImpl<VehicleSlidesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>1137_VET_Car_RP_Database.vehicle_slides.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.vehicle_slides.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.vehicle_slides.vehicle_id</code>.
     * References vehicles.id
     */
    public void setVehicleId(Long value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.vehicle_slides.vehicle_id</code>.
     * References vehicles.id
     */
    @NotNull
    public Long getVehicleId() {
        return (Long) get(1);
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.vehicle_slides.file_name</code>.
     */
    public void setFileName(String value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.vehicle_slides.file_name</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getFileName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>1137_VET_Car_RP_Database.vehicle_slides.file_url</code>.
     */
    public void setFileUrl(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>1137_VET_Car_RP_Database.vehicle_slides.file_url</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getFileUrl() {
        return (String) get(3);
    }

    /**
     * Setter for
     * <code>1137_VET_Car_RP_Database.vehicle_slides.sort_order</code>.
     */
    public void setSortOrder(Integer value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>1137_VET_Car_RP_Database.vehicle_slides.sort_order</code>.
     */
    public Integer getSortOrder() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VehicleSlidesRecord
     */
    public VehicleSlidesRecord() {
        super(VehicleSlides.VEHICLE_SLIDES);
    }

    /**
     * Create a detached, initialised VehicleSlidesRecord
     */
    public VehicleSlidesRecord(Long id, Long vehicleId, String fileName, String fileUrl, Integer sortOrder) {
        super(VehicleSlides.VEHICLE_SLIDES);

        setId(id);
        setVehicleId(vehicleId);
        setFileName(fileName);
        setFileUrl(fileUrl);
        setSortOrder(sortOrder);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised VehicleSlidesRecord
     */
    public VehicleSlidesRecord(com.db_access.jooq.tables.pojos.VehicleSlides value) {
        super(VehicleSlides.VEHICLE_SLIDES);

        if (value != null) {
            setId(value.getId());
            setVehicleId(value.getVehicleId());
            setFileName(value.getFileName());
            setFileUrl(value.getFileUrl());
            setSortOrder(value.getSortOrder());
            resetChangedOnNotNull();
        }
    }
}
