/*
 * This file is generated by jOOQ.
 */
package com.db_access.jooq.tables.daos;


import com.db_access.jooq.tables.Customers;
import com.db_access.jooq.tables.records.CustomersRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class CustomersDao extends DAOImpl<CustomersRecord, com.db_access.jooq.tables.pojos.Customers, Long> {

    /**
     * Create a new CustomersDao without any configuration
     */
    public CustomersDao() {
        super(Customers.CUSTOMERS, com.db_access.jooq.tables.pojos.Customers.class);
    }

    /**
     * Create a new CustomersDao with an attached configuration
     */
    @Autowired
    public CustomersDao(Configuration configuration) {
        super(Customers.CUSTOMERS, com.db_access.jooq.tables.pojos.Customers.class, configuration);
    }

    @Override
    public Long getId(com.db_access.jooq.tables.pojos.Customers object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.Customers> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Customers.CUSTOMERS.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.Customers> fetchById(Long... values) {
        return fetch(Customers.CUSTOMERS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.db_access.jooq.tables.pojos.Customers fetchOneById(Long value) {
        return fetchOne(Customers.CUSTOMERS.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.db_access.jooq.tables.pojos.Customers> fetchOptionalById(Long value) {
        return fetchOptional(Customers.CUSTOMERS.ID, value);
    }

    /**
     * Fetch records that have <code>full_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.Customers> fetchRangeOfFullName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Customers.CUSTOMERS.FULL_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>full_name IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.Customers> fetchByFullName(String... values) {
        return fetch(Customers.CUSTOMERS.FULL_NAME, values);
    }

    /**
     * Fetch records that have <code>phone_number BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.Customers> fetchRangeOfPhoneNumber(String lowerInclusive, String upperInclusive) {
        return fetchRange(Customers.CUSTOMERS.PHONE_NUMBER, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>phone_number IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.Customers> fetchByPhoneNumber(String... values) {
        return fetch(Customers.CUSTOMERS.PHONE_NUMBER, values);
    }

    /**
     * Fetch a unique record that has <code>phone_number = value</code>
     */
    public com.db_access.jooq.tables.pojos.Customers fetchOneByPhoneNumber(String value) {
        return fetchOne(Customers.CUSTOMERS.PHONE_NUMBER, value);
    }

    /**
     * Fetch a unique record that has <code>phone_number = value</code>
     */
    public Optional<com.db_access.jooq.tables.pojos.Customers> fetchOptionalByPhoneNumber(String value) {
        return fetchOptional(Customers.CUSTOMERS.PHONE_NUMBER, value);
    }

    /**
     * Fetch records that have <code>email BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.Customers> fetchRangeOfEmail(String lowerInclusive, String upperInclusive) {
        return fetchRange(Customers.CUSTOMERS.EMAIL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>email IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.Customers> fetchByEmail(String... values) {
        return fetch(Customers.CUSTOMERS.EMAIL, values);
    }

    /**
     * Fetch records that have <code>password BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.Customers> fetchRangeOfPassword(String lowerInclusive, String upperInclusive) {
        return fetchRange(Customers.CUSTOMERS.PASSWORD, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>password IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.Customers> fetchByPassword(String... values) {
        return fetch(Customers.CUSTOMERS.PASSWORD, values);
    }

    /**
     * Fetch records that have <code>file_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.Customers> fetchRangeOfFileName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Customers.CUSTOMERS.FILE_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>file_name IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.Customers> fetchByFileName(String... values) {
        return fetch(Customers.CUSTOMERS.FILE_NAME, values);
    }

    /**
     * Fetch records that have <code>file_url BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.Customers> fetchRangeOfFileUrl(String lowerInclusive, String upperInclusive) {
        return fetchRange(Customers.CUSTOMERS.FILE_URL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>file_url IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.Customers> fetchByFileUrl(String... values) {
        return fetch(Customers.CUSTOMERS.FILE_URL, values);
    }

    /**
     * Fetch records that have <code>is_verified BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.Customers> fetchRangeOfIsVerified(Byte lowerInclusive, Byte upperInclusive) {
        return fetchRange(Customers.CUSTOMERS.IS_VERIFIED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>is_verified IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.Customers> fetchByIsVerified(Byte... values) {
        return fetch(Customers.CUSTOMERS.IS_VERIFIED, values);
    }

    /**
     * Fetch records that have <code>os_type BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.Customers> fetchRangeOfOsType(Byte lowerInclusive, Byte upperInclusive) {
        return fetchRange(Customers.CUSTOMERS.OS_TYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>os_type IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.Customers> fetchByOsType(Byte... values) {
        return fetch(Customers.CUSTOMERS.OS_TYPE, values);
    }

    /**
     * Fetch records that have <code>language BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.Customers> fetchRangeOfLanguage(Byte lowerInclusive, Byte upperInclusive) {
        return fetchRange(Customers.CUSTOMERS.LANGUAGE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>language IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.Customers> fetchByLanguage(Byte... values) {
        return fetch(Customers.CUSTOMERS.LANGUAGE, values);
    }

    /**
     * Fetch records that have <code>device_token BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.Customers> fetchRangeOfDeviceToken(String lowerInclusive, String upperInclusive) {
        return fetchRange(Customers.CUSTOMERS.DEVICE_TOKEN, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>device_token IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.Customers> fetchByDeviceToken(String... values) {
        return fetch(Customers.CUSTOMERS.DEVICE_TOKEN, values);
    }

    /**
     * Fetch records that have <code>last_login BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.Customers> fetchRangeOfLastLogin(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Customers.CUSTOMERS.LAST_LOGIN, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>last_login IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.Customers> fetchByLastLogin(LocalDateTime... values) {
        return fetch(Customers.CUSTOMERS.LAST_LOGIN, values);
    }

    /**
     * Fetch records that have <code>created BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.Customers> fetchRangeOfCreated(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Customers.CUSTOMERS.CREATED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.Customers> fetchByCreated(LocalDateTime... values) {
        return fetch(Customers.CUSTOMERS.CREATED, values);
    }

    /**
     * Fetch records that have <code>modified BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.Customers> fetchRangeOfModified(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Customers.CUSTOMERS.MODIFIED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>modified IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.Customers> fetchByModified(LocalDateTime... values) {
        return fetch(Customers.CUSTOMERS.MODIFIED, values);
    }

    /**
     * Fetch records that have <code>is_active BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.Customers> fetchRangeOfIsActive(Byte lowerInclusive, Byte upperInclusive) {
        return fetchRange(Customers.CUSTOMERS.IS_ACTIVE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>is_active IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.Customers> fetchByIsActive(Byte... values) {
        return fetch(Customers.CUSTOMERS.IS_ACTIVE, values);
    }
}
