/*
 * This file is generated by jOOQ.
 */
package com.db_access.jooq.tables.daos;


import com.db_access.jooq.tables.CustomerReviewFiles;
import com.db_access.jooq.tables.records.CustomerReviewFilesRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class CustomerReviewFilesDao extends DAOImpl<CustomerReviewFilesRecord, com.db_access.jooq.tables.pojos.CustomerReviewFiles, Long> {

    /**
     * Create a new CustomerReviewFilesDao without any configuration
     */
    public CustomerReviewFilesDao() {
        super(CustomerReviewFiles.CUSTOMER_REVIEW_FILES, com.db_access.jooq.tables.pojos.CustomerReviewFiles.class);
    }

    /**
     * Create a new CustomerReviewFilesDao with an attached configuration
     */
    @Autowired
    public CustomerReviewFilesDao(Configuration configuration) {
        super(CustomerReviewFiles.CUSTOMER_REVIEW_FILES, com.db_access.jooq.tables.pojos.CustomerReviewFiles.class, configuration);
    }

    @Override
    public Long getId(com.db_access.jooq.tables.pojos.CustomerReviewFiles object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.CustomerReviewFiles> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(CustomerReviewFiles.CUSTOMER_REVIEW_FILES.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.CustomerReviewFiles> fetchById(Long... values) {
        return fetch(CustomerReviewFiles.CUSTOMER_REVIEW_FILES.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.db_access.jooq.tables.pojos.CustomerReviewFiles fetchOneById(Long value) {
        return fetchOne(CustomerReviewFiles.CUSTOMER_REVIEW_FILES.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.db_access.jooq.tables.pojos.CustomerReviewFiles> fetchOptionalById(Long value) {
        return fetchOptional(CustomerReviewFiles.CUSTOMER_REVIEW_FILES.ID, value);
    }

    /**
     * Fetch records that have <code>review_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.CustomerReviewFiles> fetchRangeOfReviewId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(CustomerReviewFiles.CUSTOMER_REVIEW_FILES.REVIEW_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>review_id IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.CustomerReviewFiles> fetchByReviewId(Long... values) {
        return fetch(CustomerReviewFiles.CUSTOMER_REVIEW_FILES.REVIEW_ID, values);
    }

    /**
     * Fetch records that have <code>file_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.CustomerReviewFiles> fetchRangeOfFileName(String lowerInclusive, String upperInclusive) {
        return fetchRange(CustomerReviewFiles.CUSTOMER_REVIEW_FILES.FILE_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>file_name IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.CustomerReviewFiles> fetchByFileName(String... values) {
        return fetch(CustomerReviewFiles.CUSTOMER_REVIEW_FILES.FILE_NAME, values);
    }

    /**
     * Fetch records that have <code>file_url BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.CustomerReviewFiles> fetchRangeOfFileUrl(String lowerInclusive, String upperInclusive) {
        return fetchRange(CustomerReviewFiles.CUSTOMER_REVIEW_FILES.FILE_URL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>file_url IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.CustomerReviewFiles> fetchByFileUrl(String... values) {
        return fetch(CustomerReviewFiles.CUSTOMER_REVIEW_FILES.FILE_URL, values);
    }

    /**
     * Fetch records that have <code>created BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.CustomerReviewFiles> fetchRangeOfCreated(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(CustomerReviewFiles.CUSTOMER_REVIEW_FILES.CREATED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.CustomerReviewFiles> fetchByCreated(LocalDateTime... values) {
        return fetch(CustomerReviewFiles.CUSTOMER_REVIEW_FILES.CREATED, values);
    }
}
