/*
 * This file is generated by jOOQ.
 */
package com.db_access.jooq.tables.daos;


import com.db_access.jooq.tables.Nationalities;
import com.db_access.jooq.tables.records.NationalitiesRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class NationalitiesDao extends DAOImpl<NationalitiesRecord, com.db_access.jooq.tables.pojos.Nationalities, Long> {

    /**
     * Create a new NationalitiesDao without any configuration
     */
    public NationalitiesDao() {
        super(Nationalities.NATIONALITIES, com.db_access.jooq.tables.pojos.Nationalities.class);
    }

    /**
     * Create a new NationalitiesDao with an attached configuration
     */
    @Autowired
    public NationalitiesDao(Configuration configuration) {
        super(Nationalities.NATIONALITIES, com.db_access.jooq.tables.pojos.Nationalities.class, configuration);
    }

    @Override
    public Long getId(com.db_access.jooq.tables.pojos.Nationalities object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.Nationalities> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Nationalities.NATIONALITIES.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.Nationalities> fetchById(Long... values) {
        return fetch(Nationalities.NATIONALITIES.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.db_access.jooq.tables.pojos.Nationalities fetchOneById(Long value) {
        return fetchOne(Nationalities.NATIONALITIES.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.db_access.jooq.tables.pojos.Nationalities> fetchOptionalById(Long value) {
        return fetchOptional(Nationalities.NATIONALITIES.ID, value);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.Nationalities> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Nationalities.NATIONALITIES.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.Nationalities> fetchByName(String... values) {
        return fetch(Nationalities.NATIONALITIES.NAME, values);
    }

    /**
     * Fetch records that have <code>description BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.Nationalities> fetchRangeOfDescription(String lowerInclusive, String upperInclusive) {
        return fetchRange(Nationalities.NATIONALITIES.DESCRIPTION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.Nationalities> fetchByDescription(String... values) {
        return fetch(Nationalities.NATIONALITIES.DESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>created BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.Nationalities> fetchRangeOfCreated(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Nationalities.NATIONALITIES.CREATED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.Nationalities> fetchByCreated(LocalDateTime... values) {
        return fetch(Nationalities.NATIONALITIES.CREATED, values);
    }

    /**
     * Fetch records that have <code>created_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.Nationalities> fetchRangeOfCreatedBy(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Nationalities.NATIONALITIES.CREATED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_by IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.Nationalities> fetchByCreatedBy(Long... values) {
        return fetch(Nationalities.NATIONALITIES.CREATED_BY, values);
    }

    /**
     * Fetch records that have <code>modified BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.Nationalities> fetchRangeOfModified(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Nationalities.NATIONALITIES.MODIFIED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>modified IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.Nationalities> fetchByModified(LocalDateTime... values) {
        return fetch(Nationalities.NATIONALITIES.MODIFIED, values);
    }

    /**
     * Fetch records that have <code>modified_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.Nationalities> fetchRangeOfModifiedBy(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Nationalities.NATIONALITIES.MODIFIED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>modified_by IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.Nationalities> fetchByModifiedBy(Long... values) {
        return fetch(Nationalities.NATIONALITIES.MODIFIED_BY, values);
    }

    /**
     * Fetch records that have <code>is_active BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.Nationalities> fetchRangeOfIsActive(Byte lowerInclusive, Byte upperInclusive) {
        return fetchRange(Nationalities.NATIONALITIES.IS_ACTIVE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>is_active IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.Nationalities> fetchByIsActive(Byte... values) {
        return fetch(Nationalities.NATIONALITIES.IS_ACTIVE, values);
    }
}
