/*
 * This file is generated by jOOQ.
 */
package com.db_access.jooq.tables.daos;


import com.db_access.jooq.tables.PermissionsApi;
import com.db_access.jooq.tables.records.PermissionsApiRecord;

import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class PermissionsApiDao extends DAOImpl<PermissionsApiRecord, com.db_access.jooq.tables.pojos.PermissionsApi, Long> {

    /**
     * Create a new PermissionsApiDao without any configuration
     */
    public PermissionsApiDao() {
        super(PermissionsApi.PERMISSIONS_API, com.db_access.jooq.tables.pojos.PermissionsApi.class);
    }

    /**
     * Create a new PermissionsApiDao with an attached configuration
     */
    @Autowired
    public PermissionsApiDao(Configuration configuration) {
        super(PermissionsApi.PERMISSIONS_API, com.db_access.jooq.tables.pojos.PermissionsApi.class, configuration);
    }

    @Override
    public Long getId(com.db_access.jooq.tables.pojos.PermissionsApi object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.PermissionsApi> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(PermissionsApi.PERMISSIONS_API.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.PermissionsApi> fetchById(Long... values) {
        return fetch(PermissionsApi.PERMISSIONS_API.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.db_access.jooq.tables.pojos.PermissionsApi fetchOneById(Long value) {
        return fetchOne(PermissionsApi.PERMISSIONS_API.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.db_access.jooq.tables.pojos.PermissionsApi> fetchOptionalById(Long value) {
        return fetchOptional(PermissionsApi.PERMISSIONS_API.ID, value);
    }

    /**
     * Fetch records that have <code>group_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.PermissionsApi> fetchRangeOfGroupId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(PermissionsApi.PERMISSIONS_API.GROUP_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>group_id IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.PermissionsApi> fetchByGroupId(Long... values) {
        return fetch(PermissionsApi.PERMISSIONS_API.GROUP_ID, values);
    }

    /**
     * Fetch records that have <code>module_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.PermissionsApi> fetchRangeOfModuleId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(PermissionsApi.PERMISSIONS_API.MODULE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>module_id IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.PermissionsApi> fetchByModuleId(Long... values) {
        return fetch(PermissionsApi.PERMISSIONS_API.MODULE_ID, values);
    }
}
