/*
 * This file is generated by jOOQ.
 */
package com.db_access.jooq.tables.daos;


import com.db_access.jooq.tables.PrivacyTerms;
import com.db_access.jooq.tables.records.PrivacyTermsRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class PrivacyTermsDao extends DAOImpl<PrivacyTermsRecord, com.db_access.jooq.tables.pojos.PrivacyTerms, Long> {

    /**
     * Create a new PrivacyTermsDao without any configuration
     */
    public PrivacyTermsDao() {
        super(PrivacyTerms.PRIVACY_TERMS, com.db_access.jooq.tables.pojos.PrivacyTerms.class);
    }

    /**
     * Create a new PrivacyTermsDao with an attached configuration
     */
    @Autowired
    public PrivacyTermsDao(Configuration configuration) {
        super(PrivacyTerms.PRIVACY_TERMS, com.db_access.jooq.tables.pojos.PrivacyTerms.class, configuration);
    }

    @Override
    public Long getId(com.db_access.jooq.tables.pojos.PrivacyTerms object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.PrivacyTerms> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(PrivacyTerms.PRIVACY_TERMS.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.PrivacyTerms> fetchById(Long... values) {
        return fetch(PrivacyTerms.PRIVACY_TERMS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.db_access.jooq.tables.pojos.PrivacyTerms fetchOneById(Long value) {
        return fetchOne(PrivacyTerms.PRIVACY_TERMS.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.db_access.jooq.tables.pojos.PrivacyTerms> fetchOptionalById(Long value) {
        return fetchOptional(PrivacyTerms.PRIVACY_TERMS.ID, value);
    }

    /**
     * Fetch records that have <code>type BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.PrivacyTerms> fetchRangeOfType(Byte lowerInclusive, Byte upperInclusive) {
        return fetchRange(PrivacyTerms.PRIVACY_TERMS.TYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.PrivacyTerms> fetchByType(Byte... values) {
        return fetch(PrivacyTerms.PRIVACY_TERMS.TYPE, values);
    }

    /**
     * Fetch records that have <code>description_kh BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.PrivacyTerms> fetchRangeOfDescriptionKh(String lowerInclusive, String upperInclusive) {
        return fetchRange(PrivacyTerms.PRIVACY_TERMS.DESCRIPTION_KH, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>description_kh IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.PrivacyTerms> fetchByDescriptionKh(String... values) {
        return fetch(PrivacyTerms.PRIVACY_TERMS.DESCRIPTION_KH, values);
    }

    /**
     * Fetch records that have <code>description_en BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.PrivacyTerms> fetchRangeOfDescriptionEn(String lowerInclusive, String upperInclusive) {
        return fetchRange(PrivacyTerms.PRIVACY_TERMS.DESCRIPTION_EN, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>description_en IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.PrivacyTerms> fetchByDescriptionEn(String... values) {
        return fetch(PrivacyTerms.PRIVACY_TERMS.DESCRIPTION_EN, values);
    }

    /**
     * Fetch records that have <code>description_zh BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.PrivacyTerms> fetchRangeOfDescriptionZh(String lowerInclusive, String upperInclusive) {
        return fetchRange(PrivacyTerms.PRIVACY_TERMS.DESCRIPTION_ZH, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>description_zh IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.PrivacyTerms> fetchByDescriptionZh(String... values) {
        return fetch(PrivacyTerms.PRIVACY_TERMS.DESCRIPTION_ZH, values);
    }

    /**
     * Fetch records that have <code>created BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.PrivacyTerms> fetchRangeOfCreated(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(PrivacyTerms.PRIVACY_TERMS.CREATED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.PrivacyTerms> fetchByCreated(LocalDateTime... values) {
        return fetch(PrivacyTerms.PRIVACY_TERMS.CREATED, values);
    }

    /**
     * Fetch records that have <code>created_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.PrivacyTerms> fetchRangeOfCreatedBy(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(PrivacyTerms.PRIVACY_TERMS.CREATED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_by IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.PrivacyTerms> fetchByCreatedBy(Long... values) {
        return fetch(PrivacyTerms.PRIVACY_TERMS.CREATED_BY, values);
    }

    /**
     * Fetch records that have <code>modified BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.PrivacyTerms> fetchRangeOfModified(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(PrivacyTerms.PRIVACY_TERMS.MODIFIED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>modified IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.PrivacyTerms> fetchByModified(LocalDateTime... values) {
        return fetch(PrivacyTerms.PRIVACY_TERMS.MODIFIED, values);
    }

    /**
     * Fetch records that have <code>modified_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.PrivacyTerms> fetchRangeOfModifiedBy(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(PrivacyTerms.PRIVACY_TERMS.MODIFIED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>modified_by IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.PrivacyTerms> fetchByModifiedBy(Long... values) {
        return fetch(PrivacyTerms.PRIVACY_TERMS.MODIFIED_BY, values);
    }

    /**
     * Fetch records that have <code>is_active BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.PrivacyTerms> fetchRangeOfIsActive(Byte lowerInclusive, Byte upperInclusive) {
        return fetchRange(PrivacyTerms.PRIVACY_TERMS.IS_ACTIVE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>is_active IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.PrivacyTerms> fetchByIsActive(Byte... values) {
        return fetch(PrivacyTerms.PRIVACY_TERMS.IS_ACTIVE, values);
    }
}
