/*
 * This file is generated by jOOQ.
 */
package com.db_access.jooq.tables.daos;


import com.db_access.jooq.tables.Provinces;
import com.db_access.jooq.tables.records.ProvincesRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class ProvincesDao extends DAOImpl<ProvincesRecord, com.db_access.jooq.tables.pojos.Provinces, Long> {

    /**
     * Create a new ProvincesDao without any configuration
     */
    public ProvincesDao() {
        super(Provinces.PROVINCES, com.db_access.jooq.tables.pojos.Provinces.class);
    }

    /**
     * Create a new ProvincesDao with an attached configuration
     */
    @Autowired
    public ProvincesDao(Configuration configuration) {
        super(Provinces.PROVINCES, com.db_access.jooq.tables.pojos.Provinces.class, configuration);
    }

    @Override
    public Long getId(com.db_access.jooq.tables.pojos.Provinces object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.Provinces> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Provinces.PROVINCES.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.Provinces> fetchById(Long... values) {
        return fetch(Provinces.PROVINCES.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.db_access.jooq.tables.pojos.Provinces fetchOneById(Long value) {
        return fetchOne(Provinces.PROVINCES.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.db_access.jooq.tables.pojos.Provinces> fetchOptionalById(Long value) {
        return fetchOptional(Provinces.PROVINCES.ID, value);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.Provinces> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Provinces.PROVINCES.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.Provinces> fetchByName(String... values) {
        return fetch(Provinces.PROVINCES.NAME, values);
    }

    /**
     * Fetch records that have <code>google_map_url BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.Provinces> fetchRangeOfGoogleMapUrl(String lowerInclusive, String upperInclusive) {
        return fetchRange(Provinces.PROVINCES.GOOGLE_MAP_URL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>google_map_url IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.Provinces> fetchByGoogleMapUrl(String... values) {
        return fetch(Provinces.PROVINCES.GOOGLE_MAP_URL, values);
    }

    /**
     * Fetch records that have <code>description BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.Provinces> fetchRangeOfDescription(String lowerInclusive, String upperInclusive) {
        return fetchRange(Provinces.PROVINCES.DESCRIPTION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.Provinces> fetchByDescription(String... values) {
        return fetch(Provinces.PROVINCES.DESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>created BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.Provinces> fetchRangeOfCreated(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Provinces.PROVINCES.CREATED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.Provinces> fetchByCreated(LocalDateTime... values) {
        return fetch(Provinces.PROVINCES.CREATED, values);
    }

    /**
     * Fetch records that have <code>created_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.Provinces> fetchRangeOfCreatedBy(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Provinces.PROVINCES.CREATED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_by IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.Provinces> fetchByCreatedBy(Long... values) {
        return fetch(Provinces.PROVINCES.CREATED_BY, values);
    }

    /**
     * Fetch records that have <code>modified BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.Provinces> fetchRangeOfModified(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Provinces.PROVINCES.MODIFIED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>modified IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.Provinces> fetchByModified(LocalDateTime... values) {
        return fetch(Provinces.PROVINCES.MODIFIED, values);
    }

    /**
     * Fetch records that have <code>modified_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.Provinces> fetchRangeOfModifiedBy(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Provinces.PROVINCES.MODIFIED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>modified_by IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.Provinces> fetchByModifiedBy(Long... values) {
        return fetch(Provinces.PROVINCES.MODIFIED_BY, values);
    }

    /**
     * Fetch records that have <code>is_active BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.Provinces> fetchRangeOfIsActive(Byte lowerInclusive, Byte upperInclusive) {
        return fetchRange(Provinces.PROVINCES.IS_ACTIVE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>is_active IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.Provinces> fetchByIsActive(Byte... values) {
        return fetch(Provinces.PROVINCES.IS_ACTIVE, values);
    }
}
