/*
 * This file is generated by jOOQ.
 */
package com.db_access.jooq.tables.daos;


import com.db_access.jooq.tables.SalesOrderTripSubLocations;
import com.db_access.jooq.tables.records.SalesOrderTripSubLocationsRecord;

import java.math.BigDecimal;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class SalesOrderTripSubLocationsDao extends DAOImpl<SalesOrderTripSubLocationsRecord, com.db_access.jooq.tables.pojos.SalesOrderTripSubLocations, Long> {

    /**
     * Create a new SalesOrderTripSubLocationsDao without any configuration
     */
    public SalesOrderTripSubLocationsDao() {
        super(SalesOrderTripSubLocations.SALES_ORDER_TRIP_SUB_LOCATIONS, com.db_access.jooq.tables.pojos.SalesOrderTripSubLocations.class);
    }

    /**
     * Create a new SalesOrderTripSubLocationsDao with an attached configuration
     */
    @Autowired
    public SalesOrderTripSubLocationsDao(Configuration configuration) {
        super(SalesOrderTripSubLocations.SALES_ORDER_TRIP_SUB_LOCATIONS, com.db_access.jooq.tables.pojos.SalesOrderTripSubLocations.class, configuration);
    }

    @Override
    public Long getId(com.db_access.jooq.tables.pojos.SalesOrderTripSubLocations object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.SalesOrderTripSubLocations> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(SalesOrderTripSubLocations.SALES_ORDER_TRIP_SUB_LOCATIONS.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.SalesOrderTripSubLocations> fetchById(Long... values) {
        return fetch(SalesOrderTripSubLocations.SALES_ORDER_TRIP_SUB_LOCATIONS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.db_access.jooq.tables.pojos.SalesOrderTripSubLocations fetchOneById(Long value) {
        return fetchOne(SalesOrderTripSubLocations.SALES_ORDER_TRIP_SUB_LOCATIONS.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.db_access.jooq.tables.pojos.SalesOrderTripSubLocations> fetchOptionalById(Long value) {
        return fetchOptional(SalesOrderTripSubLocations.SALES_ORDER_TRIP_SUB_LOCATIONS.ID, value);
    }

    /**
     * Fetch records that have <code>trip_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.SalesOrderTripSubLocations> fetchRangeOfTripId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(SalesOrderTripSubLocations.SALES_ORDER_TRIP_SUB_LOCATIONS.TRIP_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>trip_id IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.SalesOrderTripSubLocations> fetchByTripId(Long... values) {
        return fetch(SalesOrderTripSubLocations.SALES_ORDER_TRIP_SUB_LOCATIONS.TRIP_ID, values);
    }

    /**
     * Fetch records that have <code>sub_location_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.SalesOrderTripSubLocations> fetchRangeOfSubLocationId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(SalesOrderTripSubLocations.SALES_ORDER_TRIP_SUB_LOCATIONS.SUB_LOCATION_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>sub_location_id IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.SalesOrderTripSubLocations> fetchBySubLocationId(Long... values) {
        return fetch(SalesOrderTripSubLocations.SALES_ORDER_TRIP_SUB_LOCATIONS.SUB_LOCATION_ID, values);
    }

    /**
     * Fetch records that have <code>price BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.SalesOrderTripSubLocations> fetchRangeOfPrice(BigDecimal lowerInclusive, BigDecimal upperInclusive) {
        return fetchRange(SalesOrderTripSubLocations.SALES_ORDER_TRIP_SUB_LOCATIONS.PRICE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>price IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.SalesOrderTripSubLocations> fetchByPrice(BigDecimal... values) {
        return fetch(SalesOrderTripSubLocations.SALES_ORDER_TRIP_SUB_LOCATIONS.PRICE, values);
    }

    /**
     * Fetch records that have <code>sort_order BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.SalesOrderTripSubLocations> fetchRangeOfSortOrder(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(SalesOrderTripSubLocations.SALES_ORDER_TRIP_SUB_LOCATIONS.SORT_ORDER, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>sort_order IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.SalesOrderTripSubLocations> fetchBySortOrder(Integer... values) {
        return fetch(SalesOrderTripSubLocations.SALES_ORDER_TRIP_SUB_LOCATIONS.SORT_ORDER, values);
    }

    /**
     * Fetch records that have <code>is_active BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.SalesOrderTripSubLocations> fetchRangeOfIsActive(Byte lowerInclusive, Byte upperInclusive) {
        return fetchRange(SalesOrderTripSubLocations.SALES_ORDER_TRIP_SUB_LOCATIONS.IS_ACTIVE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>is_active IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.SalesOrderTripSubLocations> fetchByIsActive(Byte... values) {
        return fetch(SalesOrderTripSubLocations.SALES_ORDER_TRIP_SUB_LOCATIONS.IS_ACTIVE, values);
    }
}
