/*
 * This file is generated by jOOQ.
 */
package com.db_access.jooq.tables.daos;


import com.db_access.jooq.tables.SystemActivitiesApi;
import com.db_access.jooq.tables.records.SystemActivitiesApiRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class SystemActivitiesApiDao extends DAOImpl<SystemActivitiesApiRecord, com.db_access.jooq.tables.pojos.SystemActivitiesApi, Long> {

    /**
     * Create a new SystemActivitiesApiDao without any configuration
     */
    public SystemActivitiesApiDao() {
        super(SystemActivitiesApi.SYSTEM_ACTIVITIES_API, com.db_access.jooq.tables.pojos.SystemActivitiesApi.class);
    }

    /**
     * Create a new SystemActivitiesApiDao with an attached configuration
     */
    @Autowired
    public SystemActivitiesApiDao(Configuration configuration) {
        super(SystemActivitiesApi.SYSTEM_ACTIVITIES_API, com.db_access.jooq.tables.pojos.SystemActivitiesApi.class, configuration);
    }

    @Override
    public Long getId(com.db_access.jooq.tables.pojos.SystemActivitiesApi object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.SystemActivitiesApi> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(SystemActivitiesApi.SYSTEM_ACTIVITIES_API.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.SystemActivitiesApi> fetchById(Long... values) {
        return fetch(SystemActivitiesApi.SYSTEM_ACTIVITIES_API.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.db_access.jooq.tables.pojos.SystemActivitiesApi fetchOneById(Long value) {
        return fetchOne(SystemActivitiesApi.SYSTEM_ACTIVITIES_API.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.db_access.jooq.tables.pojos.SystemActivitiesApi> fetchOptionalById(Long value) {
        return fetchOptional(SystemActivitiesApi.SYSTEM_ACTIVITIES_API.ID, value);
    }

    /**
     * Fetch records that have <code>endpoint BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.SystemActivitiesApi> fetchRangeOfEndpoint(String lowerInclusive, String upperInclusive) {
        return fetchRange(SystemActivitiesApi.SYSTEM_ACTIVITIES_API.ENDPOINT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>endpoint IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.SystemActivitiesApi> fetchByEndpoint(String... values) {
        return fetch(SystemActivitiesApi.SYSTEM_ACTIVITIES_API.ENDPOINT, values);
    }

    /**
     * Fetch records that have <code>module BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.SystemActivitiesApi> fetchRangeOfModule(String lowerInclusive, String upperInclusive) {
        return fetchRange(SystemActivitiesApi.SYSTEM_ACTIVITIES_API.MODULE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>module IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.SystemActivitiesApi> fetchByModule(String... values) {
        return fetch(SystemActivitiesApi.SYSTEM_ACTIVITIES_API.MODULE, values);
    }

    /**
     * Fetch records that have <code>module_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.SystemActivitiesApi> fetchRangeOfModuleId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(SystemActivitiesApi.SYSTEM_ACTIVITIES_API.MODULE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>module_id IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.SystemActivitiesApi> fetchByModuleId(Long... values) {
        return fetch(SystemActivitiesApi.SYSTEM_ACTIVITIES_API.MODULE_ID, values);
    }

    /**
     * Fetch records that have <code>act BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.SystemActivitiesApi> fetchRangeOfAct(String lowerInclusive, String upperInclusive) {
        return fetchRange(SystemActivitiesApi.SYSTEM_ACTIVITIES_API.ACT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>act IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.SystemActivitiesApi> fetchByAct(String... values) {
        return fetch(SystemActivitiesApi.SYSTEM_ACTIVITIES_API.ACT, values);
    }

    /**
     * Fetch records that have <code>description BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.SystemActivitiesApi> fetchRangeOfDescription(String lowerInclusive, String upperInclusive) {
        return fetchRange(SystemActivitiesApi.SYSTEM_ACTIVITIES_API.DESCRIPTION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.SystemActivitiesApi> fetchByDescription(String... values) {
        return fetch(SystemActivitiesApi.SYSTEM_ACTIVITIES_API.DESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>bug BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.SystemActivitiesApi> fetchRangeOfBug(String lowerInclusive, String upperInclusive) {
        return fetchRange(SystemActivitiesApi.SYSTEM_ACTIVITIES_API.BUG, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>bug IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.SystemActivitiesApi> fetchByBug(String... values) {
        return fetch(SystemActivitiesApi.SYSTEM_ACTIVITIES_API.BUG, values);
    }

    /**
     * Fetch records that have <code>line_code BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.SystemActivitiesApi> fetchRangeOfLineCode(String lowerInclusive, String upperInclusive) {
        return fetchRange(SystemActivitiesApi.SYSTEM_ACTIVITIES_API.LINE_CODE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>line_code IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.SystemActivitiesApi> fetchByLineCode(String... values) {
        return fetch(SystemActivitiesApi.SYSTEM_ACTIVITIES_API.LINE_CODE, values);
    }

    /**
     * Fetch records that have <code>browser BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.SystemActivitiesApi> fetchRangeOfBrowser(String lowerInclusive, String upperInclusive) {
        return fetchRange(SystemActivitiesApi.SYSTEM_ACTIVITIES_API.BROWSER, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>browser IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.SystemActivitiesApi> fetchByBrowser(String... values) {
        return fetch(SystemActivitiesApi.SYSTEM_ACTIVITIES_API.BROWSER, values);
    }

    /**
     * Fetch records that have <code>operating_system BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.SystemActivitiesApi> fetchRangeOfOperatingSystem(String lowerInclusive, String upperInclusive) {
        return fetchRange(SystemActivitiesApi.SYSTEM_ACTIVITIES_API.OPERATING_SYSTEM, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>operating_system IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.SystemActivitiesApi> fetchByOperatingSystem(String... values) {
        return fetch(SystemActivitiesApi.SYSTEM_ACTIVITIES_API.OPERATING_SYSTEM, values);
    }

    /**
     * Fetch records that have <code>ip BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.SystemActivitiesApi> fetchRangeOfIp(String lowerInclusive, String upperInclusive) {
        return fetchRange(SystemActivitiesApi.SYSTEM_ACTIVITIES_API.IP, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>ip IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.SystemActivitiesApi> fetchByIp(String... values) {
        return fetch(SystemActivitiesApi.SYSTEM_ACTIVITIES_API.IP, values);
    }

    /**
     * Fetch records that have <code>host_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.SystemActivitiesApi> fetchRangeOfHostName(String lowerInclusive, String upperInclusive) {
        return fetchRange(SystemActivitiesApi.SYSTEM_ACTIVITIES_API.HOST_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>host_name IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.SystemActivitiesApi> fetchByHostName(String... values) {
        return fetch(SystemActivitiesApi.SYSTEM_ACTIVITIES_API.HOST_NAME, values);
    }

    /**
     * Fetch records that have <code>duration BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.SystemActivitiesApi> fetchRangeOfDuration(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(SystemActivitiesApi.SYSTEM_ACTIVITIES_API.DURATION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>duration IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.SystemActivitiesApi> fetchByDuration(Integer... values) {
        return fetch(SystemActivitiesApi.SYSTEM_ACTIVITIES_API.DURATION, values);
    }

    /**
     * Fetch records that have <code>created BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.SystemActivitiesApi> fetchRangeOfCreated(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(SystemActivitiesApi.SYSTEM_ACTIVITIES_API.CREATED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.SystemActivitiesApi> fetchByCreated(LocalDateTime... values) {
        return fetch(SystemActivitiesApi.SYSTEM_ACTIVITIES_API.CREATED, values);
    }

    /**
     * Fetch records that have <code>created_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.SystemActivitiesApi> fetchRangeOfCreatedBy(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(SystemActivitiesApi.SYSTEM_ACTIVITIES_API.CREATED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_by IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.SystemActivitiesApi> fetchByCreatedBy(Long... values) {
        return fetch(SystemActivitiesApi.SYSTEM_ACTIVITIES_API.CREATED_BY, values);
    }

    /**
     * Fetch records that have <code>status BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.SystemActivitiesApi> fetchRangeOfStatus(Byte lowerInclusive, Byte upperInclusive) {
        return fetchRange(SystemActivitiesApi.SYSTEM_ACTIVITIES_API.STATUS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.SystemActivitiesApi> fetchByStatus(Byte... values) {
        return fetch(SystemActivitiesApi.SYSTEM_ACTIVITIES_API.STATUS, values);
    }
}
