/*
 * This file is generated by jOOQ.
 */
package com.db_access.jooq.tables.daos;


import com.db_access.jooq.tables.UserGroupsApi;
import com.db_access.jooq.tables.records.UserGroupsApiRecord;

import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class UserGroupsApiDao extends DAOImpl<UserGroupsApiRecord, com.db_access.jooq.tables.pojos.UserGroupsApi, Long> {

    /**
     * Create a new UserGroupsApiDao without any configuration
     */
    public UserGroupsApiDao() {
        super(UserGroupsApi.USER_GROUPS_API, com.db_access.jooq.tables.pojos.UserGroupsApi.class);
    }

    /**
     * Create a new UserGroupsApiDao with an attached configuration
     */
    @Autowired
    public UserGroupsApiDao(Configuration configuration) {
        super(UserGroupsApi.USER_GROUPS_API, com.db_access.jooq.tables.pojos.UserGroupsApi.class, configuration);
    }

    @Override
    public Long getId(com.db_access.jooq.tables.pojos.UserGroupsApi object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.UserGroupsApi> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(UserGroupsApi.USER_GROUPS_API.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.UserGroupsApi> fetchById(Long... values) {
        return fetch(UserGroupsApi.USER_GROUPS_API.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.db_access.jooq.tables.pojos.UserGroupsApi fetchOneById(Long value) {
        return fetchOne(UserGroupsApi.USER_GROUPS_API.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.db_access.jooq.tables.pojos.UserGroupsApi> fetchOptionalById(Long value) {
        return fetchOptional(UserGroupsApi.USER_GROUPS_API.ID, value);
    }

    /**
     * Fetch records that have <code>user_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.UserGroupsApi> fetchRangeOfUserId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(UserGroupsApi.USER_GROUPS_API.USER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.UserGroupsApi> fetchByUserId(Long... values) {
        return fetch(UserGroupsApi.USER_GROUPS_API.USER_ID, values);
    }

    /**
     * Fetch records that have <code>group_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.UserGroupsApi> fetchRangeOfGroupId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(UserGroupsApi.USER_GROUPS_API.GROUP_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>group_id IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.UserGroupsApi> fetchByGroupId(Long... values) {
        return fetch(UserGroupsApi.USER_GROUPS_API.GROUP_ID, values);
    }
}
