/*
 * This file is generated by jOOQ.
 */
package com.db_access.jooq.tables.daos;


import com.db_access.jooq.tables.VehicleBrands;
import com.db_access.jooq.tables.records.VehicleBrandsRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class VehicleBrandsDao extends DAOImpl<VehicleBrandsRecord, com.db_access.jooq.tables.pojos.VehicleBrands, Long> {

    /**
     * Create a new VehicleBrandsDao without any configuration
     */
    public VehicleBrandsDao() {
        super(VehicleBrands.VEHICLE_BRANDS, com.db_access.jooq.tables.pojos.VehicleBrands.class);
    }

    /**
     * Create a new VehicleBrandsDao with an attached configuration
     */
    @Autowired
    public VehicleBrandsDao(Configuration configuration) {
        super(VehicleBrands.VEHICLE_BRANDS, com.db_access.jooq.tables.pojos.VehicleBrands.class, configuration);
    }

    @Override
    public Long getId(com.db_access.jooq.tables.pojos.VehicleBrands object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleBrands> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(VehicleBrands.VEHICLE_BRANDS.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleBrands> fetchById(Long... values) {
        return fetch(VehicleBrands.VEHICLE_BRANDS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.db_access.jooq.tables.pojos.VehicleBrands fetchOneById(Long value) {
        return fetchOne(VehicleBrands.VEHICLE_BRANDS.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.db_access.jooq.tables.pojos.VehicleBrands> fetchOptionalById(Long value) {
        return fetchOptional(VehicleBrands.VEHICLE_BRANDS.ID, value);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleBrands> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(VehicleBrands.VEHICLE_BRANDS.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleBrands> fetchByName(String... values) {
        return fetch(VehicleBrands.VEHICLE_BRANDS.NAME, values);
    }

    /**
     * Fetch records that have <code>description BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleBrands> fetchRangeOfDescription(String lowerInclusive, String upperInclusive) {
        return fetchRange(VehicleBrands.VEHICLE_BRANDS.DESCRIPTION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleBrands> fetchByDescription(String... values) {
        return fetch(VehicleBrands.VEHICLE_BRANDS.DESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>file_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleBrands> fetchRangeOfFileName(String lowerInclusive, String upperInclusive) {
        return fetchRange(VehicleBrands.VEHICLE_BRANDS.FILE_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>file_name IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleBrands> fetchByFileName(String... values) {
        return fetch(VehicleBrands.VEHICLE_BRANDS.FILE_NAME, values);
    }

    /**
     * Fetch records that have <code>file_url BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleBrands> fetchRangeOfFileUrl(String lowerInclusive, String upperInclusive) {
        return fetchRange(VehicleBrands.VEHICLE_BRANDS.FILE_URL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>file_url IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleBrands> fetchByFileUrl(String... values) {
        return fetch(VehicleBrands.VEHICLE_BRANDS.FILE_URL, values);
    }

    /**
     * Fetch records that have <code>sort_order BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleBrands> fetchRangeOfSortOrder(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(VehicleBrands.VEHICLE_BRANDS.SORT_ORDER, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>sort_order IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleBrands> fetchBySortOrder(Integer... values) {
        return fetch(VehicleBrands.VEHICLE_BRANDS.SORT_ORDER, values);
    }

    /**
     * Fetch records that have <code>created BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleBrands> fetchRangeOfCreated(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(VehicleBrands.VEHICLE_BRANDS.CREATED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleBrands> fetchByCreated(LocalDateTime... values) {
        return fetch(VehicleBrands.VEHICLE_BRANDS.CREATED, values);
    }

    /**
     * Fetch records that have <code>created_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleBrands> fetchRangeOfCreatedBy(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(VehicleBrands.VEHICLE_BRANDS.CREATED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_by IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleBrands> fetchByCreatedBy(Long... values) {
        return fetch(VehicleBrands.VEHICLE_BRANDS.CREATED_BY, values);
    }

    /**
     * Fetch records that have <code>modified BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleBrands> fetchRangeOfModified(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(VehicleBrands.VEHICLE_BRANDS.MODIFIED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>modified IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleBrands> fetchByModified(LocalDateTime... values) {
        return fetch(VehicleBrands.VEHICLE_BRANDS.MODIFIED, values);
    }

    /**
     * Fetch records that have <code>modified_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleBrands> fetchRangeOfModifiedBy(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(VehicleBrands.VEHICLE_BRANDS.MODIFIED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>modified_by IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleBrands> fetchByModifiedBy(Long... values) {
        return fetch(VehicleBrands.VEHICLE_BRANDS.MODIFIED_BY, values);
    }

    /**
     * Fetch records that have <code>is_active BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleBrands> fetchRangeOfIsActive(Byte lowerInclusive, Byte upperInclusive) {
        return fetchRange(VehicleBrands.VEHICLE_BRANDS.IS_ACTIVE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>is_active IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleBrands> fetchByIsActive(Byte... values) {
        return fetch(VehicleBrands.VEHICLE_BRANDS.IS_ACTIVE, values);
    }
}
