/*
 * This file is generated by jOOQ.
 */
package com.db_access.jooq.tables.daos;


import com.db_access.jooq.tables.VehicleRentalTypes;
import com.db_access.jooq.tables.records.VehicleRentalTypesRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class VehicleRentalTypesDao extends DAOImpl<VehicleRentalTypesRecord, com.db_access.jooq.tables.pojos.VehicleRentalTypes, Long> {

    /**
     * Create a new VehicleRentalTypesDao without any configuration
     */
    public VehicleRentalTypesDao() {
        super(VehicleRentalTypes.VEHICLE_RENTAL_TYPES, com.db_access.jooq.tables.pojos.VehicleRentalTypes.class);
    }

    /**
     * Create a new VehicleRentalTypesDao with an attached configuration
     */
    @Autowired
    public VehicleRentalTypesDao(Configuration configuration) {
        super(VehicleRentalTypes.VEHICLE_RENTAL_TYPES, com.db_access.jooq.tables.pojos.VehicleRentalTypes.class, configuration);
    }

    @Override
    public Long getId(com.db_access.jooq.tables.pojos.VehicleRentalTypes object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleRentalTypes> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(VehicleRentalTypes.VEHICLE_RENTAL_TYPES.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleRentalTypes> fetchById(Long... values) {
        return fetch(VehicleRentalTypes.VEHICLE_RENTAL_TYPES.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.db_access.jooq.tables.pojos.VehicleRentalTypes fetchOneById(Long value) {
        return fetchOne(VehicleRentalTypes.VEHICLE_RENTAL_TYPES.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.db_access.jooq.tables.pojos.VehicleRentalTypes> fetchOptionalById(Long value) {
        return fetchOptional(VehicleRentalTypes.VEHICLE_RENTAL_TYPES.ID, value);
    }

    /**
     * Fetch records that have <code>category_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleRentalTypes> fetchRangeOfCategoryId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(VehicleRentalTypes.VEHICLE_RENTAL_TYPES.CATEGORY_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>category_id IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleRentalTypes> fetchByCategoryId(Long... values) {
        return fetch(VehicleRentalTypes.VEHICLE_RENTAL_TYPES.CATEGORY_ID, values);
    }

    /**
     * Fetch records that have <code>name_kh BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleRentalTypes> fetchRangeOfNameKh(String lowerInclusive, String upperInclusive) {
        return fetchRange(VehicleRentalTypes.VEHICLE_RENTAL_TYPES.NAME_KH, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name_kh IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleRentalTypes> fetchByNameKh(String... values) {
        return fetch(VehicleRentalTypes.VEHICLE_RENTAL_TYPES.NAME_KH, values);
    }

    /**
     * Fetch records that have <code>name_en BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleRentalTypes> fetchRangeOfNameEn(String lowerInclusive, String upperInclusive) {
        return fetchRange(VehicleRentalTypes.VEHICLE_RENTAL_TYPES.NAME_EN, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name_en IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleRentalTypes> fetchByNameEn(String... values) {
        return fetch(VehicleRentalTypes.VEHICLE_RENTAL_TYPES.NAME_EN, values);
    }

    /**
     * Fetch records that have <code>name_zh BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleRentalTypes> fetchRangeOfNameZh(String lowerInclusive, String upperInclusive) {
        return fetchRange(VehicleRentalTypes.VEHICLE_RENTAL_TYPES.NAME_ZH, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name_zh IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleRentalTypes> fetchByNameZh(String... values) {
        return fetch(VehicleRentalTypes.VEHICLE_RENTAL_TYPES.NAME_ZH, values);
    }

    /**
     * Fetch records that have <code>google_map_url BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleRentalTypes> fetchRangeOfGoogleMapUrl(String lowerInclusive, String upperInclusive) {
        return fetchRange(VehicleRentalTypes.VEHICLE_RENTAL_TYPES.GOOGLE_MAP_URL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>google_map_url IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleRentalTypes> fetchByGoogleMapUrl(String... values) {
        return fetch(VehicleRentalTypes.VEHICLE_RENTAL_TYPES.GOOGLE_MAP_URL, values);
    }

    /**
     * Fetch records that have <code>description_kh BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleRentalTypes> fetchRangeOfDescriptionKh(String lowerInclusive, String upperInclusive) {
        return fetchRange(VehicleRentalTypes.VEHICLE_RENTAL_TYPES.DESCRIPTION_KH, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>description_kh IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleRentalTypes> fetchByDescriptionKh(String... values) {
        return fetch(VehicleRentalTypes.VEHICLE_RENTAL_TYPES.DESCRIPTION_KH, values);
    }

    /**
     * Fetch records that have <code>description_en BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleRentalTypes> fetchRangeOfDescriptionEn(String lowerInclusive, String upperInclusive) {
        return fetchRange(VehicleRentalTypes.VEHICLE_RENTAL_TYPES.DESCRIPTION_EN, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>description_en IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleRentalTypes> fetchByDescriptionEn(String... values) {
        return fetch(VehicleRentalTypes.VEHICLE_RENTAL_TYPES.DESCRIPTION_EN, values);
    }

    /**
     * Fetch records that have <code>description_zh BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleRentalTypes> fetchRangeOfDescriptionZh(String lowerInclusive, String upperInclusive) {
        return fetchRange(VehicleRentalTypes.VEHICLE_RENTAL_TYPES.DESCRIPTION_ZH, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>description_zh IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleRentalTypes> fetchByDescriptionZh(String... values) {
        return fetch(VehicleRentalTypes.VEHICLE_RENTAL_TYPES.DESCRIPTION_ZH, values);
    }

    /**
     * Fetch records that have <code>file_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleRentalTypes> fetchRangeOfFileName(String lowerInclusive, String upperInclusive) {
        return fetchRange(VehicleRentalTypes.VEHICLE_RENTAL_TYPES.FILE_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>file_name IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleRentalTypes> fetchByFileName(String... values) {
        return fetch(VehicleRentalTypes.VEHICLE_RENTAL_TYPES.FILE_NAME, values);
    }

    /**
     * Fetch records that have <code>file_url BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleRentalTypes> fetchRangeOfFileUrl(String lowerInclusive, String upperInclusive) {
        return fetchRange(VehicleRentalTypes.VEHICLE_RENTAL_TYPES.FILE_URL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>file_url IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleRentalTypes> fetchByFileUrl(String... values) {
        return fetch(VehicleRentalTypes.VEHICLE_RENTAL_TYPES.FILE_URL, values);
    }

    /**
     * Fetch records that have <code>sort_order BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleRentalTypes> fetchRangeOfSortOrder(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(VehicleRentalTypes.VEHICLE_RENTAL_TYPES.SORT_ORDER, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>sort_order IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleRentalTypes> fetchBySortOrder(Integer... values) {
        return fetch(VehicleRentalTypes.VEHICLE_RENTAL_TYPES.SORT_ORDER, values);
    }

    /**
     * Fetch records that have <code>created BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleRentalTypes> fetchRangeOfCreated(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(VehicleRentalTypes.VEHICLE_RENTAL_TYPES.CREATED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleRentalTypes> fetchByCreated(LocalDateTime... values) {
        return fetch(VehicleRentalTypes.VEHICLE_RENTAL_TYPES.CREATED, values);
    }

    /**
     * Fetch records that have <code>created_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleRentalTypes> fetchRangeOfCreatedBy(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(VehicleRentalTypes.VEHICLE_RENTAL_TYPES.CREATED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_by IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleRentalTypes> fetchByCreatedBy(Long... values) {
        return fetch(VehicleRentalTypes.VEHICLE_RENTAL_TYPES.CREATED_BY, values);
    }

    /**
     * Fetch records that have <code>modified BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleRentalTypes> fetchRangeOfModified(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(VehicleRentalTypes.VEHICLE_RENTAL_TYPES.MODIFIED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>modified IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleRentalTypes> fetchByModified(LocalDateTime... values) {
        return fetch(VehicleRentalTypes.VEHICLE_RENTAL_TYPES.MODIFIED, values);
    }

    /**
     * Fetch records that have <code>modified_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleRentalTypes> fetchRangeOfModifiedBy(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(VehicleRentalTypes.VEHICLE_RENTAL_TYPES.MODIFIED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>modified_by IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleRentalTypes> fetchByModifiedBy(Long... values) {
        return fetch(VehicleRentalTypes.VEHICLE_RENTAL_TYPES.MODIFIED_BY, values);
    }

    /**
     * Fetch records that have <code>is_active BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleRentalTypes> fetchRangeOfIsActive(Byte lowerInclusive, Byte upperInclusive) {
        return fetchRange(VehicleRentalTypes.VEHICLE_RENTAL_TYPES.IS_ACTIVE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>is_active IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleRentalTypes> fetchByIsActive(Byte... values) {
        return fetch(VehicleRentalTypes.VEHICLE_RENTAL_TYPES.IS_ACTIVE, values);
    }
}
