/*
 * This file is generated by jOOQ.
 */
package com.db_access.jooq.tables.daos;


import com.db_access.jooq.tables.VehicleItems;
import com.db_access.jooq.tables.records.VehicleItemsRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class VehicleItemsDao extends DAOImpl<VehicleItemsRecord, com.db_access.jooq.tables.pojos.VehicleItems, Long> {

    /**
     * Create a new VehicleItemsDao without any configuration
     */
    public VehicleItemsDao() {
        super(VehicleItems.VEHICLE_ITEMS, com.db_access.jooq.tables.pojos.VehicleItems.class);
    }

    /**
     * Create a new VehicleItemsDao with an attached configuration
     */
    @Autowired
    public VehicleItemsDao(Configuration configuration) {
        super(VehicleItems.VEHICLE_ITEMS, com.db_access.jooq.tables.pojos.VehicleItems.class, configuration);
    }

    @Override
    public Long getId(com.db_access.jooq.tables.pojos.VehicleItems object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleItems> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(VehicleItems.VEHICLE_ITEMS.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleItems> fetchById(Long... values) {
        return fetch(VehicleItems.VEHICLE_ITEMS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.db_access.jooq.tables.pojos.VehicleItems fetchOneById(Long value) {
        return fetchOne(VehicleItems.VEHICLE_ITEMS.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.db_access.jooq.tables.pojos.VehicleItems> fetchOptionalById(Long value) {
        return fetchOptional(VehicleItems.VEHICLE_ITEMS.ID, value);
    }

    /**
     * Fetch records that have <code>vehicle_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleItems> fetchRangeOfVehicleId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(VehicleItems.VEHICLE_ITEMS.VEHICLE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>vehicle_id IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleItems> fetchByVehicleId(Long... values) {
        return fetch(VehicleItems.VEHICLE_ITEMS.VEHICLE_ID, values);
    }

    /**
     * Fetch records that have <code>code BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleItems> fetchRangeOfCode(String lowerInclusive, String upperInclusive) {
        return fetchRange(VehicleItems.VEHICLE_ITEMS.CODE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>code IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleItems> fetchByCode(String... values) {
        return fetch(VehicleItems.VEHICLE_ITEMS.CODE, values);
    }

    /**
     * Fetch records that have <code>plate_number BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleItems> fetchRangeOfPlateNumber(String lowerInclusive, String upperInclusive) {
        return fetchRange(VehicleItems.VEHICLE_ITEMS.PLATE_NUMBER, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>plate_number IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleItems> fetchByPlateNumber(String... values) {
        return fetch(VehicleItems.VEHICLE_ITEMS.PLATE_NUMBER, values);
    }

    /**
     * Fetch records that have <code>status BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleItems> fetchRangeOfStatus(Byte lowerInclusive, Byte upperInclusive) {
        return fetchRange(VehicleItems.VEHICLE_ITEMS.STATUS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleItems> fetchByStatus(Byte... values) {
        return fetch(VehicleItems.VEHICLE_ITEMS.STATUS, values);
    }

    /**
     * Fetch records that have <code>created BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleItems> fetchRangeOfCreated(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(VehicleItems.VEHICLE_ITEMS.CREATED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleItems> fetchByCreated(LocalDateTime... values) {
        return fetch(VehicleItems.VEHICLE_ITEMS.CREATED, values);
    }

    /**
     * Fetch records that have <code>created_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleItems> fetchRangeOfCreatedBy(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(VehicleItems.VEHICLE_ITEMS.CREATED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_by IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleItems> fetchByCreatedBy(Long... values) {
        return fetch(VehicleItems.VEHICLE_ITEMS.CREATED_BY, values);
    }

    /**
     * Fetch records that have <code>modified BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleItems> fetchRangeOfModified(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(VehicleItems.VEHICLE_ITEMS.MODIFIED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>modified IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleItems> fetchByModified(LocalDateTime... values) {
        return fetch(VehicleItems.VEHICLE_ITEMS.MODIFIED, values);
    }

    /**
     * Fetch records that have <code>modified_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleItems> fetchRangeOfModifiedBy(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(VehicleItems.VEHICLE_ITEMS.MODIFIED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>modified_by IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleItems> fetchByModifiedBy(Long... values) {
        return fetch(VehicleItems.VEHICLE_ITEMS.MODIFIED_BY, values);
    }

    /**
     * Fetch records that have <code>is_active BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleItems> fetchRangeOfIsActive(Byte lowerInclusive, Byte upperInclusive) {
        return fetchRange(VehicleItems.VEHICLE_ITEMS.IS_ACTIVE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>is_active IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleItems> fetchByIsActive(Byte... values) {
        return fetch(VehicleItems.VEHICLE_ITEMS.IS_ACTIVE, values);
    }
}
