/*
 * This file is generated by jOOQ.
 */
package com.db_access.jooq.tables.daos;


import com.db_access.jooq.tables.VehicleFacilities;
import com.db_access.jooq.tables.records.VehicleFacilitiesRecord;

import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class VehicleFacilitiesDao extends DAOImpl<VehicleFacilitiesRecord, com.db_access.jooq.tables.pojos.VehicleFacilities, Long> {

    /**
     * Create a new VehicleFacilitiesDao without any configuration
     */
    public VehicleFacilitiesDao() {
        super(VehicleFacilities.VEHICLE_FACILITIES, com.db_access.jooq.tables.pojos.VehicleFacilities.class);
    }

    /**
     * Create a new VehicleFacilitiesDao with an attached configuration
     */
    @Autowired
    public VehicleFacilitiesDao(Configuration configuration) {
        super(VehicleFacilities.VEHICLE_FACILITIES, com.db_access.jooq.tables.pojos.VehicleFacilities.class, configuration);
    }

    @Override
    public Long getId(com.db_access.jooq.tables.pojos.VehicleFacilities object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleFacilities> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(VehicleFacilities.VEHICLE_FACILITIES.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleFacilities> fetchById(Long... values) {
        return fetch(VehicleFacilities.VEHICLE_FACILITIES.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.db_access.jooq.tables.pojos.VehicleFacilities fetchOneById(Long value) {
        return fetchOne(VehicleFacilities.VEHICLE_FACILITIES.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.db_access.jooq.tables.pojos.VehicleFacilities> fetchOptionalById(Long value) {
        return fetchOptional(VehicleFacilities.VEHICLE_FACILITIES.ID, value);
    }

    /**
     * Fetch records that have <code>vehicle_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleFacilities> fetchRangeOfVehicleId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(VehicleFacilities.VEHICLE_FACILITIES.VEHICLE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>vehicle_id IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleFacilities> fetchByVehicleId(Long... values) {
        return fetch(VehicleFacilities.VEHICLE_FACILITIES.VEHICLE_ID, values);
    }

    /**
     * Fetch records that have <code>facility_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleFacilities> fetchRangeOfFacilityId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(VehicleFacilities.VEHICLE_FACILITIES.FACILITY_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>facility_id IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleFacilities> fetchByFacilityId(Long... values) {
        return fetch(VehicleFacilities.VEHICLE_FACILITIES.FACILITY_ID, values);
    }

    /**
     * Fetch records that have <code>qty BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleFacilities> fetchRangeOfQty(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(VehicleFacilities.VEHICLE_FACILITIES.QTY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>qty IN (values)</code>
     */
    public List<com.db_access.jooq.tables.pojos.VehicleFacilities> fetchByQty(Integer... values) {
        return fetch(VehicleFacilities.VEHICLE_FACILITIES.QTY, values);
    }
}
